version: 2

sources:
  - name: upsales_api
    description: 'Upsales raw data'
    database: "{{ target.project | default(target.database) }}"
    schema: upsales_api_{{ var('uid') }}
    tables:
      - name: accounts
      - name: activities
      - name: appointments
      - name: opportunities
      - name: orders
      - name: products
      - name: self

