name: 'enhanza_ported_package'
version: '1.0.0'
config-version: 2
profile: 'enhanza_sample'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.9.0", "<2.0.0"]

models:
  enhanza_ported_package:
    +materialized: view
