{{ config(alias=(model_alias(model.name)),
   enabled = any_source_enabled(['fortnox', 'tripletex', 'visma_eaccounting', 'visma_economic', 'xledger'])
) }}

--all rows generated by default
with new_rows as (
  select
    OrgId
    , DimensionId
    , CategoryId
  from (
    select distinct
      split(AccountId, '-')[offset(0)] OrgId
      , split(AccountId, '-')[offset(0)] || '-' || Number DimensionId
      , fm.ID3 CategoryId
    from {{ ref('erp_bi_dim_accounts') }} erp
    left join {{ source('global_ds_chart_of_accounts', 'full_mapping') }} fm
      on fm.AccountNumber = cast(erp.Number as string)
      and fm.ChartOfAccounts = 'BAS'
    where fm.ID3 is not null
  )
)

select
  *
from new_rows
where 1=1