version: 2

sources:
  - name: fortnox_api
    description: 'FORTNOX raw data'
    database: "{{ target.project | default(target.database) }}"
    schema: fortnox_api_{{ var('uid') }}
    tables:
      - name: absence_causecodes
      - name: absence_transactions
      - name: accounts
      - name: articles
      - name: assets
      - name: assets_types
      - name: attendance_transactions
      - name: budgets
      - name: company_settings
      - name: contracts
      - name: cost_centers
      - name: customers
      - name: employees
      - name: expenses
      - name: financial_years
      - name: incominggoods
      - name: invoice_accruals
      - name: invoice_payments
      - name: invoices
      - name: itemsuppliers
      - name: labels
      - name: lockedperiod
      - name: offers
      - name: orders
      - name: pricelists
      - name: prices
      - name: production_orders
      - name: projects
      - name: purchaseorders
      - name: salary_transactions
      - name: stockbalance
      - name: stockpoints
      - name: stocktakings
      - name: supplier_invoice_accruals
      - name: supplier_invoice_file_connections
      - name: supplier_invoices
      - name: suppliers
      - name: time_reporting_articles
      - name: time_reporting_registrations
      - name: v2_invoices
      - name: v2_offers
      - name: v2_orders
      - name: voucher_series
      - name: vouchers

