#!/usr/bin/env python3
"""Project dbt knowledge into Lightdash — joins, keys, PII hiding, and agent hints.

Lightdash is this repository's BI and agentic-analytics tier: the app is pinned as a
fork submodule at external/lightdash, the CLI as @lightdash/cli at the same release
(see docs/LIGHTDASH_INTEGRATION.md). Lightdash reads a dbt project directly, and since
its CLI translates MetricFlow metrics from the manifest natively (simple metrics, and
ratio/derived metrics whose inputs stay on one semantic model), **this bridge never
writes a metric**. A `meta.metrics` block restating a MetricFlow definition would be a
second source of truth — exactly what analytics rule 42 forbids.

What dbt cannot tell Lightdash, and what this script therefore owns:

- **Explore joins.** A dbt `relationships` test already declares the join — child,
  FK column, parent, parent field — so `models[].meta.joins` is derived from the tests,
  never invented. Cardinality comes only from `unique` tests (`many-to-one`, or
  `one-to-one` when the FK itself is unique-tested); where no unique test exists the
  `relationship:` key is omitted rather than guessed (rule 5). Join type is always
  `left`: MetricFlow joins dimension sources LEFT OUTER, and the Wren bridge measured
  an INNER join dropping guest-checkout orders from foreign-dim cuts.
- **Primary keys.** `meta.primary_key`, only on models that participate in a join and
  only when exactly one column carries both `unique` and `not_null` — an ambiguous key
  is reported, not chosen.
- **PII hiding.** A column whose `ontology/column-annotations.json` annotation says
  `pii: direct` gets `meta.dimension.hidden: true` in every model that declares it
  (rule 17: tagged at every model that carries it). `quasi` PII is not hidden — the
  right remedy differs per class — and a use-case without annotations hides nothing,
  reported as such rather than guessed at.
- **Agent hints.** Lightdash's AI agents read `ai_hint`. Annotated columns on join
  participants get their recorded definition, plus an additivity warning when the
  annotation says summing is wrong — the two facts a column name cannot convey.
- **The honest coverage statement.** `lightdash/knowledge/semantic-coverage.md` names
  which MetricFlow metrics the upstream translator will carry and which it skips
  (cumulative, conversion, time-offset, cross-model inputs or filters), so nobody
  reads a Lightdash project and believes it serves a metric it silently dropped.

Ownership follows the repository's insertion rules: meta blocks are inserted into the
project's own schema YAML **line-based, never a YAML round-trip** (these files carry
Jinja and comments a round-trip destroys), each block marked with an inline
`# generated: lightdash_context_sync` comment. A `meta:` without the marker is
hand-authored and left alone, reported. A file whose header names another generator
(`# GENERATED by scripts/ontology_to_dbt.py`) is refused whole — one generator never
edits another's file. Orphaned marker-owned blocks are removed on regeneration.

The no-server gate is `lightdash compile --skip-dbt-compile --skip-warehouse-catalog`:
it converts the manifest to explores and validates them entirely offline. No CLI means
skip with the remedy named, never a failure — the toolchain is optional here, like
rustc and Node everywhere else in this repository.

Nothing here reads or writes credentials. Deploying (`lightdash deploy`, previews) is
data egress and stays a human decision; the MCP registration line in
`lightdash/knowledge/mcp.md` uses environment placeholders, never token values.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

import _paths  # noqa: E402
from _manifest import Manifest, die  # noqa: E402
from dbt_column_memory import package_roots  # noqa: E402

REPO = _paths.REPO

# The inline ownership marker. Short enough to live as a YAML comment on the `meta:`
# line itself, distinctive enough that nothing else in a dbt project matches it.
MARKER = "generated: lightdash_context_sync"

# Another generator's file header. ontology_to_dbt.py stamps `# GENERATED by
# scripts/ontology_to_dbt.py — do not edit.`; any header naming a scripts/ generator
# that is not this one makes the whole file off-limits.
_FOREIGN_GENERATOR = re.compile(r"^#\s*GENERATED by scripts/(?!lightdash_context_sync)")

# The submodule pin and the CLI move together, like the WrenAI submodule and wheel.
CLI_PIN = "1.97.0"
CLI_INSTALL = f"npm install --prefix .lightdash-cli @lightdash/cli@{CLI_PIN}"


def _header(slug: str) -> str:
    return (
        "<!-- Generated by scripts/lightdash_context_sync.py — do not hand-edit.\n"
        f"     Regenerate: python3 scripts/use_case_sync.py --use-case {slug} "
        "--stage lightdash -->\n"
    )


def use_case_dir(slug: str) -> Optional[Path]:
    """`_paths.use_case_dir` bound to this module's REPO, which tests override."""
    return _paths.use_case_dir(slug, REPO)


# ---------------------------------------------------------------------------------------
# CLI resolution — env var, PATH, then the repo-local npm prefix
# ---------------------------------------------------------------------------------------


def find_lightdash_cli() -> Optional[str]:
    env = os.environ.get("LIGHTDASH_CLI")
    if env and Path(env).exists():
        return env
    from shutil import which

    on_path = which("lightdash")
    if on_path:
        return on_path
    local = REPO / ".lightdash-cli/node_modules/.bin/lightdash"
    if local.exists():
        return str(local)
    return None


# ---------------------------------------------------------------------------------------
# Derivation — joins, primary keys, PII, hints. Evidence in, meta out, nothing guessed.
# ---------------------------------------------------------------------------------------


def _test_index(man: Manifest) -> Tuple[Set[Tuple[str, str]], Set[Tuple[str, str]]]:
    """(model_uid, column) pairs carrying a `unique` / `not_null` test."""
    unique: Set[Tuple[str, str]] = set()
    not_null: Set[Tuple[str, str]] = set()
    for node in man.tests().values():
        meta = node.get("test_metadata") or {}
        attached = node.get("attached_node")
        column = node.get("column_name")
        if not attached or not column:
            continue
        if meta.get("name") == "unique":
            unique.add((attached, column))
        elif meta.get("name") == "not_null":
            not_null.add((attached, column))
    return unique, not_null


def _declared(node: Dict[str, Any], name: str) -> str:
    """The model's own declared casing for a column name.

    dbt and the warehouses match test columns case-insensitively, so a relationships
    test may say `stockPointId` where the model declares `StockPointId` — and a
    Lightdash `${table.column}` reference is case-sensitive, so the test's casing
    dangles. The declared name is the model's own fact, not an invention. Measured:
    three enhanza explores compiled PARTIAL_SUCCESS on exactly this before the fix.
    """
    cols = node.get("columns") or {}
    if name in cols:
        return name
    lowered = {c.lower(): c for c in cols}
    return lowered.get(name.lower(), name)


def derive_joins(
    man: Manifest,
) -> Tuple[Dict[str, List[Dict[str, str]]], List[str]]:
    """`meta.joins` per child model, from the manifest's relationships tests.

    Child → parent, the direction the test declares. The parent is resolved from
    `depends_on.nodes`, never by regexing the jinja in `kwargs.to` — the same rule the
    graphify emitters follow, because a name rule mints wrong nodes silently.
    """
    unique, _ = _test_index(man)
    joins: Dict[str, List[Dict[str, str]]] = {}
    skipped: List[str] = []
    seen: Set[Tuple[str, str, str, str]] = set()

    for node in man.tests().values():
        meta = node.get("test_metadata") or {}
        if meta.get("name") != "relationships":
            continue
        child_uid = node.get("attached_node") or ""
        child = man.nodes.get(child_uid) or {}
        if child.get("resource_type") != "model":
            skipped.append(f"{node.get('name', '?')}: attached to a non-model")
            continue
        parents = [
            uid
            for uid in (node.get("depends_on") or {}).get("nodes", [])
            if uid != child_uid and uid.startswith("model.")
        ]
        if len(parents) != 1:
            skipped.append(
                f"{child.get('name')}: {len(parents)} model parents, expected one"
            )
            continue
        parent_uid = parents[0]
        parent = man.nodes.get(parent_uid) or {}
        fk = node.get("column_name")
        field = (meta.get("kwargs") or {}).get("field")
        if not fk or not field:
            skipped.append(
                f"{child.get('name')} -> {parent.get('name')}: test carries no "
                "column/field pair"
            )
            continue

        fk = _declared(child, fk)
        field = _declared(parent, field)
        key = (child.get("name", ""), parent.get("name", ""), fk, field)
        if key in seen:
            continue
        seen.add(key)

        entry: Dict[str, str] = {
            "join": parent["name"],
            "sql_on": f"${{{child['name']}.{fk}}} = ${{{parent['name']}.{field}}}",
            "type": "left",
            "_fk": fk,
            "_field": field,
        }
        # Cardinality only where a unique test states it; omitted, never guessed.
        if (parent_uid, field) in unique:
            entry["relationship"] = (
                "one-to-one" if (child_uid, fk) in unique else "many-to-one"
            )
        joins.setdefault(child["name"], []).append(entry)

    # Role-playing dimensions: two FKs to one parent are ordinary dbt and fatal
    # Lightdash — an explore may join a table once unless each join carries an
    # alias. The alias is derived from the test's own FK column (content, not
    # invention), and sql_on must reference the alias: the compiler registers the
    # joined table under `alias || table`.
    for child_name, entries in joins.items():
        by_parent: Dict[str, List[Dict[str, str]]] = {}
        for entry in entries:
            by_parent.setdefault(entry["join"], []).append(entry)
        for parent_name, group in by_parent.items():
            if len(group) > 1:
                for entry in group:
                    alias = f"{parent_name}_{entry['_fk']}"
                    entry["alias"] = alias
                    entry["sql_on"] = (
                        f"${{{child_name}.{entry['_fk']}}} = "
                        f"${{{alias}.{entry['_field']}}}"
                    )
        for entry in entries:
            entry.pop("_fk", None)
            entry.pop("_field", None)
        entries.sort(key=lambda e: (e["join"], e["sql_on"]))
    return joins, skipped


def derive_primary_keys(
    man: Manifest, participants: Set[str]
) -> Tuple[Dict[str, str], List[str]]:
    """One unique+not_null column per join participant, or nothing and a reason."""
    unique, not_null = _test_index(man)
    keys: Dict[str, str] = {}
    ambiguous: List[str] = []
    by_name = {n.get("name"): uid for uid, n in man.models().items()}
    for name in sorted(participants):
        uid = by_name.get(name)
        if not uid:
            continue
        candidates = sorted(
            col for (m, col) in unique if m == uid and (m, col) in not_null
        )
        if len(candidates) == 1:
            keys[name] = candidates[0]
        elif len(candidates) > 1:
            ambiguous.append(f"{name}: {len(candidates)} unique+not_null columns")
    return keys, ambiguous


def load_annotations(use_case: Path) -> Optional[List[Dict[str, Any]]]:
    path = use_case / "ontology/column-annotations.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return None
    return data.get("columns") or []


def derive_column_meta(
    man: Manifest,
    annotations: Optional[List[Dict[str, Any]]],
    join_participants: Set[str],
) -> Tuple[Dict[Tuple[str, str], Dict[str, Any]], Dict[str, int]]:
    """(model, column) -> dimension meta, from annotations only.

    `hidden: true` for direct PII on every model that declares the column (rule 17).
    `ai_hint` (definition + additivity warning) only on join participants — the models
    a Lightdash explore actually surfaces — so hints land where an agent reads them
    instead of being sprayed over every staging model.
    """
    counts = {"pii_hidden": 0, "ai_hints": 0}
    if not annotations:
        return {}, counts

    facts: Dict[str, Dict[str, Any]] = {}
    for entry in annotations:
        name = entry.get("column")
        if name:
            facts[name] = entry

    out: Dict[Tuple[str, str], Dict[str, Any]] = {}
    for node in man.models().values():
        model = node.get("name", "")
        for column in (node.get("columns") or {}):
            fact = facts.get(column)
            if not fact:
                continue
            meta: Dict[str, Any] = {}
            if fact.get("pii") == "direct":
                meta["hidden"] = True
            if model in join_participants:
                hint_parts: List[str] = []
                definition = (fact.get("definition") or "").strip()
                if definition:
                    hint_parts.append(definition)
                additivity = fact.get("additivity")
                if additivity and additivity != "additive":
                    hint_parts.append(
                        f"Additivity: {additivity} — do not SUM without checking "
                        "the aggregation contract."
                    )
                if hint_parts:
                    meta["ai_hint"] = " ".join(hint_parts)
            if meta:
                out[(model, column)] = meta
                if meta.get("hidden"):
                    counts["pii_hidden"] += 1
                if meta.get("ai_hint"):
                    counts["ai_hints"] += 1
    return out, counts


# ---------------------------------------------------------------------------------------
# MetricFlow coverage — mirror of the upstream translator's rules at the pinned release
# ---------------------------------------------------------------------------------------

_DIMENSION_REF = re.compile(r"Dimension\(\s*'([^']+)'")
_OTHER_REF = re.compile(r"(Entity|Metric)\(\s*'")


def _filter_templates(owner: Dict[str, Any]) -> List[str]:
    filt = owner.get("filter") or {}
    if isinstance(filt, str):
        return [filt]
    return [
        f.get("where_sql_template", "")
        for f in (filt.get("where_filters") or [])
        if isinstance(f, dict)
    ]


def _filter_verdict(owner: Dict[str, Any], home_entity: str) -> Optional[str]:
    """None when every filter stays on the metric's own model, else the reason."""
    for template in _filter_templates(owner):
        if _OTHER_REF.search(template):
            return "non-Dimension filter"
        for ref in _DIMENSION_REF.findall(template):
            prefix = ref.split("__")[0]
            if prefix not in (home_entity, "metric_time"):
                return f"filter references a joined model's dimension ({ref})"
    return None


def classify_metricflow(
    man: Manifest,
) -> Tuple[List[Dict[str, str]], List[Dict[str, str]], List[str]]:
    """(translated, skipped, saved_queries) per the upstream translator's own rules.

    Mirrors @lightdash/cli {CLI_PIN}'s metricFlow.ts: simple metrics translate
    (same-model where-filters included); ratio and derived translate when every input
    is a translated metric on the same semantic model with no time offset; cumulative,
    conversion, cross-model inputs, and time-offset inputs are skipped with a warning.
    """
    measure_home: Dict[str, str] = {}  # measure name -> semantic model name
    primary_entity: Dict[str, str] = {}  # semantic model name -> primary entity
    for sm in man.semantic_models.values():
        sm_name = sm.get("name", "")
        for measure in sm.get("measures") or []:
            measure_home[measure.get("name", "")] = sm_name
        for entity in sm.get("entities") or []:
            if entity.get("type") == "primary":
                primary_entity[sm_name] = entity.get("name", "")

    metrics = {m.get("name", ""): m for m in man.metrics.values()}
    verdicts: Dict[str, Tuple[Optional[str], Optional[str]]] = {}

    def verdict(name: str, trail: Tuple[str, ...] = ()) -> Tuple[Optional[str], Optional[str]]:
        """(home semantic model, None) when translatable, (None, reason) when not."""
        if name in verdicts:
            return verdicts[name]
        if name in trail:
            return None, "cyclic metric reference"
        metric = metrics.get(name)
        if metric is None:
            return None, "references an unknown metric"
        mtype = metric.get("type", "")
        params = metric.get("type_params") or {}
        result: Tuple[Optional[str], Optional[str]]

        if mtype == "simple":
            measure = (params.get("measure") or {}).get("name", "")
            home = measure_home.get(measure)
            if home is None:
                result = (None, f"measure {measure!r} is on no semantic model")
            else:
                reason = _filter_verdict(metric, primary_entity.get(home, ""))
                result = (home, None) if reason is None else (None, reason)
        elif mtype in ("ratio", "derived"):
            if mtype == "ratio":
                inputs = [params.get("numerator") or {}, params.get("denominator") or {}]
            else:
                inputs = list(params.get("metrics") or [])
            homes: Set[str] = set()
            reason = None
            for inp in inputs:
                if isinstance(inp, str):
                    inp = {"name": inp}
                if inp.get("offset_window") or inp.get("offset_to_grain"):
                    reason = f"input {inp.get('name')!r} carries a time offset"
                    break
                home, why = verdict(inp.get("name", ""), trail + (name,))
                if why is not None:
                    reason = f"input {inp.get('name')!r}: {why}"
                    break
                homes.add(home or "")
                inner = _filter_verdict(inp, primary_entity.get(home or "", ""))
                if inner is not None:
                    reason = f"input {inp.get('name')!r}: {inner}"
                    break
            if reason is None and len(homes) > 1:
                reason = "inputs live on different semantic models"
            if reason is None:
                outer = _filter_verdict(
                    metric, primary_entity.get(next(iter(homes), ""), "")
                )
                reason = outer
            result = (next(iter(homes), None), None) if reason is None else (None, reason)
        elif mtype in ("cumulative", "conversion"):
            result = (None, f"no {mtype} metric concept in Lightdash meta tags")
        else:
            result = (None, f"unknown metric type {mtype!r}")

        verdicts[name] = result
        return result

    translated: List[Dict[str, str]] = []
    skipped: List[Dict[str, str]] = []
    for name in sorted(metrics):
        metric = metrics[name]
        home, reason = verdict(name)
        if reason is None:
            translated.append(
                {"name": name, "type": metric.get("type", ""), "model": home or ""}
            )
        else:
            skipped.append(
                {"name": name, "type": metric.get("type", ""), "reason": reason}
            )
    saved = sorted(sq.get("name", "") for sq in man.saved_queries.values())
    return translated, skipped, saved


# ---------------------------------------------------------------------------------------
# YAML surgery — line-based insert/replace of marker-owned meta blocks
# ---------------------------------------------------------------------------------------

_RE_ENTRY = re.compile(r"^(\s*)-\s+name:\s*[\"']?([\w.]+)[\"']?\s*(?:#.*)?$")
_RE_KEY = re.compile(r"^(\s*)([A-Za-z_][\w]*):")


def _span_end(lines: List[str], start: int, indent: int) -> int:
    """First index >= start whose non-blank, non-comment line is indented `indent` or less.

    Comment lines are transparent at any column: a `#` is annotation, not structure.
    Found the hard way — a commented-out data_tests block at column 0 truncated a
    model body, and the last column's generated meta was silently withheld.
    """
    i = start
    while i < len(lines):
        stripped = lines[i].rstrip("\n")
        body = stripped.strip()
        if body and not body.startswith("#") and (
            len(stripped) - len(stripped.lstrip())
        ) <= indent:
            return i
        i += 1
    return i


def _render_model_meta(pad: str, meta: Dict[str, Any]) -> List[str]:
    out = [f"{pad}meta:  # {MARKER}\n"]
    joins = meta.get("joins") or []
    if joins:
        out.append(f"{pad}  joins:\n")
        for join in joins:
            out.append(f"{pad}    - join: {join['join']}\n")
            if "alias" in join:
                out.append(f"{pad}      alias: {join['alias']}\n")
            out.append(f"{pad}      sql_on: {join['sql_on']}\n")
            out.append(f"{pad}      type: {join['type']}\n")
            if "relationship" in join:
                out.append(f"{pad}      relationship: {join['relationship']}\n")
    if meta.get("primary_key"):
        out.append(f"{pad}  primary_key: {meta['primary_key']}\n")
    return out


def _render_column_meta(pad: str, meta: Dict[str, Any]) -> List[str]:
    out = [f"{pad}meta:  # {MARKER}\n", f"{pad}  dimension:\n"]
    if meta.get("hidden"):
        out.append(f"{pad}    hidden: true\n")
    if meta.get("ai_hint"):
        out.append(f"{pad}    ai_hint: {json.dumps(meta['ai_hint'])}\n")
    return out


def _apply_meta(
    lines: List[str],
    start: int,
    end: int,
    key_indent: int,
    desired: Optional[List[str]],
    report: Dict[str, List[str]],
    label: str,
) -> Tuple[List[str], int]:
    """Insert/replace/remove the marker-owned `meta:` inside one entry body.

    Returns the new lines and the shift in length. A `meta:` without the marker —
    including one nested inside `config:` — is a hand-authored decision: reported,
    never touched, and the desired block is withheld rather than emitted beside it.
    """
    pad = " " * key_indent
    i = start
    while i < end:
        stripped = lines[i].rstrip("\n")
        match = _RE_KEY.match(stripped)
        if match and len(match.group(1)) == key_indent:
            key = match.group(2)
            if key == "meta":
                owned = MARKER in stripped
                body_end = _span_end(lines, i + 1, key_indent)
                # Trailing blank/comment lines belong to the file, not the owned
                # block: trim them out of the replacement span so a comment after
                # generated meta is never deleted, and regeneration stays idempotent.
                while body_end > i + 1 and (
                    not lines[body_end - 1].strip()
                    or lines[body_end - 1].lstrip().startswith("#")
                ):
                    body_end -= 1
                if not owned:
                    report["hand_authored"].append(label)
                    return lines, 0
                new = list(desired) if desired else []
                if lines[i:body_end] == new:
                    return lines, 0
                shifted = lines[:i] + new + lines[body_end:]
                report["replaced" if desired else "removed"].append(label)
                return shifted, len(new) - (body_end - i)
            if key == "config":
                config_end = _span_end(lines, i + 1, key_indent)
                for line in lines[i + 1 : config_end]:
                    inner = line.rstrip("\n")
                    if re.match(r"^\s*meta\s*:", inner):
                        report["hand_authored"].append(label)
                        return lines, 0
                i = config_end
                continue
        i += 1

    if desired:
        insert_at = start
        shifted = lines[:insert_at] + list(desired) + lines[insert_at:]
        report["inserted"].append(label)
        return shifted, len(desired)
    return lines, 0


def rewrite_yaml(
    text: str,
    model_meta: Dict[str, Dict[str, Any]],
    column_meta: Dict[Tuple[str, str], Dict[str, Any]],
) -> Tuple[str, Dict[str, List[str]]]:
    """Apply the desired meta to one schema file, preserving everything else."""
    report: Dict[str, List[str]] = {
        "inserted": [],
        "replaced": [],
        "removed": [],
        "hand_authored": [],
        "found_models": [],
        "found_columns": [],
    }
    lines = text.splitlines(keepends=True)
    in_models = False
    entry_indent: Optional[int] = None
    i = 0
    while i < len(lines):
        stripped = lines[i].rstrip("\n")
        if re.match(r"^models:\s*$", stripped):
            in_models = True
            entry_indent = None
            i += 1
            continue
        # Only a new top-level mapping key (sources:, seeds:, ...) ends the models
        # section — a column-0 comment or a zero-indent `- name:` list entry does
        # not, though both start with a non-space character.
        if (
            in_models
            and stripped.strip()
            and not stripped[0].isspace()
            and _RE_KEY.match(stripped)
        ):
            in_models = False
        if not in_models:
            i += 1
            continue

        entry = _RE_ENTRY.match(stripped)
        if not entry or (entry_indent is not None and len(entry.group(1)) != entry_indent):
            i += 1
            continue
        if entry_indent is None:
            entry_indent = len(entry.group(1))
        model = entry.group(2)
        key_indent = entry_indent + 2
        body_start = i + 1
        body_end = _span_end(lines, body_start, entry_indent)
        report["found_models"].append(model)

        desired = model_meta.get(model)
        rendered = _render_model_meta(" " * key_indent, desired) if desired else None
        lines, shift = _apply_meta(
            lines, body_start, body_end, key_indent,
            rendered, report, model,
        )
        body_end += shift

        # Columns of this model, inside the (possibly shifted) body.
        j = body_start
        while j < body_end:
            col_key = _RE_KEY.match(lines[j].rstrip("\n"))
            if col_key and col_key.group(2) == "columns" and len(col_key.group(1)) == key_indent:
                cols_end = _span_end(lines, j + 1, key_indent)
                k = j + 1
                # Discover the column-entry indent from the first entry, the same
                # way entry_indent is discovered for models — files indent list
                # items by 2 here, but nothing guarantees it elsewhere.
                col_entry_indent: Optional[int] = None
                while k < min(cols_end, body_end):
                    col_entry = _RE_ENTRY.match(lines[k].rstrip("\n"))
                    if (
                        col_entry
                        and len(col_entry.group(1)) > key_indent
                        and (
                            col_entry_indent is None
                            or len(col_entry.group(1)) == col_entry_indent
                        )
                    ):
                        if col_entry_indent is None:
                            col_entry_indent = len(col_entry.group(1))
                        column = col_entry.group(2)
                        report["found_columns"].append(f"{model}.{column}")
                        col_indent = col_entry_indent + 2
                        col_start = k + 1
                        col_end = _span_end(lines, col_start, col_entry_indent)
                        desired_col = column_meta.get((model, column))
                        rendered_col = (
                            _render_column_meta(" " * col_indent, desired_col)
                            if desired_col
                            else None
                        )
                        lines, shift = _apply_meta(
                            lines, col_start, col_end, col_indent,
                            rendered_col, report, f"{model}.{column}",
                        )
                        body_end += shift
                        cols_end += shift
                        k = col_end + shift
                        continue
                    k += 1
                j = cols_end
                continue
            j += 1

        i = body_end
    return "".join(lines), report


# ---------------------------------------------------------------------------------------
# Knowledge files
# ---------------------------------------------------------------------------------------


def coverage_markdown(
    slug: str,
    translated: List[Dict[str, str]],
    skipped: List[Dict[str, str]],
    saved: List[str],
    joins: Dict[str, List[Dict[str, str]]],
    join_skips: List[str],
) -> Optional[str]:
    if not (translated or skipped or joins):
        return None
    lines = [_header(slug), "# Lightdash semantic coverage\n\n"]
    lines.append(
        "What of this project's semantic layer actually reaches Lightdash, and what\n"
        "does not. MetricFlow stays the metric's source of truth; the Lightdash CLI\n"
        f"(@lightdash/cli {CLI_PIN}, the external/lightdash submodule pin) translates\n"
        "the supported subset from `manifest.json` at compile/deploy time. Nothing\n"
        "below was re-authored as a Lightdash metric — a projection that dropped a\n"
        "filter or a window would be a wrong number that plans successfully.\n\n"
    )
    if translated:
        lines.append("## Metrics Lightdash translates natively\n\n")
        for m in translated:
            lines.append(f"- `{m['name']}` ({m['type']}, on `{m['model']}`)\n")
        lines.append("\n")
    if skipped:
        lines.append("## Metrics the translator skips — served by WrenAI, not Lightdash\n\n")
        lines.append(
            "Each of these has no faithful Lightdash representation. Query them\n"
            "through the Wren metric views (`wren/views/`), where the full MetricFlow\n"
            "definition — window, offset, cross-model join — is compiled into SQL.\n\n"
        )
        for m in skipped:
            lines.append(f"- `{m['name']}` ({m['type']}): {m['reason']}\n")
        lines.append("\n")
    if saved:
        lines.append("## Saved queries\n\n")
        lines.append(
            "The translator carries metrics only; saved queries are not translated.\n"
        )
        for name in saved:
            lines.append(f"- `{name}`\n")
        lines.append("\n")
    if joins:
        lines.append("## Explore joins derived from relationships tests\n\n")
        for child in sorted(joins):
            for join in joins[child]:
                rel = join.get("relationship", "cardinality untested — omitted")
                lines.append(f"- `{child}` → `{join['join']}` on `{join['sql_on']}` ({rel})\n")
        lines.append("\n")
    if join_skips:
        lines.append("## Relationships tests that produced no join\n\n")
        for reason in join_skips:
            lines.append(f"- {reason}\n")
        lines.append("\n")
    return "".join(lines)


def mcp_markdown(slug: str) -> str:
    return "".join(
        [
            _header(slug),
            "# Lightdash MCP — agent access to this project\n\n",
            "Lightdash serves an MCP endpoint on the instance itself at\n",
            "`/api/v1/mcp` (list explores, find fields, run metric queries, render\n",
            "charts). Registration needs an instance URL and a personal access\n",
            "token — credentials, so nothing here writes a config file; export the\n",
            "environment variables and register:\n\n",
            "```bash\n",
            "export LIGHTDASH_URL=...      # your instance, e.g. https://app.lightdash.cloud\n",
            "export LIGHTDASH_API_KEY=...  # personal access token (ldpat_...)\n",
            f'claude mcp add --transport http lightdash-{slug} \\\n',
            '  "$LIGHTDASH_URL/api/v1/mcp" \\\n',
            '  --header "Authorization: ApiKey $LIGHTDASH_API_KEY"\n',
            "```\n\n",
            "Pin the server to one project with the `X-Lightdash-Project: <uuid>`\n",
            "header. The CLI uses the same variables (`LIGHTDASH_URL`,\n",
            "`LIGHTDASH_API_KEY`, `LIGHTDASH_PROJECT`) for non-interactive\n",
            "`deploy`/`validate`.\n\n",
            "`lightdash deploy` and the preview commands push this project to the\n",
            "instance — that is data egress and needs explicit per-deploy\n",
            "confirmation, the same rule as `wren genbi deploy`.\n",
        ]
    )


# ---------------------------------------------------------------------------------------
# Compile gate
# ---------------------------------------------------------------------------------------


def run_compile(cli: str, dbt_project: Path, meta_models: Set[str]) -> Dict[str, Any]:
    """`lightdash compile` with both offline flags — the no-server validation gate.

    The verdict distinguishes what the bridge caused from what it merely observed.
    Offline compile relies on YAML-declared column types (`--skip-warehouse-catalog`
    means "use types in yml"), so a project whose models declare no columns fails
    wholesale for a reason that predates this bridge — measured on enhanza-analytics:
    172 of 267 explores, none of them carrying bridge meta. Failing the stage for that
    is a gate going red on a correct state, which is how gates get switched off. So:
    `fail` only when a failing explore is one the bridge wrote meta on; otherwise the
    project's un-readiness is reported as `unready`, counted, never red.
    """
    cmd = [
        cli, "compile",
        "--project-dir", str(dbt_project),
        "--profiles-dir", str(dbt_project),
        "--skip-dbt-compile",
        "--skip-warehouse-catalog",
    ]
    # NO_COLOR/FORCE_COLOR: chalk otherwise ANSI-wraps "ERROR" in the per-explore
    # lines and the failing-explore matcher below sees nothing.
    env = dict(os.environ, CI="true", NO_COLOR="1", FORCE_COLOR="0")
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, cwd=str(dbt_project),
            timeout=300, env=env,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"status": "fail", "detail": f"lightdash compile did not run: {exc}"}
    output = (proc.stdout or "") + (proc.stderr or "")
    # The CLI adds PARTIAL_SUCCESS=y to the summary whenever any explore compiled
    # with warnings; the regex must tolerate both forms or a pre-existing failure
    # gets misread as "fail" through the tail-lines fallback.
    summary = re.search(
        r"Compiled (\d+) explores, SUCCESS=(\d+)(?: PARTIAL_SUCCESS=(\d+))? ERRORS=(\d+)",
        output,
    )
    if proc.returncode == 0:
        if not summary:
            return {"status": "ok", "detail": "ok"}
        detail = f"{summary.group(1)} explores"
        if summary.group(3) and int(summary.group(3)):
            detail += f", {summary.group(3)} partial (compile warnings)"
        return {"status": "ok", "detail": detail}

    failing = set(re.findall(r"^\s*-\s*ERROR>\s*(\S+)", output, re.MULTILINE))
    touched = sorted(failing & meta_models)
    if touched:
        return {
            "status": "fail",
            "detail": (
                f"{len(touched)} explore(s) carrying bridge meta fail offline "
                f"compile: {', '.join(touched[:5])}"
            ),
        }
    if summary:
        return {
            "status": "unready",
            "detail": (
                f"{summary.group(4)}/{summary.group(1)} explores fail offline compile "
                "with no bridge meta involved — models without YAML-declared columns "
                "have no types for `--skip-warehouse-catalog`; pre-existing, not "
                "introduced here"
            ),
        }
    tail = [ln for ln in output.strip().splitlines() if ln.strip()][-3:]
    return {"status": "fail", "detail": " / ".join(tail) or f"exit {proc.returncode}"}


# ---------------------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------------------


def _patch_file(
    node: Dict[str, Any], man: Manifest, dbt_project: Path
) -> Optional[Path]:
    """The YAML file a model's patch lives in, resolved through package roots."""
    patch = node.get("patch_path") or ""
    if "://" not in patch:
        return None
    package, rel = patch.split("://", 1)
    if package == man.project_name:
        root = dbt_project
    else:
        root = package_roots(dbt_project).get(package)
    if root is None:
        return None
    path = root / rel
    return path if path.exists() else None


def sync(
    slug: str, manifest_arg: Optional[str], check: bool
) -> Dict[str, Any]:
    use_case = use_case_dir(slug)
    if use_case is None:
        die(f"no such use-case under skill-packs/*/use-cases/: {slug}")
        return {}

    dbt_project = use_case / "dbt_project"
    if not dbt_project.exists():
        return {"status": "skip", "reason": "no dbt_project yet"}

    if manifest_arg:
        manifest_path = Path(manifest_arg).resolve()
        target = (dbt_project / "target").resolve()
        if target not in manifest_path.parents:
            return {
                "status": "skip",
                "reason": (
                    "--manifest points outside dbt_project/target/ — the derivation "
                    "and `lightdash compile` must read the same generation; re-run "
                    "dbt parse there instead"
                ),
            }
    else:
        manifest_path = dbt_project / "target/manifest.json"
    if not manifest_path.exists():
        return {
            "status": "skip",
            "reason": "no manifest — dbt parse (or artifacts/refresh.sh)",
        }

    man = Manifest.load(str(manifest_path))
    joins, join_skips = derive_joins(man)
    participants: Set[str] = set(joins)
    for entries in joins.values():
        participants.update(e["join"] for e in entries)
    keys, ambiguous = derive_primary_keys(man, participants)
    annotations = load_annotations(use_case)
    column_meta, counts = derive_column_meta(man, annotations, participants)

    model_meta: Dict[str, Dict[str, Any]] = {}
    for model in participants:
        meta: Dict[str, Any] = {}
        if joins.get(model):
            meta["joins"] = joins[model]
        if model in keys:
            meta["primary_key"] = keys[model]
        if meta:
            model_meta[model] = meta

    # Group the desired meta by the schema file that declares each model.
    by_file: Dict[Path, Tuple[Dict[str, Dict[str, Any]], Dict[Tuple[str, str], Dict[str, Any]]]] = {}
    unplaced: List[str] = []
    models_by_name = {n.get("name"): n for n in man.models().values()}
    for model in sorted(set(model_meta) | {m for (m, _c) in column_meta}):
        node = models_by_name.get(model)
        path = _patch_file(node, man, dbt_project) if node else None
        if path is None:
            unplaced.append(f"{model}: declared in no resolvable schema file")
            continue
        file_models, file_columns = by_file.setdefault(path, ({}, {}))
        if model in model_meta:
            file_models[model] = model_meta[model]
        for (m, c), meta in column_meta.items():
            if m == model:
                file_columns[(m, c)] = meta

    # A file whose evidence disappeared entirely is in no desired set, so also
    # open every patch file still carrying the marker: regeneration must remove
    # orphaned blocks, not only rewrite live ones. Found by deleting a
    # relationships test and watching its join survive.
    for node in models_by_name.values():
        path = _patch_file(node, man, dbt_project) if node else None
        if path is None or path in by_file:
            continue
        try:
            if MARKER in path.read_text(encoding="utf-8"):
                by_file[path] = ({}, {})
        except OSError:
            continue

    changed: List[str] = []
    refused: List[Dict[str, str]] = []
    hand_authored: List[str] = []
    for path in sorted(by_file):
        text = path.read_text(encoding="utf-8")
        first = text.splitlines()[0] if text else ""
        if _FOREIGN_GENERATOR.match(first):
            refused.append(
                {
                    "file": str(path.relative_to(use_case)),
                    "reason": f"owned by another generator ({first.strip()[:60]})",
                }
            )
            continue
        file_models, file_columns = by_file[path]
        new_text, report = rewrite_yaml(text, file_models, file_columns)
        hand_authored += report["hand_authored"]
        # Desired meta that landed nowhere is reported, never silent: a YAML style
        # the rewriter's grammar cannot scan must show up here, not vanish.
        rel = str(path.relative_to(use_case))
        for missing in sorted(set(file_models) - set(report["found_models"])):
            unplaced.append(f"{missing}: model entry not found in {rel}")
        found_cols = set(report["found_columns"])
        for m, c in sorted(file_columns):
            if m in report["found_models"] and f"{m}.{c}" not in found_cols:
                unplaced.append(f"{m}.{c}: column entry not found in {rel}")
        if new_text != text:
            changed.append(rel)
            if not check:
                path.write_text(new_text, encoding="utf-8")

    translated, skipped, saved = classify_metricflow(man)
    knowledge_dir = use_case / "lightdash/knowledge"
    knowledge: Dict[str, Optional[str]] = {
        "semantic-coverage.md": coverage_markdown(
            slug, translated, skipped, saved, joins, join_skips
        ),
        "mcp.md": mcp_markdown(slug),
    }
    for name, content in knowledge.items():
        path = knowledge_dir / name
        if content is None:
            if path.exists():
                changed.append(str(path.relative_to(use_case)))
                if not check:
                    path.unlink()
            continue
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            changed.append(str(path.relative_to(use_case)))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    cli = find_lightdash_cli()
    meta_models = set(model_meta) | {m for (m, _c) in column_meta}
    if check:
        # The currency gate is about bytes, not explores; the compile gate runs on
        # every real sync and in its own CLI-gated test, and skipping it here keeps
        # `--check` cheap enough to run in every suite pass.
        compile_result: Dict[str, Any] = {
            "status": "skip",
            "detail": "compile gate not run under --check; it runs on sync",
        }
    elif cli is None:
        compile_result = {
            "status": "skip",
            "detail": f"lightdash CLI not installed — {CLI_INSTALL}",
        }
    else:
        compile_result = run_compile(cli, dbt_project, meta_models)

    return {
        "status": "synced",
        "use_case": slug,
        "check": check,
        "joins": sum(len(v) for v in joins.values()),
        "join_models": len(joins),
        "joins_skipped": join_skips,
        "primary_keys": len(keys),
        "ambiguous_keys": ambiguous,
        "pii_hidden": counts["pii_hidden"],
        "ai_hints": counts["ai_hints"],
        "annotations_present": annotations is not None,
        "metricflow": {
            "translated": translated,
            "skipped": skipped,
            "saved_queries": saved,
        },
        "hand_authored": sorted(set(hand_authored)),
        "refused": refused,
        "unplaced": unplaced,
        "compile": compile_result,
        "changed": changed,
    }


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--use-case", required=True)
    parser.add_argument("--manifest")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args(argv)

    payload = sync(args.use_case, args.manifest, args.check)

    if args.format == "json":
        print(json.dumps(payload))
    elif payload["status"] == "skip":
        print(f"skip  {args.use_case}: {payload['reason']}")
    else:
        mf = payload["metricflow"]
        print(
            f"{payload['joins']} join(s) on {payload['join_models']} model(s), "
            f"{payload['primary_keys']} primary key(s), "
            f"{payload['pii_hidden']} PII column(s) hidden, "
            f"{payload['ai_hints']} ai hint(s); "
            f"metricflow: {len(mf['translated'])} translated, "
            f"{len(mf['skipped'])} skipped; "
            f"compile: {payload['compile']['status']} ({payload['compile']['detail']})"
        )
        for entry in mf["skipped"]:
            print(f"  skipped {entry['name']}: {entry['reason']}")
        for name in payload["hand_authored"]:
            print(f"  hand-authored meta left alone: {name}")
        for entry in payload["refused"]:
            print(f"  refused {entry['file']}: {entry['reason']}")
        for rel in payload["changed"]:
            verb = "would change" if args.check else "changed"
            print(f"  {verb} {rel}")
        if payload["changed"] and not args.check:
            print(
                "  re-run dbt parse (artifacts/refresh.sh) so the manifest carries "
                "the new meta before `lightdash compile`/`deploy` reads it"
            )

    if payload["status"] == "synced" and payload["compile"]["status"] == "fail":
        return 1
    if args.check and payload.get("changed"):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
