#!/usr/bin/env python3
"""Derive the MetricFlow semantic layer from the annotated conformed columns.

This is the link between what a column *means* and what an agent can *ask*. Everything
upstream of here already exists: `dbt_column_memory.py` records which raw column feeds
which conformed one, `column_annotations.py` records what the conformed column is —
`role`, `additivity`, `unit`, `pii` — and `ontology_generator.py` projects both into
`index.json`. Everything downstream already exists too: `wren_context_sync.py` compiles
each MetricFlow metric to an MDL view, so `SELECT * FROM revenue` through the engine *is*
the metric, for BI and for an agent over the per-use-case MCP server.

The middle was empty. Measured on enhanza-analytics before this: **89 annotated conformed
columns, 17 of them measures, and zero semantic models** — so the Wren stage projected
nothing, and an agent asking "how many customers" got a table list rather than a metric.

The mapping is mechanical, because every facet already answers a MetricFlow question:

    role: identifier      -> entities        (primary when the grain is tested, else foreign)
    role: timestamp       -> dimensions      type: time, granularity from `unit: date`
    role: dimension|text|flag -> dimensions  type: categorical
    role: measure         -> measures        agg from `additivity`
    pii: direct           -> withheld        (rule 17)

What it will not do is supply the two facts nobody wrote down. **A primary entity comes
from a `unique` test, never from a name shape.** `CustomerId` looks like a key in every
model that carries it, and in a per-connector model it is one; in the union of six
connectors it is not, because two systems can issue the same id. A `unique` test is the
project stating the grain in a form that fails when it is wrong — which is exactly rule 21,
and the reason the semantic layer's coverage here is a direct function of test discipline
rather than of this script's cleverness. A model with no `unique` test is **skipped and
counted, with the test that unlocks it named**.

And **`agg: sum` comes from a recorded additivity, never from a numeric type** (rule 11).
An additive measure sums. A semi-additive one needs `non_additive_dimension` — naming which
dimension it may not cross is a decision, so it is refused. A non-additive one is not a
measure at all: store the numerator and the denominator and define the ratio as a metric.
A measure whose additivity nobody recorded is refused too, because `sum` is what a reader
already assumes and emitting it silently makes the assumption authoritative.

The layer is the consumer layer, not the union and not the per-connector model. Rule 43
puts semantic models on marts; rule 7 wants one entity defined once. `logic_bi_customers`
and `logic_bi_articles` each define their entity for the whole project — declaring
`customer` primary in nineteen `fortnox_bi_*`/`shopify_bi_*` models instead would be
nineteen definitions of one entity, which is the drift the conformed layer exists to
prevent. The prefix is imported from `ontology_to_dbt` rather than restated, so the
generator that writes those models and the generator that describes them cannot disagree
about which layer they are.

Usage:
    python3 scripts/ontology_to_semantic.py --use-case <slug> --dry-run
    python3 scripts/ontology_to_semantic.py --use-case <slug> --write
    python3 scripts/ontology_to_semantic.py --use-case <slug> --check
    python3 scripts/ontology_to_semantic.py --use-case <slug> --format json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _manifest import Manifest, die  # noqa: E402
import _paths  # noqa: E402
from _paths import REPO  # noqa: E402
from ontology_to_dbt import LOGIC_PREFIX  # noqa: E402  - one definition of "consumer layer"

GENERATED_MARKER = "GENERATED by scripts/ontology_to_semantic.py"
SEMANTIC_DIR = "models/semantic"
SEMANTIC_FILE = "_semantic_models__generated.yml"

# A role that is a dimension you group by. `identifier` becomes an entity instead, and a
# `measure` becomes a measure; anything else is a column nobody classified.
CATEGORICAL_ROLES = ("dimension", "text", "flag")

# MetricFlow needs a granularity on every time dimension (rule 44) and there is exactly one
# evidence source for it here: the annotation's own unit. A `role: timestamp` with no
# `unit: date` is a column whose granularity nobody recorded.
GRANULARITY_FOR_UNIT = {"date": "day"}

# The only additivity that maps to an aggregation without a further decision.
AGG_FOR_ADDITIVITY = {"additive": "sum"}

# Why a candidate did not become part of the semantic layer. Classified rather than
# counted, because "no grain declared" and "PII withheld" are two different owners.
NO_KEY = "no-unique-test"
NO_MODEL = "no-consumer-model"
NO_TIME = "no-time-dimension"
AMBIGUOUS_TIME = "several-time-dimensions"
PII_WITHHELD = "pii-withheld"
SEMI_ADDITIVE = "semi-additive-needs-non-additive-dimension"
NON_ADDITIVE = "non-additive-not-a-measure"
UNRECORDED_ADDITIVITY = "additivity-not-recorded"
UNRESOLVED_ENTITY = "identifier-joins-to-nothing"
UNANNOTATED = "unannotated"

# dbt refuses to parse a project whose semantic layer has a time dimension and no time
# spine — not "cumulative metrics are unavailable", the whole parse. Every stage downstream
# of here reads the manifest, so writing the file into a project without one would take the
# ontology, the seeds, the graph merge and the Wren project down with it.
TIME_SPINE_MODEL = "metricflow_time_spine"


def use_case_dir(slug: str) -> Path:
    """`_paths.require_use_case_dir` bound to this module's REPO; absence exits 2."""
    return _paths.require_use_case_dir(slug, REPO)


def _load(path: Path, what: str) -> Dict[str, Any]:
    if not path.exists():
        die(f"no {what} at {path.relative_to(REPO)}")
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------------------


def snake(name: str) -> str:
    """`AccountId` -> `account_id`, `FileURL` -> `file_url`, `OrgId` -> `org_id`."""
    text = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", text)
    return re.sub(r"_+", "_", text).strip("_").lower()


def entity_name(column: str, taken: Tuple[str, ...] = ()) -> str:
    """The entity a key column identifies.

    `CustomerId` identifies a `customer`. The suffix is dropped because MetricFlow joins on
    the entity *name*, so `customer` in a dimension model and `customer` in a fact model
    are the same entity — which is the whole point of conformance. Keeping the `_id` would
    still work, but the resulting semantic layer reads as a schema rather than a business.

    Except where dropping it collides. `dim_accounts` carries `MainAccountId` *and*
    `MainAccount` — the key and its label — and stripping the suffix names both
    `main_account`. MetricFlow requires element names to be unique within a semantic model,
    so the stripped form is used only when no other column in the same model already
    answers to it; `AccountClassId` beside `AccountClass` is the same case.
    """
    stripped = re.sub(r"_?id$", "", snake(column)) or snake(column)
    return stripped if stripped not in taken else snake(column)


# ---------------------------------------------------------------------------------------
# Evidence
# ---------------------------------------------------------------------------------------


def tested_keys(man: Manifest) -> Dict[str, List[str]]:
    """Model name -> the columns a `unique` test declares unique.

    This is the grain, stated by the project in a form that fails when it is wrong. Nothing
    else in a dbt project says it: a column named `<Thing>Id` is a key in the model that
    issued it and not in the union of six systems that each issued their own.
    """
    keys: Dict[str, List[str]] = {}
    for node in man.nodes.values():
        if node.get("resource_type") != "test":
            continue
        if (node.get("test_metadata") or {}).get("name") != "unique":
            continue
        column = node.get("column_name")
        parents = (node.get("depends_on") or {}).get("nodes") or []
        if not column or not parents:
            continue
        owner = man.nodes.get(parents[0], {}).get("name")
        if owner:
            keys.setdefault(owner, []).append(column)
    return {model: sorted(set(cols)) for model, cols in keys.items()}


def not_null_columns(man: Manifest) -> Dict[str, List[str]]:
    """Model name -> the columns a `not_null` test covers.

    Read only to report the half of rule 21 a keyed model is missing. A primary entity
    column that is nullable is a real defect, but it is a defect in the *data*, not a
    reason to refuse to describe the model — so it warns rather than skips.
    """
    cols: Dict[str, List[str]] = {}
    for node in man.nodes.values():
        if node.get("resource_type") != "test":
            continue
        if (node.get("test_metadata") or {}).get("name") != "not_null":
            continue
        column = node.get("column_name")
        parents = (node.get("depends_on") or {}).get("nodes") or []
        if not column or not parents:
            continue
        owner = man.nodes.get(parents[0], {}).get("name")
        if owner:
            cols.setdefault(owner, []).append(column)
    return {model: sorted(set(c)) for model, c in cols.items()}


def has_time_spine(man: Manifest) -> bool:
    """Whether the project declares a MetricFlow time spine.

    Read from the manifest rather than by globbing for a filename, because the spine is
    whatever model carries a `time_spine:` block — dbt's own convention names it
    `metricflow_time_spine`, and this project's example does, but the name is not what
    makes it one.
    """
    if (man.data.get("semantic_manifest") or {}).get("time_spines"):
        return True
    for node in man.nodes.values():
        if node.get("resource_type") != "model":
            continue
        if node.get("time_spine") or (node.get("config") or {}).get("time_spine"):
            return True
        if node.get("name") == TIME_SPINE_MODEL:
            return True
    return False


def semantics_by_column(index: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    return {row["column"]: row for row in index.get("column_semantics") or []}


def contract_columns(memory: Dict[str, Any]) -> Dict[str, List[str]]:
    """Concept -> its conformed column list, in the order conformance agreed."""
    return {
        contract["concept"]: list(contract.get("conformed") or [])
        for contract in memory.get("contracts") or []
    }


# ---------------------------------------------------------------------------------------
# Derivation
# ---------------------------------------------------------------------------------------


@dataclass
class Refusal:
    kind: str
    subject: str
    detail: str = ""

    def as_record(self) -> Dict[str, Any]:
        return {"kind": self.kind, "subject": self.subject, "detail": self.detail}


@dataclass
class SemanticModel:
    name: str
    concept: str
    dbt_model: str
    description: str
    primary: Tuple[str, str]  # (entity name, column)
    agg_time_dimension: Optional[str] = None
    foreign: List[Tuple[str, str]] = field(default_factory=list)
    time_dimensions: List[Tuple[str, str, str]] = field(default_factory=list)
    categorical: List[Tuple[str, str, str]] = field(default_factory=list)
    measures: List[Dict[str, str]] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


def derive_model(
    concept: str,
    dbt_model: str,
    key_column: str,
    columns: List[str],
    semantics: Dict[str, Dict[str, Any]],
    joinable: Dict[str, str],
    refusals: List[Refusal],
) -> SemanticModel:
    """One semantic model from one keyed consumer model and its annotated columns.

    `joinable` maps a key column to the entity some *other* semantic model declares
    primary. An identifier that is not in it joins to nothing, and is reported rather than
    emitted — the same rule `connector_semantics_derive.py` applies to a dangling `*_id`.
    """
    taken = tuple(snake(c) for c in columns)
    model = SemanticModel(
        name=concept,
        concept=concept,
        dbt_model=dbt_model,
        description=f"Conformed {concept}. One row per {entity_name(key_column, taken)}, "
                    f"as declared by the `unique` test on {key_column}.",
        primary=(entity_name(key_column, taken), key_column),
    )
    claimed = {model.primary[0]}

    for column in columns:
        if column == key_column:
            continue
        facets = semantics.get(column)
        if not facets:
            refusals.append(Refusal(UNANNOTATED, f"{concept}.{column}"))
            continue
        if facets.get("pii") == "direct":
            # Rule 17. The column stays available upstream to anything with a reason to
            # join it; what it may not do is arrive in the layer BI and agents read.
            refusals.append(Refusal(PII_WITHHELD, f"{concept}.{column}"))
            continue

        role = facets.get("role")
        definition = (facets.get("definition") or "").strip()

        if role == "identifier":
            # An opaque id that reaches no primary entity is neither a join nor a useful
            # grouping: an agent that groups by it produces a report keyed on numbers
            # nobody can read, while the label column beside it is already a dimension.
            target = joinable.get(column)
            if not target:
                refusals.append(Refusal(
                    UNRESOLVED_ENTITY, f"{concept}.{column}",
                    "no semantic model declares it primary"))
                continue
            # The entity is named by whichever model declares it primary, so the name can
            # arrive already claimed by a local column. MetricFlow rejects a duplicate
            # element name, and silently dropping the join is better than an unparseable
            # file — but only if it is said out loud.
            # `taken` rather than `claimed` alone: a dimension later in the contract has not
            # been emitted yet but will claim its name, so checking only what has been
            # emitted so far would let the collision through in one column order and catch
            # it in another.
            if target in claimed or target in (set(taken) - {snake(column)}):
                refusals.append(Refusal(
                    UNRESOLVED_ENTITY, f"{concept}.{column}",
                    f"entity `{target}` collides with another element of {concept}"))
                continue
            claimed.add(target)
            model.foreign.append((target, column))
        elif role == "timestamp":
            granularity = GRANULARITY_FOR_UNIT.get(facets.get("unit") or "")
            if not granularity:
                refusals.append(Refusal(
                    NO_TIME, f"{concept}.{column}",
                    "role: timestamp with no `unit: date` — granularity not recorded"))
                continue
            model.time_dimensions.append((snake(column), column, granularity))
            claimed.add(snake(column))
        elif role in CATEGORICAL_ROLES:
            model.categorical.append((snake(column), column, definition))
            claimed.add(snake(column))
        elif role == "measure":
            measure = derive_measure(concept, column, facets, refusals)
            if measure:
                model.measures.append(measure)
        else:
            refusals.append(Refusal(UNANNOTATED, f"{concept}.{column}",
                                    f"role: {role or 'unset'}"))

    # An entity count is not a business decision: the `unique` test is what makes
    # count_distinct on this column exactly the number of things. It is also the one
    # measure a dimension model can carry honestly, which is why the semantic layer is
    # useful before a single fact table declares its grain.
    model.measures.insert(0, {
        "name": f"{model.primary[0]}_count",
        "agg": "count_distinct",
        "expr": key_column,
        "description": f"Distinct {model.primary[0]} count. Exact: {key_column} carries a "
                       f"`unique` test.",
    })

    # Rule 44: measures need an aggregation time dimension. One candidate is the model's
    # answer; several is a choice, and choosing changes every metric's default time grain.
    if len(model.time_dimensions) == 1:
        model.agg_time_dimension = model.time_dimensions[0][0]
    elif len(model.time_dimensions) > 1:
        refusals.append(Refusal(
            AMBIGUOUS_TIME, concept,
            "several time dimensions: " + ", ".join(t[0] for t in model.time_dimensions)))
    else:
        refusals.append(Refusal(NO_TIME, concept, "no annotated time dimension"))

    return model


def derive_measure(
    concept: str, column: str, facets: Dict[str, Any], refusals: List[Refusal]
) -> Optional[Dict[str, str]]:
    """A measure, or a refusal naming which decision is missing (rule 11)."""
    additivity = facets.get("additivity")
    if additivity == "non_additive":
        refusals.append(Refusal(
            NON_ADDITIVE, f"{concept}.{column}",
            "store the numerator and the denominator and define the ratio as a metric"))
        return None
    if additivity == "semi_additive":
        refusals.append(Refusal(
            SEMI_ADDITIVE, f"{concept}.{column}",
            "declare which dimension it may not be summed across"))
        return None
    agg = AGG_FOR_ADDITIVITY.get(additivity or "")
    if not agg:
        refusals.append(Refusal(
            UNRECORDED_ADDITIVITY, f"{concept}.{column}",
            "annotate `additivity` before this column can be aggregated"))
        return None
    description = (facets.get("definition") or "").strip()
    unit = facets.get("unit")
    if unit and description:
        description = f"{description} Unit: {unit}."
    return {
        "name": snake(column),
        "agg": agg,
        "expr": column,
        "description": description or f"{column}, summed.",
    }


def derive(use_case: Path, man: Manifest) -> Dict[str, Any]:
    """Every semantic model the annotated columns and the tested grains support."""
    index = _load(use_case / "ontology" / "index.json", "index.json")
    memory = _load(use_case / "ontology" / "column-memory.json", "column-memory.json")

    semantics = semantics_by_column(index)
    contracts = contract_columns(memory)
    keys = tested_keys(man)
    not_nulls = not_null_columns(man)
    model_names = {
        node["name"] for node in man.nodes.values() if node.get("resource_type") == "model"
    }

    refusals: List[Refusal] = []
    eligible: List[Tuple[str, str, str]] = []  # (concept, dbt model, key column)

    for concept in sorted(contracts):
        dbt_model = f"{LOGIC_PREFIX}{concept}"
        if dbt_model not in model_names:
            refusals.append(Refusal(
                NO_MODEL, concept,
                f"no {dbt_model} — run ontology_to_dbt.py --write"))
            continue
        candidates = keys.get(dbt_model) or []
        if not candidates:
            refusals.append(Refusal(
                NO_KEY, concept,
                f"{dbt_model} declares no `unique` test — rule 21"))
            continue
        if len(candidates) > 1:
            refusals.append(Refusal(
                NO_KEY, concept,
                f"{dbt_model} declares {len(candidates)} unique columns "
                f"({', '.join(candidates)}); which one is the grain is a decision"))
            continue
        eligible.append((concept, dbt_model, candidates[0]))

    # Two passes, because a foreign entity is only real once something declares it primary.
    # Resolving them in one pass would emit a join key for every `*Id` in the contract and
    # let an agent write a join that plans and returns nothing.
    joinable: Dict[str, str] = {}
    for concept, _dbt_model, key_column in eligible:
        taken = tuple(snake(c) for c in contracts[concept])
        joinable[key_column] = entity_name(key_column, taken)

    models: List[SemanticModel] = []
    for concept, dbt_model, key_column in eligible:
        model = derive_model(concept, dbt_model, key_column, contracts[concept],
                             semantics, joinable, refusals)
        if key_column not in (not_nulls.get(dbt_model) or []):
            model.warnings.append(
                f"{dbt_model}.{key_column} has `unique` but no `not_null` — rule 21 wants both")
        models.append(model)

    return {"models": models, "refusals": refusals}


# ---------------------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------------------


def _quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def measure_id(model: "SemanticModel", measure: Dict[str, Any]) -> str:
    """`<semantic model>__<measure>` — the name MetricFlow sees.

    A measure is named for its conformed column, and a conformed column is by definition
    shared: measured on this project, **7 of 17 columns annotated `measure` belong to more
    than one concept** — `ContributionValue` to five, `Net` to four, both additive. Each of
    those concepts that earns a semantic model would declare a measure `contribution_value`
    and a metric of the same name, and MetricFlow requires both to be unique across the
    whole manifest. It does not happen today only because those concepts still owe the
    `unique` test this generator refuses to invent.

    Qualified, not deduplicated. `fact_orders.ContributionValue` and
    `fact_invoices.ContributionValue` are the same *column definition* and two different
    *numbers*; keeping one and pointing the metric at it publishes a value for orders under
    a name a consumer will read as invoices — rule 42's failure mode, arrived at by tidying.

    Qualified unconditionally, too. Qualifying only on collision makes a published metric's
    name depend on which *other* concepts exist, so adding one renames a metric that BI is
    already bound to.
    """
    return f"{model.name}__{measure['name']}"


def render(slug: str, models: List[SemanticModel]) -> str:
    """The semantic models and their metrics, as one generated dbt YAML file."""
    out: List[str] = [
        "# " + GENERATED_MARKER,
        "#",
        "# Do not edit. Regenerate with:",
        f"#   python3 scripts/use_case_sync.py --use-case {slug} --stage semantic",
        "#",
        "# Every entity, dimension, and measure below is a projection of an annotated",
        "# conformed column (ontology/column-annotations.json) onto a grain the project",
        "# tests (`unique`). Nothing here is inferred from a column name: a measure with no",
        "# recorded additivity is left out rather than summed, and a model with no `unique`",
        "# test gets no semantic model at all. `--dry-run` names every refusal.",
        "",
        "version: 2",
        "",
        "semantic_models:",
    ]
    for model in models:
        out.append(f"  - name: {model.name}")
        out.append(f"    description: {_quote(model.description)}")
        out.append(f"    model: ref('{model.dbt_model}')")
        for warning in model.warnings:
            out.append(f"    # {warning}")
        if model.agg_time_dimension:
            out.append("    defaults:")
            out.append(f"      agg_time_dimension: {model.agg_time_dimension}")

        out.append("")
        out.append("    entities:")
        primary_name, primary_column = model.primary
        out.append(f"      - name: {primary_name}")
        out.append("        type: primary")
        out.append(f"        expr: {primary_column}")
        for name, column in model.foreign:
            out.append(f"      - name: {name}")
            out.append("        type: foreign")
            out.append(f"        expr: {column}")

        if model.time_dimensions or model.categorical:
            out.append("")
            out.append("    dimensions:")
            for name, column, granularity in model.time_dimensions:
                out.append(f"      - name: {name}")
                out.append("        type: time")
                out.append(f"        expr: {column}")
                out.append("        type_params:")
                out.append(f"          time_granularity: {granularity}")
            for name, column, definition in model.categorical:
                out.append(f"      - name: {name}")
                out.append("        type: categorical")
                out.append(f"        expr: {column}")
                if definition:
                    out.append(f"        description: {_quote(definition)}")

        # A measure needs an aggregation time dimension (rule 44). Without one the model
        # still describes its entities and dimensions and joins to anything that has them —
        # which is more useful than refusing to describe it at all.
        if model.agg_time_dimension:
            out.append("")
            out.append("    measures:")
            for measure in model.measures:
                out.append(f"      - name: {measure_id(model, measure)}")
                out.append(f"        agg: {measure['agg']}")
                out.append(f"        expr: {measure['expr']}")
                out.append(f"        description: {_quote(measure['description'])}")
        out.append("")

    metrics = [(m, measure) for m in models if m.agg_time_dimension for measure in m.measures]
    if metrics:
        out.append("metrics:")
        for model, measure in metrics:
            # The label stays the humanised *column* name — two concepts measuring
            # `ContributionValue` genuinely share a label, and it is the name that has to
            # tell them apart.
            out.append(f"  - name: {measure_id(model, measure)}")
            out.append(f"    label: {_quote(measure['name'].replace('_', ' ').title())}")
            out.append(f"    description: {_quote(measure['description'])}")
            out.append("    type: simple")
            out.append("    type_params:")
            out.append(f"      measure: {measure_id(model, measure)}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------------------


def summarise(payload: Dict[str, Any]) -> Dict[str, Any]:
    models: List[SemanticModel] = payload["models"]
    refusals: List[Refusal] = payload["refusals"]
    by_kind: Dict[str, int] = {}
    for refusal in refusals:
        by_kind[refusal.kind] = by_kind.get(refusal.kind, 0) + 1
    with_measures = [m for m in models if m.agg_time_dimension]
    return {
        "semantic_models": len(models),
        "with_measures": len(with_measures),
        "entities": sum(1 + len(m.foreign) for m in models),
        "dimensions": sum(len(m.time_dimensions) + len(m.categorical) for m in models),
        "measures": sum(len(m.measures) for m in with_measures),
        "metrics": sum(len(m.measures) for m in with_measures),
        "refused": by_kind,
        "warnings": [w for m in models for w in m.warnings],
    }


def run(slug: str, manifest: Optional[Path], write: bool, check: bool) -> Dict[str, Any]:
    use_case = use_case_dir(slug)
    manifest = manifest or _paths.default_manifest(use_case)
    if not manifest or not manifest.exists():
        return {"status": "skip", "reason": "no manifest — run artifacts/refresh.sh"}
    for artifact in ("index.json", "column-memory.json"):
        if not (use_case / "ontology" / artifact).exists():
            return {"status": "skip", "reason": f"no ontology/{artifact}"}

    project = _paths.project_root_of(manifest, use_case)
    if project is None:
        return {"status": "skip", "reason": "no dbt project beside the manifest"}

    man = Manifest.load(str(manifest))
    payload = derive(use_case, man)
    summary = summarise(payload)
    summary["status"] = "ok"

    target = project / SEMANTIC_DIR / SEMANTIC_FILE
    summary["path"] = str(target.relative_to(REPO))
    summary["refusals"] = [r.as_record() for r in payload["refusals"]]

    # Found by writing the file and parsing: a `time` dimension with no time spine is not a
    # missing feature, it is `Parsing Error ... none was found` and dbt builds nothing. The
    # columns, ontology, seeds, graph and wren stages all read the manifest, so a generator
    # that emitted here would take the whole use-case down to add one metric. The spine is
    # not derivable either — it needs `dbt_utils` in packages.yml and a start date that is
    # a decision, and this project declares only per-org `start_years: {}`.
    if payload["models"] and not has_time_spine(man):
        summary["status"] = "skip"
        summary["reason"] = (
            f"{len(payload['models'])} semantic model(s) ready, but the project declares no "
            f"MetricFlow time spine — dbt would refuse to parse. Add a {TIME_SPINE_MODEL} "
            f"model (dbt_utils.date_spine) and re-run; --dry-run shows what lands."
        )
        summary["changed"] = []
        return summary

    content = render(slug, payload["models"])
    existing = target.read_text(encoding="utf-8") if target.exists() else None
    changed = existing != content
    if changed and write and not check:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    summary["changed"] = [summary["path"]] if changed else []
    return summary


def report(summary: Dict[str, Any]) -> None:
    if summary.get("status") == "skip":
        print(f"semantic: skip — {summary['reason']}")
        # A skip that hid the derivation would make the blocker look like an absence of
        # work. Everything below is what lands the moment the reason is resolved.
        if not summary.get("semantic_models"):
            return
    print(f"semantic models: {summary['semantic_models']} "
          f"({summary['with_measures']} carry measures)")
    print(f"  entities {summary['entities']} · dimensions {summary['dimensions']} · "
          f"measures {summary['measures']} · metrics {summary['metrics']}")
    refused = summary.get("refused") or {}
    if refused:
        print("  refused:")
        for kind, count in sorted(refused.items(), key=lambda kv: -kv[1]):
            print(f"    {count:>4}  {kind}")
    for warning in summary.get("warnings") or []:
        print(f"  warn: {warning}")
    if summary.get("changed"):
        print(f"  would write: {summary['changed'][0]}")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Derive MetricFlow semantic models from the annotated conformed columns."
    )
    parser.add_argument("--use-case", required=True)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--write", action="store_true", help="write the generated YAML")
    parser.add_argument("--dry-run", action="store_true", help="report without writing")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the generated file is stale")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    parser.add_argument("--limit", type=int, default=40,
                        help="refusals listed in --format json (default 40)")
    args = parser.parse_args(argv)

    summary = run(args.use_case, args.manifest, write=args.write, check=args.check)
    if args.format == "json":
        summary = dict(summary)
        summary["refusals"] = (summary.get("refusals") or [])[: args.limit]
        print(json.dumps(summary, sort_keys=True))
    else:
        report(summary)
    if args.check and summary.get("changed"):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
