#!/usr/bin/env python3
"""Extract the dbt models the ontology declares and the project never built.

Every other generator here derives an artifact *from* the dbt project. This one runs the
other way: it reads what the ontology says exists — conformed concepts, their suppliers,
and what each of their columns means — and writes the business-layer models that were
never realised. Measured on enhanza-analytics: **58 concepts, 27 with an `erp_bi_*` union,
8 with a `logic_bi_*` business model**. Nineteen unions have no consumer-facing model at
all, and nothing in the project said so, because a model that does not exist produces no
lineage, no test, and no error.

The convention is copied, never invented: `logic_bi_<concept>` selecting from
`ref('erp_bi_<concept>')` aliased `d0`, gated on `any_source_enabled([...])` with the
supplier list taken from the ontology rather than typed. What it deliberately does not do
is invent business logic — the existing hand-written models rename and concatenate
(`Description || ' (' || Code || ')'`), and a generator guessing at that would produce
plausible columns nobody asked for. The generated model is a faithful projection: the
conformed columns whose meaning is recorded, under the names conformance already agreed.

Three rules decide what lands in a model, and each is an ontology fact rather than a
preference:

- **Only annotated columns.** A column with no recorded meaning cannot be documented
  (rule 34) and its additivity is unknown (rule 11), so projecting it into a consumer-facing
  model ships a field nobody can use correctly. The unannotated ones are counted, not
  silently dropped.
- **No direct-PII column** (rule 17). `pii: direct` names a person on its own; the mart is
  what BI and an agent read, and a column excluded here is still available upstream to
  anything with a reason to join it.
- **Tests come from the facets, never from a template.** `not_null` on identifiers,
  `accepted_values` on a closed domain that cited its source. No `unique`: the grain is not
  declared anywhere for these concepts, and asserting a key nobody chose is the invention
  rule 5 forbids. `eval_dbt_models.py` measures candidate-key uniqueness instead and reports
  it as evidence for a taxonomy.

Usage:
    python3 scripts/ontology_to_dbt.py --use-case <slug> --dry-run
    python3 scripts/ontology_to_dbt.py --use-case <slug> --concept dim_company --write
    python3 scripts/ontology_to_dbt.py --use-case <slug> --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _manifest import Manifest, die  # noqa: E402
import _paths  # noqa: E402
from _paths import REPO  # noqa: E402

GENERATED_MARKER = "GENERATED by scripts/ontology_to_dbt.py"
LAYER_DIR = "models/logic_bi"
UNION_PREFIX = "erp_bi_"
LOGIC_PREFIX = "logic_bi_"

# Columns the union itself adds. `DataSource` is what makes a unioned row attributable, so
# it leads every generated projection — without it a consumer cannot tell whose number it is.
UNION_COLUMNS = ("DataSource",)


def use_case_dir(slug: str) -> Path:
    """`_paths.require_use_case_dir` bound to this module's REPO; absence exits 2."""
    return _paths.require_use_case_dir(slug, REPO)


def _load(path: Path, what: str) -> Dict[str, Any]:
    if not path.exists():
        die(f"no {what} at {path.relative_to(REPO)}")
    return json.loads(path.read_text(encoding="utf-8"))


def gap_concepts(
    use_case: Path, man: Manifest
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Conformed concepts with a union and no business model, richest evidence first.

    "Richest" is the count of annotated columns, not of columns: a concept with 30 columns
    and 2 meanings recorded produces a two-column model, and ranking it above one with 18
    recorded meanings would put the thinnest output first.
    """
    ontology = use_case / "ontology"
    index = _load(ontology / "index.json", "ontology index")
    memory = _load(ontology / "column-memory.json", "column memory")
    annotations = _load(ontology / "column-annotations.json", "column annotations")

    by_column = {a["column"]: a for a in annotations.get("columns") or []}
    contracts = {c["concept"]: c for c in memory.get("contracts") or []}
    models = {n.get("name") for n in man.nodes.values() if n.get("resource_type") == "model"}

    out: List[Dict[str, Any]] = []
    for concept in index.get("concepts") or []:
        name = concept["concept"]
        if f"{UNION_PREFIX}{name}" not in models:
            continue
        if f"{LOGIC_PREFIX}{name}" in models:
            continue
        contract = contracts.get(name) or {}
        conformed = list(contract.get("conformed") or [])
        annotated = [by_column[c] for c in conformed if c in by_column]
        # `pii: direct` names a person alone. Excluded from the model, and counted, so the
        # exclusion is visible rather than looking like a column nobody recorded.
        carried = [a for a in annotated if a.get("pii") != "direct"]
        withheld = [a["column"] for a in annotated if a.get("pii") == "direct"]
        out.append({
            "concept": name,
            "model": f"{LOGIC_PREFIX}{name}",
            "union": f"{UNION_PREFIX}{name}",
            "suppliers": sorted(concept.get("implemented_by") or []),
            "conformed": len(conformed),
            "columns": carried,
            "withheld_pii": sorted(withheld),
            "unannotated": len(conformed) - len(annotated),
        })
    out.sort(key=lambda r: (-len(r["columns"]), r["concept"]))
    return out, {"concepts": len(index.get("concepts") or []), "models": len(models)}


def render_model(entry: Dict[str, Any]) -> str:
    """The model file. Shape copied from the project's own `logic_bi_*` models."""
    suppliers = ", ".join(f"'{s}'" for s in entry["suppliers"])
    lines = [
        "{{ config(",
        "    alias=(model_alias(model.name)),",
        f"        enabled = any_source_enabled([{suppliers}])",
        ") }}",
        "",
        f"-- {GENERATED_MARKER}. Regenerate with:",
        "--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write",
        "--",
        f"-- The conformed concept `{entry['concept']}`, restricted to the columns whose",
        "-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather",
        "-- than starred (rule 25) so a new upstream column cannot appear here silently.",
        "",
        "select",
    ]
    projected = list(UNION_COLUMNS) + [c["column"] for c in entry["columns"]]
    for i, column in enumerate(projected):
        prefix = "    " if i == 0 else "    , "
        lines.append(f"{prefix}d0.{column}")
    lines.append(f"from {{{{ ref('{entry['union']}') }}}} d0")
    lines.append("order by 1")
    return "\n".join(lines) + "\n"


def render_schema(entries: List[Dict[str, Any]]) -> str:
    """`schema.yml` for the generated models: descriptions and the tests the facets justify.

    Every description is the annotation's own sentence. Nothing is paraphrased into
    existence here — a column reaches this file only because somebody recorded what it
    means, which is the same bar `column_annotations.py --check` enforces.
    """
    lines = [
        f"# {GENERATED_MARKER} — do not edit.",
        "#",
        "# Descriptions are the recorded meaning of each conformed column; tests are the",
        "# ones its facets justify. `unique` is absent on purpose: no grain is declared for",
        "# these concepts, and asserting a key nobody chose would be inventing one (rule 5).",
        "",
        "version: 2",
        "",
        "models:",
    ]
    for entry in entries:
        suppliers = ", ".join(entry["suppliers"]) or "none"
        lines.append(f"  - name: {entry['model']}")
        lines.append(
            f"    description: >"
        )
        lines.append(
            f"      The conformed `{entry['concept']}`, one row per row of the union across"
        )
        lines.append(
            f"      its suppliers ({suppliers}). Carries the"
            f" {len(entry['columns'])} column(s) whose"
        )
        lines.append(
            f"      meaning is recorded; {entry['unannotated']} conformed column(s) are not"
            f" annotated yet"
        )
        if entry["withheld_pii"]:
            lines.append(
                f"      and {len(entry['withheld_pii'])} direct-PII column(s) are withheld"
                f" (rule 17)."
            )
        else:
            lines.append("      and none is withheld.")
        lines.append("    columns:")
        lines.append("      - name: DataSource")
        lines.append("        description: Which connector supplied the row.")
        for column in entry["columns"]:
            lines.append(f"      - name: {column['column']}")
            definition = str(column.get("definition") or "").replace('"', "'")
            lines.append(f'        description: "{definition}"')
            meta: List[str] = [f"role: {column.get('role')}"]
            if column.get("additivity"):
                meta.append(f"additivity: {column['additivity']}")
            if column.get("unit"):
                meta.append(f"unit: {column['unit']}")
            if column.get("pii") and column["pii"] != "none":
                meta.append(f"pii: {column['pii']}")
            lines.append("        meta:")
            for item in meta:
                lines.append(f"          {item}")
            tests: List[str] = []
            if column.get("role") == "identifier":
                tests.append("          - not_null")
            domain = column.get("domain") or None
            if domain and domain.get("values"):
                tests.append("          - accepted_values:")
                tests.append("              values:")
                for value in domain["values"]:
                    tests.append(f"                - {value}")
            if tests:
                lines.append("        data_tests:")
                lines.extend(tests)
        lines.append("")
    return "\n".join(lines) + "\n"


def generate(use_case: Path, manifest: Optional[str], concept: Optional[str]) -> Dict[str, Any]:
    project = use_case / "dbt_project"
    manifest_path = Path(manifest) if manifest else (project / "target/manifest.json")
    if not manifest_path.exists():
        die(f"no manifest at {manifest_path} — run artifacts/refresh.sh")
    man = Manifest.load(str(manifest_path))

    entries, stats = gap_concepts(use_case, man)
    if concept:
        entries = [e for e in entries if e["concept"] == concept]
        if not entries:
            die(f"{concept} is not a concept with a union and no business model")
    # A concept whose columns nobody has annotated would produce a model of one column,
    # `DataSource`, which is not a model. Reported as a gap needing annotation, not written.
    writable = [e for e in entries if e["columns"]]
    unannotated = [e["concept"] for e in entries if not e["columns"]]

    files: Dict[Path, str] = {}
    for entry in writable:
        files[project / LAYER_DIR / f"{entry['model']}.sql"] = render_model(entry)
    if writable:
        files[project / LAYER_DIR / "schema_generated.yml"] = render_schema(writable)

    return {
        "use_case": use_case.name,
        "gap": len(entries),
        "writable": len(writable),
        "blocked_on_annotation": sorted(unannotated),
        "entries": writable,
        "files": files,
        "stats": stats,
    }


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="Write the business-layer models the ontology declares and the project lacks.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--use-case", required=True)
    p.add_argument("--manifest")
    p.add_argument("--concept", help="only this conformed concept")
    p.add_argument("--write", action="store_true")
    p.add_argument("--check", action="store_true", help="exit 1 if generation would change anything")
    p.add_argument("--dry-run", action="store_true", help="report without writing")
    p.add_argument("--format", choices=("text", "json"), default="text")
    args = p.parse_args(argv)

    use_case = use_case_dir(args.use_case)
    result = generate(use_case, args.manifest, args.concept)

    changed: List[str] = []
    for path, content in sorted(result["files"].items()):
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        changed.append(str(path.relative_to(REPO)))
        if args.write and not (args.check or args.dry_run):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    payload = {
        "use_case": args.use_case,
        "concepts_with_union_and_no_model": result["gap"],
        "models_generated": result["writable"],
        "blocked_on_annotation": result["blocked_on_annotation"],
        "changed": changed,
        "columns_by_model": {
            e["model"]: len(e["columns"]) for e in result["entries"]
        },
        "withheld_pii": {
            e["model"]: e["withheld_pii"] for e in result["entries"] if e["withheld_pii"]
        },
    }
    if args.format == "json":
        print(json.dumps(payload, ensure_ascii=False))
    else:
        print(f"use-case:  {args.use_case}")
        print(f"gap:       {result['gap']} concept(s) with a union and no business model")
        print(f"generated: {result['writable']} model(s)")
        for entry in result["entries"]:
            withheld = (f", {len(entry['withheld_pii'])} PII withheld"
                        if entry["withheld_pii"] else "")
            print(f"  {entry['model']:<42} {len(entry['columns'])} column(s), "
                  f"{entry['unannotated']} unannotated{withheld}")
        if result["blocked_on_annotation"]:
            print(f"\nblocked on annotation ({len(result['blocked_on_annotation'])}): "
                  f"{', '.join(result['blocked_on_annotation'][:8])}")
        if changed and not args.write:
            print(f"\n{len(changed)} file(s) would change — pass --write")
        elif changed:
            print(f"\nwrote {len(changed)} file(s)")

    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
