#!/usr/bin/env python3
"""Render the PR decision gates as a Mermaid flowchart for a PR comment.

Used by .github/workflows/pr-decision-diagram.yml. The workflow runs each of
the repository's merge-decision gates (branch naming, Conventional Commits,
activation drift, marketplace portability, TOON serializer build, test suite),
records one `gate|status|detail` line per gate, and this script turns those
records into a markdown document containing:

- a Mermaid flowchart — the decision chain in execution order, each node
  colored pass/fail/skip, failed gates wired to the verdict with a "blocks
  merge" edge;
- a result table with the per-gate detail;
- a sticky-comment marker so the workflow updates one comment per PR instead
  of stacking new ones.

GitHub renders ```mermaid fences natively in PR comments and in
$GITHUB_STEP_SUMMARY, so the same document serves both.

Security note: PR titles and branch names are attacker-controlled on fork
PRs. They reach this script via argv (passed from env in the workflow, never
shell-interpolated) and every label goes through _escape() before it lands in
Mermaid or markdown.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

MARKER = "<!-- pr-decision-diagram -->"

_STATUS_CLASS = {"pass": "pass", "fail": "fail", "skip": "skip"}
_STATUS_ICON = {"pass": "✅", "fail": "❌", "skip": "⏭️"}
_MAX_LABEL = 60


def _escape(text: str) -> str:
    """Neutralize characters that break Mermaid labels or markdown tables."""
    out = (
        text.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "&#124;")
        .replace("`", "'")
        .replace("\n", " ")
    )
    return out


def _clip(text: str, limit: int = _MAX_LABEL) -> str:
    return text if len(text) <= limit else text[: limit - 1] + "…"


def parse_records(path: Path) -> list[dict]:
    """Parse `gate|status|detail` lines; unknown statuses become `skip`."""
    records = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        parts = line.split("|", 2)
        gate = parts[0].strip()
        status = parts[1].strip().lower() if len(parts) > 1 else "skip"
        detail = parts[2].strip() if len(parts) > 2 else ""
        if status not in _STATUS_CLASS:
            status = "skip"
        records.append({"gate": gate, "status": status, "detail": detail})
    return records


def render(records: list[dict], pr_number: str, pr_title: str, head_ref: str) -> str:
    verdict_pass = all(r["status"] != "fail" for r in records)
    lines: list[str] = [MARKER, "", "## Merge decision diagram", ""]

    # --- Mermaid flowchart: the chain of decisions in execution order -----
    lines += [
        "```mermaid",
        "flowchart TD",
        "    classDef pass fill:#1a7f37,color:#ffffff,stroke:#116329",
        "    classDef fail fill:#cf222e,color:#ffffff,stroke:#a40e26",
        "    classDef skip fill:#6e7781,color:#ffffff,stroke:#57606a",
        "    classDef verdict fill:#0969da,color:#ffffff,stroke:#0550ae",
        "    classDef blocked fill:#cf222e,color:#ffffff,stroke:#a40e26",
        "",
        f'    PR["PR #{_escape(pr_number)}: {_escape(_clip(pr_title))}'
        f'<br/>{_escape(_clip(head_ref))}"]',
    ]
    prev = "PR"
    for i, r in enumerate(records):
        node = f"G{i}"
        icon = _STATUS_ICON[r["status"]]
        label = f'{icon} {_escape(r["gate"])}'
        if r["detail"]:
            label += f'<br/>{_escape(_clip(r["detail"]))}'
        lines.append(f'    {prev} --> {node}["{label}"]:::{_STATUS_CLASS[r["status"]]}')
        prev = node
    if verdict_pass:
        lines.append(
            f'    {prev} --> V["Verdict: mergeable by repository standards"]:::verdict'
        )
    else:
        lines.append(f'    {prev} --> V["Verdict: BLOCKED"]:::blocked')
        for i, r in enumerate(records):
            if r["status"] == "fail":
                lines.append(f"    G{i} -. blocks merge .-> V")
    lines += ["```", ""]

    # --- Result table ------------------------------------------------------
    lines += ["| Gate | Result | Detail |", "|---|---|---|"]
    for r in records:
        lines.append(
            f'| {_escape(r["gate"])} | {_STATUS_ICON[r["status"]]} {r["status"]} '
            f'| {_escape(r["detail"]) or "—"} |'
        )
    lines += [
        "",
        "_Generated by `.github/workflows/pr-decision-diagram.yml` on every push "
        "to this PR; this comment is updated in place._",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--input", type=Path, required=True, help="gate|status|detail lines")
    ap.add_argument("--pr-number", default="", help="PR number (from env, untrusted-safe)")
    ap.add_argument("--pr-title", default="", help="PR title (from env, escaped here)")
    ap.add_argument("--head-ref", default="", help="head branch name (from env, escaped here)")
    ap.add_argument("--out", type=Path, required=True, help="markdown output path")
    args = ap.parse_args(argv)

    records = parse_records(args.input)
    if not records:
        print("pr_decision_diagram: no gate records found", file=sys.stderr)
        return 1
    args.out.write_text(
        render(records, args.pr_number, args.pr_title, args.head_ref), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
