#!/usr/bin/env python3
"""Project a use-case into a WrenAI semantic-layer project — import, then enrich.

WrenAI (pinned as a submodule at external/WrenAI, installed as the `wrenai` wheel) already
ships a native dbt importer: `wren context import dbt` turns a dbt project's manifest.json +
catalog.json into a Wren MDL project — models, columns, relationships from `relationships`
tests, knowledge scaffolding. This script does **not** reimplement any of that. It runs the
native importer and then writes the one thing the importer cannot know: the business context
this repository already derives.

    importer (upstream, mechanical)          enrichment (this repo's artifacts)
    ---------------------------------        -------------------------------------------
    models/<name>/metadata.yml               knowledge/rules/ontology-concepts.md
    relationships.yml (dbt tests)              <- ontology/index.json
    knowledge/rules/general.md               knowledge/rules/column-contracts.md
    knowledge/sql/*.md seed pairs              <- ontology/column-memory.json
    wren_project.yml, AGENTS.md              knowledge/caveats/adapter-drift.md
                                               <- column-memory drift findings
                                             knowledge/rules/semantic-metrics.md
                                               <- manifest metrics (MetricFlow)
                                             cubes/<name>/metadata.yml
                                               <- manifest semantic models + catalog types

Ownership is disjoint on purpose: re-running the importer with `--force` regenerates its
files and only its files, and this script's files carry a generated-by header naming the
regeneration command. Hand-authored knowledge belongs in *other* filenames — both layers
leave unknown files alone (they are reported as `stale`, never deleted).

Generation happens in a scratch directory beside the target and is diffed file-by-file, for
the same reason the other emitters do it: `--check` must write nothing, a re-run must change
nothing, and the changed-file list is the report. Nothing run-dependent goes into the tree.

Cube types are read from catalog.json — the warehouse's own answer — never guessed (rule 5).
A measure whose aggregation has no direct SQL projection, or a dimension whose expression is
not a bare catalog column, is skipped and counted in the payload rather than approximated.

Inputs that are missing produce a `skip` with the way out, not a failure: no dbt_project, no
manifest (`dbt parse`), no catalog.json (`dbt docs generate`), no `wren` CLI
(pip install -r requirements.txt). The CLI is resolved from $WREN_CLI, then PATH, then the
repository's .venv-wren/.

Usage:
    python3 scripts/wren_context_sync.py --use-case example-order-revenue-mart
    python3 scripts/wren_context_sync.py --use-case <slug> --check --format json
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _manifest import Manifest, die, load_json  # noqa: E402

REPO = Path(__file__).resolve().parent.parent

GENERATED_HEADER = (
    "<!-- Generated by scripts/wren_context_sync.py — do not hand-edit. "
    "Regenerate: python3 scripts/use_case_sync.py --use-case {slug} --stage wren -->"
)

# Files the upstream importer owns and regenerates under --force. Everything else in the
# project tree that we did not generate is someone's hand-authored context: report, never
# touch. `apps/` is agent-authored GenBI output; `.wren/` and `target/` are derived state.
UNTOUCHED_DIRS = {"apps", ".wren", "target"}

# MetricFlow aggregation -> SQL projection for a cube measure, with the result type the
# aggregation itself determines. Anything not listed has no faithful single-expression
# projection (percentile, median, sum_boolean) and is skipped, counted, and reported.
AGG_SQL = {
    "sum": ("SUM({x})", "DOUBLE"),
    "avg": ("AVG({x})", "DOUBLE"),
    "average": ("AVG({x})", "DOUBLE"),
    "count": ("COUNT({x})", "BIGINT"),
    "count_distinct": ("COUNT(DISTINCT {x})", "BIGINT"),
    "min": ("MIN({x})", None),  # result type = column type, read from the catalog
    "max": ("MAX({x})", None),
}


def use_case_dir(slug: str) -> Optional[Path]:
    matches = [p for p in REPO.glob(f"skill-packs/*/use-cases/{slug}") if p.is_dir()]
    return matches[0] if matches else None


def find_wren_cli() -> Optional[str]:
    env = os.environ.get("WREN_CLI")
    if env and Path(env).exists():
        return env
    on_path = shutil.which("wren")
    if on_path:
        return on_path
    local = REPO / ".venv-wren" / "bin" / "wren"
    return str(local) if local.exists() else None


def run_wren(cli: str, args: List[str]) -> subprocess.CompletedProcess:
    # Per-call budget deliberately below stage_wren's whole-script timeout in
    # use_case_sync.py (1800s): four wren calls at 300s each leave headroom, so the outer
    # timeout can never SIGKILL this process while the run_results sanitizer is open.
    return subprocess.run(
        [cli, *args], capture_output=True, text=True, timeout=300, cwd=REPO,
    )


def _tail(proc: subprocess.CompletedProcess) -> str:
    lines = (proc.stderr or proc.stdout).strip().splitlines()
    return lines[-1] if lines else "no output"


# ---------------------------------------------------------------------------------------
# YAML emission — small and local. The cube files are simple mappings; a hand-rolled
# emitter keeps this script standard-library like every other emitter in scripts/.
# ---------------------------------------------------------------------------------------


# Plain scalars YAML 1.1 loads as something other than a string. `on` becomes True,
# `no` becomes False, `~` becomes null — and a column literally named `no` exists in the
# wild (Norwegian country codes).
_YAML_SPECIALS = {"true", "false", "yes", "no", "on", "off", "null", "none", "y", "n", "~"}


def _yml_scalar(value: str) -> str:
    """Quote a YAML scalar defensively; identifiers pass through unquoted."""
    if value == "" or value != value.strip():
        return json.dumps(value)
    if value.lower() in _YAML_SPECIALS:
        return json.dumps(value)
    try:  # all-digit and float-ish forms (1.5, 1e3, .inf) must stay strings
        float(value)
        return json.dumps(value)
    except ValueError:
        pass
    plain = all(c.isalnum() or c in "_-." for c in value)
    return value if plain else json.dumps(value)


def cube_yaml(name: str, base_object: str, description: str,
              measures: List[Dict[str, str]], dimensions: List[Dict[str, str]],
              time_dimensions: List[Dict[str, str]]) -> str:
    lines = [f"name: {_yml_scalar(name)}", f"base_object: {_yml_scalar(base_object)}"]

    def block(key: str, items: List[Dict[str, str]]) -> None:
        if not items:
            return
        lines.append(f"{key}:")
        for item in items:
            lines.append(f"- name: {_yml_scalar(item['name'])}")
            lines.append(f"  expression: {_yml_scalar(item['expression'])}")
            lines.append(f"  type: {_yml_scalar(item['type'])}")

    block("measures", measures)
    block("dimensions", dimensions)
    block("time_dimensions", time_dimensions)
    lines.append("properties:")
    lines.append(f"  description: {_yml_scalar(description)}")
    lines.append("  source: dbt_semantic_model")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------------------
# Enrichment content
# ---------------------------------------------------------------------------------------


def concepts_markdown(index: Dict[str, Any], slug: str) -> Optional[str]:
    concepts = index.get("concepts") or []
    if not concepts:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Ontology concepts", ""]
    lines += [
        "Business concepts this use-case's ontology defines, and which connectors supply",
        "each one. A concept named here is the conformed entity; the dbt models that",
        "implement it per connector are listed in `column-contracts.md`.", "",
    ]
    for c in sorted(concepts, key=lambda x: x.get("concept", "")):
        implemented = ", ".join(sorted(c.get("implemented_by") or [])) or "none yet"
        planned = ", ".join(sorted(c.get("planned_by") or []))
        line = f"- **{c.get('concept')}** ({c.get('core_class', '?')}) — implemented by: {implemented}"
        if planned:
            line += f"; planned: {planned}"
        lines.append(line)
    gaps = index.get("gaps") or []
    if gaps:
        lines += ["", "## Coverage gaps", ""]
        for g in sorted(gaps, key=lambda x: x.get("concept", "")):
            lines.append(f"- {g.get('concept')}: {g.get('reason')}")
    return "\n".join(lines) + "\n"


def contracts_markdown(memory: Dict[str, Any], slug: str) -> Optional[str]:
    contracts = memory.get("contracts") or []
    if not contracts:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Column contracts", ""]
    lines += [
        "Conformed column lists per concept, derived from parsed column lineage across",
        "every connector's adapter model. When writing SQL against a conformed concept,",
        "these are the column names that exist on every supplier.", "",
    ]
    for c in sorted(contracts, key=lambda x: x.get("concept", "")):
        adapters = c.get("adapters") or {}
        supplier_note = ", ".join(
            f"{k} ({v})" for k, v in sorted(adapters.items())
        )
        lines.append(f"## {c.get('concept')}")
        lines.append("")
        if supplier_note:
            lines.append(f"Suppliers: {supplier_note}")
        conformed = c.get("conformed") or []
        if conformed:
            lines.append(f"Conformed columns ({len(conformed)}): " + ", ".join(conformed))
        partial = c.get("partial_for") or []
        if partial:
            lines.append(
                f"Partial (macro-generated column list, cannot be fully named): "
                + ", ".join(sorted(partial))
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def drift_markdown(memory: Dict[str, Any], slug: str) -> Optional[str]:
    drift = memory.get("drift") or []
    if not drift:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Adapter column drift", ""]
    lines += [
        "Known disagreements between connector adapters that supply the same concept.",
        "SQL that unions or compares across these connectors must account for them.", "",
    ]
    for d in sorted(drift, key=lambda x: (x.get("concept", ""), x.get("column", ""))):
        missing = ", ".join(sorted(d.get("missing_from") or [])) or "-"
        carried = ", ".join(sorted(d.get("carried_by") or [])) or "-"
        lines.append(
            f"- **{d.get('concept')}.{d.get('column')}** ({d.get('confidence')}) — "
            f"carried by: {carried}; missing from: {missing}"
        )
    return "\n".join(lines) + "\n"


def metrics_markdown(man: Manifest, slug: str) -> Optional[str]:
    metrics = man.metrics
    if not metrics:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Semantic-layer metrics", ""]
    lines += [
        "Metric definitions from the dbt semantic layer (MetricFlow). These are the",
        "canonical definitions — a query answering a metric question should reproduce",
        "the definition below, not invent a variant (one metric, one definition).", "",
    ]
    for key in sorted(metrics):
        m = metrics[key]
        name = m.get("name", key)
        lines.append(f"## {name}")
        lines.append("")
        label = m.get("label")
        if label and label != name:
            lines.append(f"Label: {label}")
        lines.append(f"Type: {m.get('type', '?')}")
        desc = " ".join((m.get("description") or "").split())
        if desc:
            lines.append(f"Definition: {desc}")
        params = m.get("type_params") or {}
        expr = params.get("expr")
        if expr:
            lines.append(f"Formula: `{expr}`")
        num, den = params.get("numerator"), params.get("denominator")
        if num or den:
            # A ratio leg can carry its own filter and alias — emea_revenue_share's
            # numerator is revenue *filtered to EMEA*. Dropping that renders the metric
            # as revenue/revenue, a wrong definition presented as canonical.
            lines.append(f"Ratio: {_metric_ref(num)} / {_metric_ref(den)}")
        flt = _filter_sql(m.get("filter"))
        if flt:
            lines.append(f"Filter: `{flt}`")
        lines.append("")
    return "\n".join(lines) + "\n"


def _filter_sql(flt: Any) -> str:
    """Flatten MetricFlow's filter shapes to the SQL templates they carry."""
    if not flt:
        return ""
    if isinstance(flt, dict):
        templates = [
            w.get("where_sql_template", "") for w in flt.get("where_filters", [])
            if isinstance(w, dict)
        ]
        flt = " AND ".join(t for t in templates if t) or flt.get("where_sql_template", "")
    return " ".join(str(flt).split())


def _metric_ref(side: Any) -> str:
    if not isinstance(side, dict):
        return f"`{side}`"
    ref = f"`{side.get('name', '?')}`"
    leg_filter = _filter_sql(side.get("filter"))
    if leg_filter:
        ref += f" filtered by `{leg_filter}`"
    if side.get("alias"):
        ref += f" (as {side['alias']})"
    return ref


def _model_name(man: Manifest, unique_id: str) -> str:
    """The model's declared name — from the manifest node, never the unique_id.

    A versioned model's unique_id is `model.<pkg>.<name>.v<version>`, so splitting the
    id string yields `v2` as the "name". The node's own `name` field is what the wrenai
    importer emits as the Wren model name, so it is the only join key that holds.
    """
    node = man.all_nodes().get(unique_id) or {}
    return node.get("name") or unique_id.rsplit(".", 1)[-1]


def build_cubes(man: Manifest, catalog: Dict[str, Any],
                slug: str) -> Tuple[Dict[str, str], List[str]]:
    """One cube per dbt semantic model, typed from the warehouse catalog."""
    cubes: Dict[str, str] = {}
    skipped: List[str] = []
    rejected: set = set()
    catalog_nodes = catalog.get("nodes") or {}

    for key in sorted(man.semantic_models):
        sm = man.semantic_models[key]
        name = sm.get("name") or key.rsplit(".", 1)[-1]
        if name in cubes or name in rejected:
            skipped.append(f"{name}: cube name collides across semantic models "
                           f"({key}); rename one — no winner is emitted silently")
            cubes.pop(name, None)
            rejected.add(name)
            continue
        model_ids = [u for u in (sm.get("depends_on") or {}).get("nodes", [])
                     if u.startswith("model.")]
        if len(model_ids) != 1:
            skipped.append(f"{name}: semantic model does not sit on exactly one model")
            continue
        base_object = _model_name(man, model_ids[0])
        catalog_cols = {
            c.lower(): (meta or {}).get("type", "")
            for c, meta in ((catalog_nodes.get(model_ids[0]) or {}).get("columns") or {}).items()
        }
        if not catalog_cols:
            skipped.append(f"{name}: {base_object} not in catalog.json")
            continue

        def column_type(expression: str) -> Optional[str]:
            return catalog_cols.get(expression.strip().lower())

        measures, dimensions, time_dimensions = [], [], []
        for ms in sm.get("measures") or []:
            agg = (ms.get("agg") or "").lower()
            template = AGG_SQL.get(agg)
            expr = (ms.get("expr") or ms.get("name") or "").strip()
            if not template or not expr:
                skipped.append(f"{name}.{ms.get('name')}: no faithful projection for agg '{agg}'")
                continue
            sql, result_type = template
            if result_type is None:  # min/max: result type is the column's own
                result_type = column_type(expr)
                if not result_type:
                    skipped.append(f"{name}.{ms.get('name')}: '{expr}' not a catalog column")
                    continue
            measures.append({
                "name": ms["name"], "expression": sql.format(x=expr), "type": result_type,
            })
        for dim in sm.get("dimensions") or []:
            expr = (dim.get("expr") or dim.get("name") or "").strip()
            ctype = column_type(expr)
            if not ctype:
                skipped.append(f"{name}.{dim.get('name')}: '{expr}' not a catalog column")
                continue
            entry = {"name": dim["name"], "expression": expr, "type": ctype}
            if (dim.get("type") or "").lower() == "time":
                time_dimensions.append(entry)
            else:
                dimensions.append(entry)

        if not measures:
            skipped.append(f"{name}: no projectable measures")
            continue
        description = " ".join((sm.get("description") or "").split()) or (
            f"Projected from dbt semantic model '{name}'."
        )
        cubes[name] = cube_yaml(name, base_object, description,
                                measures, dimensions, time_dimensions)
    return cubes, skipped


# ---------------------------------------------------------------------------------------
# Generation and diffing
# ---------------------------------------------------------------------------------------


@contextlib.contextmanager
def _model_level_tests_hidden(dbt_project: Path, man: Manifest) -> Iterator[None]:
    """Hide model-level test rows from run_results.json for the duration of the import.

    wrenai 0.13.2's importer sorts its test events by `(model, column)` and a dbt test
    with no column — a singular test, a model-level dbt_utils test — carries
    `column_name: None`, so the sort compares None to str and the whole import dies
    (wren/dbt.py:1201; fix staged at external/patches/). Dropping run_results.json
    entirely would also dodge it, but it takes the `dbt_test_status: verified` column
    enrichment with it. So only the rows the importer cannot sort are filtered, the
    original file is set aside under a distinct name, and it is restored no matter how
    the import exits.
    """
    rr = dbt_project / "target" / "run_results.json"
    backup = rr.with_suffix(".json.wren-sync-orig")
    # A finally clause does not run on SIGKILL. If a previous run was killed inside the
    # window, the sanitized copy (or nothing) is on disk and the original is stranded at
    # the backup name — heal that first, before reading, and never let a fresh rename
    # clobber the stranded copy silently.
    if backup.exists():
        backup.replace(rr)
    if not rr.exists():
        yield
        return
    columnless = {
        uid for uid, node in man.tests().items() if node.get("column_name") is None
    }
    data = load_json(str(rr), "run_results")
    kept = [r for r in data.get("results", []) if r.get("unique_id") not in columnless]
    if len(kept) == len(data.get("results", [])):
        yield
        return
    rr.rename(backup)
    try:
        rr.write_text(json.dumps({**data, "results": kept}), encoding="utf-8")
        yield
    finally:
        rr.unlink(missing_ok=True)
        backup.rename(rr)


def generate(cli: str, use_case: Path, slug: str, manifest_path: Path,
             catalog_path: Path, scratch: Path) -> Dict[str, Any]:
    """Run importer + enrichment into `scratch`; return generation stats."""
    if scratch.exists():
        shutil.rmtree(scratch)
    scratch.mkdir(parents=True)

    dbt_project = use_case / "dbt_project"
    man = Manifest.load(str(manifest_path))
    init = run_wren(cli, ["context", "init", "--empty", "--path", str(scratch)])
    if init.returncode != 0:
        die(f"wren context init failed: {_tail(init)}")
    with _model_level_tests_hidden(dbt_project, man):
        imp = run_wren(cli, [
            "context", "import", "dbt",
            "--project-dir", str(dbt_project),
            "--profiles-path", str(dbt_project / "profiles.yml"),
            "--path", str(scratch), "--force",
        ])
    if imp.returncode != 0:
        die(f"wren context import dbt failed: {_tail(imp)}")

    catalog = load_json(str(catalog_path), "catalog")

    knowledge_written = 0
    for rel, content in (
        ("knowledge/rules/ontology-concepts.md",
         concepts_markdown(_optional_json(use_case / "ontology/index.json"), slug)),
        ("knowledge/rules/column-contracts.md",
         contracts_markdown(_optional_json(use_case / "ontology/column-memory.json"), slug)),
        ("knowledge/caveats/adapter-drift.md",
         drift_markdown(_optional_json(use_case / "ontology/column-memory.json"), slug)),
        ("knowledge/rules/semantic-metrics.md", metrics_markdown(man, slug)),
    ):
        if content is None:
            continue
        target = scratch / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        knowledge_written += 1

    cubes, cubes_skipped = build_cubes(man, catalog, slug)
    for name, content in sorted(cubes.items()):
        target = scratch / "cubes" / name / "metadata.yml"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    (scratch / ".gitignore").write_text("target/\n.wren/\n", encoding="utf-8")

    validate = run_wren(cli, ["context", "validate", "--path", str(scratch)])
    if validate.returncode != 0:
        die(f"wren context validate failed: {_tail(validate)}")
    warnings = sum(
        1 for ln in validate.stdout.splitlines() if ln.strip().lower().startswith("warning")
    )
    build = run_wren(cli, ["context", "build", "--path", str(scratch)])
    if build.returncode != 0:
        die(f"wren context build failed: {_tail(build)}")
    # Build output validated, then discarded: target/ is derived state and stays out of
    # the committed tree — a fresh clone rebuilds it with one command.
    shutil.rmtree(scratch / "target", ignore_errors=True)

    models = sum(1 for _ in scratch.glob("models/*/metadata.yml"))
    relationships = 0
    rel_file = scratch / "relationships.yml"
    if rel_file.exists():
        relationships = sum(
            1 for ln in rel_file.read_text(encoding="utf-8").splitlines()
            if ln.startswith("- name:")
        )
    return {
        "models": models,
        "relationships": relationships,
        "cubes": len(cubes),
        "cubes_skipped": sorted(cubes_skipped),
        "knowledge_files": knowledge_written,
        "validate_warnings": warnings,
    }


def _optional_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    return load_json(str(path), path.name)


def _tree(root: Path) -> Dict[str, bytes]:
    files: Dict[str, bytes] = {}
    if not root.exists():
        return files
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if rel.parts and rel.parts[0] in UNTOUCHED_DIRS:
            continue
        files[str(rel)] = p.read_bytes()
    return files


# Paths the generation pipeline owns wholesale — a stale file here is an orphan of a
# renamed or deleted dbt node, not somebody's hand work.
_OWNED_PREFIXES = ("models/", "cubes/")
_OWNED_FILES = {"wren_project.yml", "relationships.yml", "AGENTS.md", ".gitignore"}


def _generation_owned(rel: str, blob: bytes) -> bool:
    if rel in _OWNED_FILES or rel.startswith(_OWNED_PREFIXES):
        return True
    # Knowledge files are shared ground: the importer's and this script's carry markers;
    # anything else there is hand-authored context (including `wren memory store` pairs).
    text = blob.decode("utf-8", errors="replace")
    return (
        "Generated by scripts/wren_context_sync.py" in text
        or "source: dbt" in text  # importer-seeded NL->SQL pairs and rules
    )


def diff_and_sync(scratch: Path, target: Path,
                  check: bool) -> Tuple[List[str], List[str], List[str]]:
    """Returns (changed, deleted, kept_stale).

    `deleted` is generation-owned orphans — a cube whose semantic model was removed, a
    model dir for a renamed dbt node. Leaving them would ship a committed tree that
    references dropped tables while `--check` stays green, so they count as changes and
    are removed on sync. `kept_stale` is everything else: hand-authored files, reported
    and never touched.
    """
    generated, committed = _tree(scratch), _tree(target)
    changed = sorted(
        rel for rel, blob in generated.items() if committed.get(rel) != blob
    )
    stale = sorted(set(committed) - set(generated))
    deleted = [rel for rel in stale if _generation_owned(rel, committed[rel])]
    kept_stale = [rel for rel in stale if rel not in set(deleted)]
    if not check:
        for rel in changed:
            dest = target / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(generated[rel])
        for rel in deleted:
            (target / rel).unlink(missing_ok=True)
    return changed, deleted, kept_stale


# ---------------------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------------------


def sync(slug: str, manifest_arg: Optional[str], check: bool) -> Dict[str, Any]:
    use_case = use_case_dir(slug)
    if not use_case:
        die(f"no such use-case under skill-packs/*/use-cases/: {slug}")

    payload: Dict[str, Any] = {"use_case": slug, "status": "skip"}

    if not (use_case / "dbt_project").exists():
        payload["reason"] = "no dbt_project yet"
        return payload
    default_manifest = use_case / "dbt_project/target/manifest.json"
    manifest_path = Path(manifest_arg) if manifest_arg else default_manifest
    # The wrenai importer always reads <dbt_project>/target/ itself; honoring a foreign
    # --manifest here would sanitize and enrich from one manifest while the importer
    # reads another — two internally consistent halves of different generations.
    if manifest_arg and manifest_path.resolve() != default_manifest.resolve():
        payload["reason"] = (
            "--manifest points outside dbt_project/target/ — the wren importer reads "
            "the project's own target; re-run dbt parse there instead"
        )
        return payload
    if not manifest_path.exists():
        payload["reason"] = "no manifest — dbt parse (or artifacts/refresh.sh)"
        return payload
    catalog_path = manifest_path.parent / "catalog.json"
    if not catalog_path.exists():
        payload["reason"] = "no catalog.json — dbt docs generate against the local target"
        return payload
    cli = find_wren_cli()
    if not cli:
        payload["reason"] = "wren CLI not installed — pip install -r requirements.txt"
        return payload

    scratch = use_case / ".wren.tmp"
    try:
        stats = generate(cli, use_case, slug, manifest_path, catalog_path, scratch)
        changed, deleted, stale = diff_and_sync(scratch, use_case / "wren", check)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    payload.update(stats)
    payload["status"] = "changed" if (changed or deleted) else "ok"
    payload["changed"] = changed
    payload["deleted"] = deleted
    payload["stale"] = stale
    return payload


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate the WrenAI semantic-layer project for a use-case: "
                    "native dbt import plus ontology/contract/metric enrichment.",
    )
    p.add_argument("--use-case", required=True, help="slug under skill-packs/*/use-cases/")
    p.add_argument("--manifest", help="manifest.json (default: <project>/target/manifest.json)")
    p.add_argument("--check", action="store_true",
                   help="write nothing; report what would change")
    p.add_argument("--format", choices=("text", "json"), default="text")
    args = p.parse_args(argv)

    payload = sync(args.use_case, args.manifest, args.check)

    if args.format == "json":
        print(json.dumps(payload, ensure_ascii=False))
    else:
        status = payload["status"]
        if status == "skip":
            print(f"skip  {payload['use_case']}: {payload['reason']}")
        else:
            print(
                f"{status:<5} {payload['use_case']}: {payload.get('models', 0)} models, "
                f"{payload.get('relationships', 0)} relationships, "
                f"{payload.get('cubes', 0)} cubes, "
                f"{payload.get('knowledge_files', 0)} knowledge files, "
                f"{payload.get('validate_warnings', 0)} validate warning(s)"
            )
            for rel in payload.get("changed", []):
                print(f"  changed  wren/{rel}")
            for rel in payload.get("deleted", []):
                print(f"  deleted  wren/{rel} (generation-owned orphan)")
            for rel in payload.get("stale", []):
                print(f"  stale    wren/{rel} (hand-authored; left alone)")
            skipped = payload.get("cubes_skipped", [])
            if skipped:
                print(f"  {len(skipped)} cube part(s) skipped rather than approximated:")
                for reason in skipped[:10]:
                    print(f"    - {reason}")

    if payload["status"] == "changed" and args.check:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
