#!/usr/bin/env python3
"""Project a use-case into a WrenAI semantic-layer project — import, then enrich.

WrenAI (pinned as a submodule at external/WrenAI, installed as the `wrenai` wheel) already
ships a native dbt importer: `wren context import dbt` turns a dbt project's manifest.json +
catalog.json into a Wren MDL project — models, columns, relationships from `relationships`
tests, knowledge scaffolding. This script does **not** reimplement any of that. It runs the
native importer and then writes the one thing the importer cannot know: the business context
this repository already derives.

    importer (upstream, mechanical)          enrichment (this repo's artifacts)
    ---------------------------------        -------------------------------------------
    models/<name>/metadata.yml               knowledge/rules/ontology-concepts.md
    relationships.yml (dbt tests)              <- ontology/index.json
    knowledge/rules/general.md               knowledge/rules/column-contracts.md
    knowledge/sql/*.md seed pairs              <- ontology/column-memory.json
    wren_project.yml, AGENTS.md              knowledge/caveats/adapter-drift.md
                                               <- column-memory drift findings
                                             knowledge/rules/semantic-metrics.md
                                               <- manifest metrics (MetricFlow)
                                             views/<name>/metadata.yml
                                               <- manifest metrics + saved queries,
                                                  typed from catalog.json

Metrics compile to MDL *views*, not cubes. A cube measure is `AGG(column)` with the
metric's filter, ratio, offset, and window silently dropped — measured on
example-order-revenue-mart, the cube's `order_total` and the metric `revenue` disagreed
by 4.4% while both looked authoritative. A view carries the whole definition as SQL, so
`SELECT * FROM revenue` through the engine *is* the metric, for BI and agents alike.
MetricFlow stays the source of truth (analytics rule 42); the view is a projection with
a generated marker, regenerated whole (wren rule 4).

Ownership is disjoint on purpose: re-running the importer with `--force` regenerates its
files and only its files, and this script's files carry a generated-by header naming the
regeneration command. Hand-authored knowledge belongs in *other* filenames — both layers
leave unknown files alone (they are reported as `stale`, never deleted).

Generation happens in a scratch directory beside the target and is diffed file-by-file, for
the same reason the other emitters do it: `--check` must write nothing, a re-run must change
nothing, and the changed-file list is the report. Nothing run-dependent goes into the tree.

Types are read from catalog.json — the warehouse's own answer — never guessed (rule 5).
A metric whose type or parameters have no faithful SQL compilation is skipped and counted
in the payload rather than approximated. Casts in the generated SQL come from the catalog
too: wren-core registers a parameterized DECIMAL model column as Utf8 when planning a
view's statement (fix staged at external/patches/), so every bare decimal measure column
is CAST to its own catalog type — a no-op at execution, correct at planning.

Inputs that are missing produce a `skip` with the way out, not a failure: no dbt_project, no
manifest (`dbt parse`), no catalog.json (`dbt docs generate`), no `wren` CLI
(pip install -r requirements.txt). The CLI is resolved from $WREN_CLI, then PATH, then the
repository's .venv-wren/.

Usage:
    python3 scripts/wren_context_sync.py --use-case example-order-revenue-mart
    python3 scripts/wren_context_sync.py --use-case <slug> --check --format json
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _manifest import Manifest, die, load_json  # noqa: E402

REPO = Path(__file__).resolve().parent.parent

GENERATED_HEADER = (
    "<!-- Generated by scripts/wren_context_sync.py — do not hand-edit. "
    "Regenerate: python3 scripts/use_case_sync.py --use-case {slug} --stage wren -->"
)

# Files the upstream importer owns and regenerates under --force. Everything else in the
# project tree that we did not generate is someone's hand-authored context: report, never
# touch. `apps/` is agent-authored GenBI output; `.wren/` and `target/` are derived state.
UNTOUCHED_DIRS = {"apps", ".wren", ".wren-home", "target"}

# Derived per-clone state at the project root: carries absolute paths, so it is
# gitignored and written straight to the target on sync — never through the scratch
# diff, never reported as stale.
UNTOUCHED_FILES = {"mcp.json"}

# MetricFlow aggregation -> SQL projection. Anything not listed has no faithful
# single-expression projection (percentile, median, sum_boolean) and is skipped,
# counted, and reported.
AGG_SQL = {
    "sum": "SUM({x})",
    "avg": "AVG({x})",
    "average": "AVG({x})",
    "count": "COUNT({x})",
    "count_distinct": "COUNT(DISTINCT {x})",
    "min": "MIN({x})",
    "max": "MAX({x})",
}

# Grain ordering for derived metrics: the view's grain is the coarsest offset any
# input carries, because a 1-month offset only aligns on a monthly series.
_GRAIN_ORDER = ("day", "week", "month", "quarter", "year")

_BARE_COLUMN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")

# MetricFlow filter templates reference dimensions as {{ Dimension('entity__name') }}.
_DIM_REF = re.compile(r"\{\{\s*Dimension\(\s*'([A-Za-z0-9_]+)__([A-Za-z0-9_]+)'\s*\)\s*\}\}")

# Saved-query group_by entries are the same call forms, as bare strings.
_SQ_TIME = re.compile(r"TimeDimension\(\s*'metric_time'\s*,\s*'([a-z]+)'\s*\)\Z")
_SQ_DIM = re.compile(r"Dimension\(\s*'([A-Za-z0-9_]+)__([A-Za-z0-9_]+)'\s*\)\Z")


def use_case_dir(slug: str) -> Optional[Path]:
    matches = [p for p in REPO.glob(f"skill-packs/*/use-cases/{slug}") if p.is_dir()]
    return matches[0] if matches else None


def find_wren_cli() -> Optional[str]:
    env = os.environ.get("WREN_CLI")
    if env and Path(env).exists():
        return env
    on_path = shutil.which("wren")
    if on_path:
        return on_path
    local = REPO / ".venv-wren" / "bin" / "wren"
    return str(local) if local.exists() else None


def run_wren(cli: str, args: List[str]) -> subprocess.CompletedProcess:
    # Per-call budget deliberately below stage_wren's whole-script timeout in
    # use_case_sync.py (1800s): four wren calls at 300s each leave headroom, so the outer
    # timeout can never SIGKILL this process while the run_results sanitizer is open.
    return subprocess.run(
        [cli, *args], capture_output=True, text=True, timeout=300, cwd=REPO,
    )


def _tail(proc: subprocess.CompletedProcess) -> str:
    lines = (proc.stderr or proc.stdout).strip().splitlines()
    return lines[-1] if lines else "no output"


# ---------------------------------------------------------------------------------------
# YAML emission — small and local. The cube files are simple mappings; a hand-rolled
# emitter keeps this script standard-library like every other emitter in scripts/.
# ---------------------------------------------------------------------------------------


# Plain scalars YAML 1.1 loads as something other than a string. `on` becomes True,
# `no` becomes False, `~` becomes null — and a column literally named `no` exists in the
# wild (Norwegian country codes).
_YAML_SPECIALS = {"true", "false", "yes", "no", "on", "off", "null", "none", "y", "n", "~"}


def _yml_scalar(value: str) -> str:
    """Quote a YAML scalar defensively; identifiers pass through unquoted."""
    if value == "" or value != value.strip():
        return json.dumps(value)
    if value.lower() in _YAML_SPECIALS:
        return json.dumps(value)
    try:  # all-digit and float-ish forms (1.5, 1e3, .inf) must stay strings
        float(value)
        return json.dumps(value)
    except ValueError:
        pass
    plain = all(c.isalnum() or c in "_-." for c in value)
    return value if plain else json.dumps(value)


def view_yaml(name: str, statement: str, description: str,
              props: List[Tuple[str, str]]) -> str:
    """An MDL view file: name + statement (block scalar) + generated marker.

    `source: dbt_metric` is the ownership marker `_generation_owned` matches on, so an
    orphaned view (its metric was renamed or removed) is deleted on the next sync while
    a hand-authored view in the same directory is reported `stale` and never touched.
    """
    lines = [f"name: {_yml_scalar(name)}", "statement: |"]
    for ln in statement.splitlines():
        lines.append(f"  {ln}" if ln.strip() else "")
    lines.append("properties:")
    lines.append(f"  description: {_yml_scalar(description)}")
    lines.append("  source: dbt_metric")
    for key, value in props:
        lines.append(f"  {key}: {_yml_scalar(str(value))}")
    return "\n".join(lines) + "\n"


def _indent(sql: str, pad: str = "  ") -> str:
    return "\n".join(pad + ln if ln.strip() else "" for ln in sql.splitlines())


# ---------------------------------------------------------------------------------------
# Enrichment content
# ---------------------------------------------------------------------------------------


def concepts_markdown(index: Dict[str, Any], slug: str) -> Optional[str]:
    concepts = index.get("concepts") or []
    if not concepts:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Ontology concepts", ""]
    lines += [
        "Business concepts this use-case's ontology defines, and which connectors supply",
        "each one. A concept named here is the conformed entity; the dbt models that",
        "implement it per connector are listed in `column-contracts.md`.", "",
    ]
    for c in sorted(concepts, key=lambda x: x.get("concept", "")):
        implemented = ", ".join(sorted(c.get("implemented_by") or [])) or "none yet"
        planned = ", ".join(sorted(c.get("planned_by") or []))
        line = f"- **{c.get('concept')}** ({c.get('core_class', '?')}) — implemented by: {implemented}"
        if planned:
            line += f"; planned: {planned}"
        lines.append(line)
    gaps = index.get("gaps") or []
    if gaps:
        lines += ["", "## Coverage gaps", ""]
        for g in sorted(gaps, key=lambda x: x.get("concept", "")):
            lines.append(f"- {g.get('concept')}: {g.get('reason')}")
    return "\n".join(lines) + "\n"


def contracts_markdown(memory: Dict[str, Any], slug: str) -> Optional[str]:
    contracts = memory.get("contracts") or []
    if not contracts:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Column contracts", ""]
    lines += [
        "Conformed column lists per concept, derived from parsed column lineage across",
        "every connector's adapter model. When writing SQL against a conformed concept,",
        "these are the column names that exist on every supplier.", "",
    ]
    for c in sorted(contracts, key=lambda x: x.get("concept", "")):
        adapters = c.get("adapters") or {}
        supplier_note = ", ".join(
            f"{k} ({v})" for k, v in sorted(adapters.items())
        )
        lines.append(f"## {c.get('concept')}")
        lines.append("")
        if supplier_note:
            lines.append(f"Suppliers: {supplier_note}")
        conformed = c.get("conformed") or []
        if conformed:
            lines.append(f"Conformed columns ({len(conformed)}): " + ", ".join(conformed))
        partial = c.get("partial_for") or []
        if partial:
            lines.append(
                f"Partial (macro-generated column list, cannot be fully named): "
                + ", ".join(sorted(partial))
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def drift_markdown(memory: Dict[str, Any], slug: str) -> Optional[str]:
    drift = memory.get("drift") or []
    if not drift:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Adapter column drift", ""]
    lines += [
        "Known disagreements between connector adapters that supply the same concept.",
        "SQL that unions or compares across these connectors must account for them.", "",
    ]
    for d in sorted(drift, key=lambda x: (x.get("concept", ""), x.get("column", ""))):
        missing = ", ".join(sorted(d.get("missing_from") or [])) or "-"
        carried = ", ".join(sorted(d.get("carried_by") or [])) or "-"
        lines.append(
            f"- **{d.get('concept')}.{d.get('column')}** ({d.get('confidence')}) — "
            f"carried by: {carried}; missing from: {missing}"
        )
    return "\n".join(lines) + "\n"


def metrics_markdown(man: Manifest, slug: str) -> Optional[str]:
    metrics = man.metrics
    if not metrics:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Semantic-layer metrics", ""]
    lines += [
        "Metric definitions from the dbt semantic layer (MetricFlow). These are the",
        "canonical definitions — a query answering a metric question should reproduce",
        "the definition below, not invent a variant (one metric, one definition).", "",
        "Each metric that compiles is also an MDL **view** of the same name:",
        "`SELECT * FROM <metric>` through the engine returns the governed series",
        "(metric_time, value). Prefer the view over re-deriving the SQL.", "",
    ]
    for key in sorted(metrics):
        m = metrics[key]
        name = m.get("name", key)
        lines.append(f"## {name}")
        lines.append("")
        label = m.get("label")
        if label and label != name:
            lines.append(f"Label: {label}")
        lines.append(f"Type: {m.get('type', '?')}")
        desc = " ".join((m.get("description") or "").split())
        if desc:
            lines.append(f"Definition: {desc}")
        params = m.get("type_params") or {}
        expr = params.get("expr")
        if expr:
            lines.append(f"Formula: `{expr}`")
        num, den = params.get("numerator"), params.get("denominator")
        if num or den:
            # A ratio leg can carry its own filter and alias — emea_revenue_share's
            # numerator is revenue *filtered to EMEA*. Dropping that renders the metric
            # as revenue/revenue, a wrong definition presented as canonical.
            lines.append(f"Ratio: {_metric_ref(num)} / {_metric_ref(den)}")
        flt = _filter_sql(m.get("filter"))
        if flt:
            lines.append(f"Filter: `{flt}`")
        lines.append("")
    return "\n".join(lines) + "\n"


def _filter_sql(flt: Any) -> str:
    """Flatten MetricFlow's filter shapes to the SQL templates they carry."""
    if not flt:
        return ""
    if isinstance(flt, dict):
        templates = [
            w.get("where_sql_template", "") for w in flt.get("where_filters", [])
            if isinstance(w, dict)
        ]
        flt = " AND ".join(t for t in templates if t) or flt.get("where_sql_template", "")
    return " ".join(str(flt).split())


def _metric_ref(side: Any) -> str:
    if not isinstance(side, dict):
        return f"`{side}`"
    ref = f"`{side.get('name', '?')}`"
    leg_filter = _filter_sql(side.get("filter"))
    if leg_filter:
        ref += f" filtered by `{leg_filter}`"
    if side.get("alias"):
        ref += f" (as {side['alias']})"
    return ref


def _model_name(man: Manifest, unique_id: str) -> str:
    """The model's declared name — from the manifest node, never the unique_id.

    A versioned model's unique_id is `model.<pkg>.<name>.v<version>`, so splitting the
    id string yields `v2` as the "name". The node's own `name` field is what the wrenai
    importer emits as the Wren model name, so it is the only join key that holds.
    """
    node = man.all_nodes().get(unique_id) or {}
    return node.get("name") or unique_id.rsplit(".", 1)[-1]


class _SemanticIndex:
    """Resolved lookups over the manifest's semantic layer and the warehouse catalog.

    Built once per generation. Everything a compiler needs to turn a metric into SQL —
    which semantic model a measure lives on, which single dbt model that sits on, the
    catalog type of a column, which model is the time spine — resolved here so each
    metric compiler stays a straight-line SQL builder.
    """

    def __init__(self, man: Manifest, catalog: Dict[str, Any]) -> None:
        self.man = man
        self._cat: Dict[str, Dict[str, str]] = {
            uid: {
                c.lower(): (meta or {}).get("type", "")
                for c, meta in ((node or {}).get("columns") or {}).items()
            }
            for uid, node in (catalog.get("nodes") or {}).items()
        }
        self.sms: Dict[str, Dict[str, Any]] = {}
        self.sm_model: Dict[str, Optional[Tuple[str, str]]] = {}
        self.measure_sm: Dict[str, str] = {}
        self.primary_entity: Dict[str, str] = {}
        for key in sorted(man.semantic_models):
            sm = man.semantic_models[key]
            name = sm.get("name") or key.rsplit(".", 1)[-1]
            self.sms[name] = sm
            model_ids = [u for u in (sm.get("depends_on") or {}).get("nodes", [])
                         if u.startswith("model.")]
            self.sm_model[name] = (
                (model_ids[0], _model_name(man, model_ids[0]))
                if len(model_ids) == 1 else None
            )
            for m in sm.get("measures") or []:
                self.measure_sm.setdefault(m.get("name", ""), name)
            for e in sm.get("entities") or []:
                if (e.get("type") or "").lower() == "primary":
                    self.primary_entity.setdefault(e.get("name", ""), name)
        self.metrics: Dict[str, Dict[str, Any]] = {}
        for key in sorted(man.metrics):
            m = man.metrics[key]
            self.metrics[m.get("name") or key.rsplit(".", 1)[-1]] = m
        # The time spine comes from the manifest's own declaration
        # (`time_spine.standard_granularity_column` on a model) — never from a
        # name convention (rule 5). No declaration means cumulative metrics and
        # timespine fills are skipped and counted, not guessed.
        self.spine: Optional[Tuple[str, str]] = None
        for uid in sorted(man.models()):
            ts = man.models()[uid].get("time_spine")
            if isinstance(ts, dict) and ts.get("standard_granularity_column"):
                self.spine = (_model_name(man, uid), ts["standard_granularity_column"])
                break

    def catalog_type(self, model_uid: str, column: str) -> Optional[str]:
        return self._cat.get(model_uid, {}).get(column.strip().lower())

    def model_in_catalog(self, model_uid: str) -> bool:
        return bool(self._cat.get(model_uid))


def _typed_column(idx: _SemanticIndex, model_uid: str, model: str, expr: str) -> str:
    """Qualify a bare column and make its type visible to the planner.

    wren-core's `map_data_type` matches `decimal`/`numeric` as exact strings, so a
    parameterized `DECIMAL(28, 6)` from the catalog registers as Utf8 and any aggregate
    over it fails to plan *inside a view statement* (model queries never plan the user's
    aggregate, which is why the importer's output works unchanged). CAST to the column's
    own catalog type is a no-op at execution and correct at planning. Fix staged at
    external/patches/; measured on example-order-revenue-mart.

    Non-bare expressions pass through untouched: their component columns are the model's
    own and the planner infers from them.
    """
    if not _BARE_COLUMN.match(expr):
        return expr
    ctype = idx.catalog_type(model_uid, expr) or ""
    base = ctype.split("(")[0].strip().lower()
    if "(" in ctype and base in ("decimal", "numeric"):
        return f"CAST({model}.{expr} AS {ctype.replace(' ', '')})"
    return f"{model}.{expr}"


def _resolve_dim(idx: _SemanticIndex, base_sm_name: str, entity: str,
                 dim_name: str) -> Tuple[Optional[str], Optional[Tuple[str, str]], Optional[str]]:
    """Resolve `entity__dim` to (sql_expr, join_or_None, err).

    Same-model dimensions qualify against the base model. A foreign dimension joins
    through the base semantic model's foreign entity of the same name — MetricFlow's
    own join rule — and anything that cannot be resolved that way is an error the
    caller turns into a skip, never a guess.
    """
    target_sm_name = idx.primary_entity.get(entity)
    if not target_sm_name:
        return None, None, f"no semantic model has primary entity '{entity}'"
    sm = idx.sms[target_sm_name]
    dim = next((d for d in sm.get("dimensions") or [] if d.get("name") == dim_name), None)
    if dim is None:
        return None, None, f"dimension '{dim_name}' not on semantic model '{target_sm_name}'"
    expr = (dim.get("expr") or dim.get("name") or "").strip()
    tinfo = idx.sm_model.get(target_sm_name)
    if not tinfo:
        return None, None, f"semantic model '{target_sm_name}' does not sit on exactly one model"
    _, tmodel = tinfo
    col = f"{tmodel}.{expr}" if _BARE_COLUMN.match(expr) else expr
    if target_sm_name == base_sm_name:
        return col, None, None
    base = idx.sms[base_sm_name]
    fk = next((e for e in base.get("entities") or []
               if e.get("name") == entity and (e.get("type") or "").lower() == "foreign"), None)
    if fk is None:
        return None, None, f"'{base_sm_name}' has no foreign entity '{entity}' to join through"
    pk = next((e for e in sm.get("entities") or []
               if e.get("name") == entity and (e.get("type") or "").lower() == "primary"), None)
    binfo = idx.sm_model.get(base_sm_name)
    if not binfo or pk is None:
        return None, None, f"cannot derive the join for entity '{entity}'"
    fk_expr = (fk.get("expr") or fk.get("name") or "").strip()
    pk_expr = (pk.get("expr") or pk.get("name") or "").strip()
    join = (tmodel, f"{binfo[1]}.{fk_expr} = {tmodel}.{pk_expr}")
    return col, join, None


def _render_filter(idx: _SemanticIndex, base_sm_name: str,
                   flt: Any) -> Tuple[Optional[str], List[Tuple[str, str]], Optional[str]]:
    """MetricFlow where-template -> (sql, joins, err). Empty filter -> ("", [], None)."""
    raw = _filter_sql(flt)
    if not raw:
        return "", [], None
    joins: List[Tuple[str, str]] = []
    errs: List[str] = []

    def sub(m: "re.Match[str]") -> str:
        col, join, err = _resolve_dim(idx, base_sm_name, m.group(1), m.group(2))
        if err:
            errs.append(err)
            return m.group(0)
        if join and join not in joins:
            joins.append(join)
        return col or m.group(0)

    sql = _DIM_REF.sub(sub, raw)
    if errs:
        return None, [], "; ".join(errs)
    if "{{" in sql:
        return None, [], f"unsupported template in filter: {raw}"
    return sql, joins, None


def _grouped_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any], value_alias: str,
                        grain: Optional[str] = None,
                        dims: Tuple[Tuple[str, str, str], ...] = (),
                        extra_filters: Tuple[Any, ...] = (),
                        timespine: bool = True,
                        ) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """The core builder: a simple metric as (metric_time[, dims], AGG) SQL.

    Everything else composes it — ratio legs, derived inputs, the cumulative daily
    series, and saved-query cuts all reduce to this with a grain override, extra
    dimensions, or extra filters.

    `dims` entries are (alias, entity, dim_name). With no dims, a measure that declares
    `join_to_timespine` gets the spine join and its `fill_nulls_with`, bounded to the
    observed data range; with dims the fill is not applied (a per-combination fill needs
    the dimension domain, which SQL from one model cannot know) and `meta["filled"]`
    says so — visible, not silent.
    """
    tp = metric.get("type_params") or {}
    mref = tp.get("measure") or {}
    mname = mref.get("name") or ""
    sm_name = idx.measure_sm.get(mname)
    if not sm_name:
        return None, None, f"measure '{mname}' not on any semantic model"
    sm = idx.sms[sm_name]
    minfo = idx.sm_model.get(sm_name)
    if not minfo:
        return None, None, f"semantic model '{sm_name}' does not sit on exactly one model"
    model_uid, model = minfo
    if not idx.model_in_catalog(model_uid):
        return None, None, f"{model} not in catalog.json — dbt docs generate"
    measure = next((m for m in sm.get("measures") or [] if m.get("name") == mname), None)
    agg = ((measure or {}).get("agg") or "").lower()
    template = AGG_SQL.get(agg)
    if not template:
        return None, None, f"no faithful SQL for agg '{agg}'"
    agg_sql = template.format(
        x=_typed_column(idx, model_uid, model, (measure.get("expr") or mname).strip())
    )

    td_name = measure.get("agg_time_dimension") or (sm.get("defaults") or {}).get("agg_time_dimension")
    td = next((d for d in sm.get("dimensions") or [] if d.get("name") == td_name), None)
    if td is None:
        return None, None, f"agg_time_dimension '{td_name}' not found on '{sm_name}'"
    t_expr = (td.get("expr") or td.get("name") or "").strip()
    if _BARE_COLUMN.match(t_expr):
        t_expr = f"{model}.{t_expr}"
    g = grain or ((td.get("type_params") or {}).get("time_granularity") or "day")

    joins: List[Tuple[str, str]] = []
    where: List[str] = []
    for f in (metric.get("filter"), mref.get("filter"), *extra_filters):
        sql_f, f_joins, err = _render_filter(idx, sm_name, f)
        if err:
            return None, None, err
        if sql_f:
            where.append(f"({sql_f})")
            for j in f_joins:
                if j not in joins:
                    joins.append(j)
    dim_cols: List[Tuple[str, str]] = []
    for alias, entity, dname in dims:
        col, join, err = _resolve_dim(idx, sm_name, entity, dname)
        if err:
            return None, None, err
        if join and join not in joins:
            joins.append(join)
        dim_cols.append((alias, col or ""))

    select = [f"date_trunc('{g}', {t_expr}) AS metric_time"]
    select += [f"{col} AS {alias}" for alias, col in dim_cols]
    select.append(f"{agg_sql} AS {value_alias}")
    frm = model
    # LEFT, because MetricFlow joins dimension sources LEFT OUTER: a base row with a
    # NULL or unmatched foreign key stays in the aggregate (NULL dimension value).
    # An INNER join silently dropped those rows — measured on the demo data, 15
    # guest-checkout orders and $9,197.66 of revenue vanished from any foreign-dim
    # cut. Filters like `region = 'EMEA'` are unaffected (NULL never equals), and
    # `region IS NULL` now means what MetricFlow means by it.
    for jmodel, cond in joins:
        frm += f"\n  LEFT JOIN {jmodel} ON {cond}"
    sql = "SELECT " + ",\n       ".join(select) + f"\nFROM {frm}"
    if where:
        sql += "\nWHERE " + "\n  AND ".join(where)
    sql += "\nGROUP BY " + ", ".join(str(i + 1) for i in range(1 + len(dim_cols)))

    filled = False
    if timespine and not dims and mref.get("join_to_timespine") and idx.spine:
        spine_model, spine_col = idx.spine
        fill = mref.get("fill_nulls_with")
        value = (f"COALESCE(base.{value_alias}, {fill})" if fill is not None
                 else f"base.{value_alias}")
        sql = (
            f"WITH base AS (\n{_indent(sql)}\n),\n"
            f"spine AS (\n"
            f"  SELECT DISTINCT date_trunc('{g}', CAST({spine_col} AS TIMESTAMP)) AS metric_time\n"
            f"  FROM {spine_model}\n"
            f")\n"
            f"SELECT spine.metric_time, {value} AS {value_alias}\n"
            f"FROM spine LEFT JOIN base ON base.metric_time = spine.metric_time\n"
            f"WHERE spine.metric_time BETWEEN (SELECT MIN(metric_time) FROM base)\n"
            f"                            AND (SELECT MAX(metric_time) FROM base)"
        )
        filled = True
    return sql, {"grain": g, "filled": filled}, None


def _ratio_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any], name: str,
                      grain: Optional[str] = None,
                      dims: Tuple[Tuple[str, str, str], ...] = (),
                      extra_filters: Tuple[Any, ...] = (),
                      ) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """Ratio = numerator CTE / denominator CTE joined on the group keys.

    The denominator drives the series (LEFT JOIN) and a missing numerator group is 0,
    not NULL — a day with no EMEA revenue has share 0, it does not vanish.
    """
    tp = metric.get("type_params") or {}
    legs: Dict[str, Tuple[str, Dict[str, Any]]] = {}
    for role, alias in (("numerator", "num"), ("denominator", "den")):
        ref = tp.get(role)
        if not isinstance(ref, dict) or not ref.get("name"):
            return None, None, f"{role} is not a metric reference"
        # A leg-level offset would compile as the plain metric with the offset
        # silently dropped — `revenue / revenue offset 1 month` becoming exactly 1.0.
        if ref.get("offset_window") or ref.get("offset_to_grain"):
            return None, None, (f"{role} '{ref['name']}' carries an offset — "
                                "no faithful compilation")
        base = idx.metrics.get(ref["name"])
        if not base:
            return None, None, f"{role} metric '{ref['name']}' not found"
        if (base.get("type") or "").lower() != "simple":
            return None, None, f"{role} '{ref['name']}' is not a simple metric"
        sql, meta, err = _grouped_metric_sql(
            idx, base, alias, grain=grain, dims=dims,
            extra_filters=(ref.get("filter"), *extra_filters), timespine=False,
        )
        if err:
            return None, None, f"{role}: {err}"
        legs[role] = (sql or "", meta or {})
    g = legs["denominator"][1].get("grain")
    if legs["numerator"][1].get("grain") != g:
        return None, None, "numerator and denominator compile at different grains"
    keys = ["metric_time"] + [alias for alias, _, _ in dims]
    on = " AND ".join(f"num.{k} IS NOT DISTINCT FROM den.{k}" for k in keys)
    select = [f"den.{k} AS {k}" for k in keys]
    select.append(
        f"CAST(COALESCE(num.num, 0) AS DOUBLE) / NULLIF(CAST(den.den AS DOUBLE), 0) AS {name}"
    )
    sql = (
        f"WITH num AS (\n{_indent(legs['numerator'][0])}\n),\n"
        f"den AS (\n{_indent(legs['denominator'][0])}\n)\n"
        "SELECT " + ",\n       ".join(select) + "\n"
        f"FROM den LEFT JOIN num ON {on}"
    )
    return sql, {"grain": g}, None


def _derived_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any],
                        name: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """Derived metric: one CTE per input (offset inputs shift their metric_time
    forward by the offset, so an equality join lines the periods up), then the
    formula verbatim over the joined value columns."""
    tp = metric.get("type_params") or {}
    expr = tp.get("expr")
    inputs = tp.get("metrics") or []
    if not expr or not inputs:
        return None, None, "derived metric without expr or input metrics"
    # An offset leg only lines up on an equality join when the series grain equals
    # the offset granularity: month-truncated times shifted by 7 days match nothing,
    # so the leg would be NULL on every row while the view validates clean. Mixed
    # offset granularities therefore have no faithful single-grain compilation, and
    # `offset_to_grain` has no compilation here at all — both skip, counted, rather
    # than shipping a view that quietly computes a different metric.
    offset_grains = set()
    for i in inputs:
        if i.get("offset_to_grain"):
            return None, None, (f"input '{i.get('alias') or i.get('name')}' uses "
                                "offset_to_grain — no faithful compilation")
        og = (i.get("offset_window") or {}).get("granularity")
        if og:
            if og not in _GRAIN_ORDER:
                return None, None, f"unknown offset granularity '{og}'"
            offset_grains.add(og)
    if len(offset_grains) > 1:
        return None, None, (
            "offset windows at different granularities ("
            + ", ".join(sorted(offset_grains))
            + ") cannot align on one series grain — no faithful compilation")
    grain: Optional[str] = next(iter(offset_grains), None)
    ctes: List[Tuple[str, str]] = []
    base_alias: Optional[str] = None
    for i in inputs:
        base = idx.metrics.get(i.get("name") or "")
        if not base:
            return None, None, f"input metric '{i.get('name')}' not found"
        if (base.get("type") or "").lower() != "simple":
            return None, None, f"input '{i.get('name')}' is not a simple metric"
        alias = i.get("alias") or i.get("name") or ""
        sql, meta, err = _grouped_metric_sql(
            idx, base, alias, grain=grain,
            extra_filters=(i.get("filter"),), timespine=False,
        )
        if err:
            return None, None, f"input {alias}: {err}"
        if grain is None:
            grain = (meta or {}).get("grain")
        ow = i.get("offset_window") or {}
        if ow.get("count") and ow.get("granularity"):
            sql = (
                f"SELECT metric_time + INTERVAL '{int(ow['count'])} {ow['granularity']}'"
                f" AS metric_time, {alias}\n"
                f"FROM (\n{_indent(sql or '')}\n) t"
            )
        elif base_alias is None:
            base_alias = alias
        ctes.append((alias, sql or ""))
    base_alias = base_alias or ctes[0][0]
    with_sql = ",\n".join(f"{a} AS (\n{_indent(s)}\n)" for a, s in ctes)
    frm = base_alias
    for a, _ in ctes:
        if a != base_alias:
            frm += f"\n  LEFT JOIN {a} ON {a}.metric_time = {base_alias}.metric_time"
    sql = (
        f"WITH {with_sql}\n"
        f"SELECT {base_alias}.metric_time,\n"
        f"       ({expr}) AS {name}\n"
        f"FROM {frm}"
    )
    return sql, {"grain": grain or "day"}, None


def _cumulative_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any],
                           name: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """Cumulative metric: daily series x time spine, windowed by a join condition.

    A join range, not a window frame: `RANGE INTERVAL` frames are the one piece of this
    SQL whose planner support varies, and the join form means the statement only needs
    joins, aggregates, and interval arithmetic — which both the planner and every
    target dialect here handle.
    """
    tp = metric.get("type_params") or {}
    ctp = tp.get("cumulative_type_params") or {}
    window, g2d = ctp.get("window"), ctp.get("grain_to_date")
    if not idx.spine:
        return None, None, ("no time spine — declare time_spine.standard_granularity_column "
                            "on a model")
    if bool(window) == bool(g2d):
        return None, None, "cumulative needs exactly one of window / grain_to_date"
    # The window is applied by re-aggregating daily values with SUM, which is only
    # correct for aggs that are additive across days. A daily COUNT(DISTINCT) summed
    # over 28 days counts a customer once per active day; daily AVG/MIN/MAX summed is
    # not any statistic at all. Those need the distinct/avg computed over the joined
    # window itself — no faithful compilation here, so: skipped and counted.
    mref = tp.get("measure") or {}
    m_sm = idx.measure_sm.get(mref.get("name") or "")
    measure = next((m for m in (idx.sms.get(m_sm) or {}).get("measures") or []
                    if m.get("name") == mref.get("name")), {})
    agg = (measure.get("agg") or "").lower()
    if agg not in ("sum", "count"):
        return None, None, (f"cumulative over agg '{agg}' cannot be re-aggregated "
                            "by summing daily values — no faithful compilation")
    inner = {"type_params": {"measure": tp.get("measure")}, "filter": metric.get("filter")}
    sql, _, err = _grouped_metric_sql(idx, inner, "v", grain="day", timespine=False)
    if err:
        return None, None, err
    spine_model, spine_col = idx.spine
    if window:
        cond = (
            f"daily.metric_time > spine.metric_time"
            f" - INTERVAL '{int(window['count'])} {window['granularity']}'\n"
            f"  AND daily.metric_time <= spine.metric_time"
        )
    else:
        cond = (
            f"daily.metric_time >= date_trunc('{g2d}', spine.metric_time)\n"
            f"  AND daily.metric_time <= spine.metric_time"
        )
    out = (
        f"WITH daily AS (\n{_indent(sql or '')}\n),\n"
        f"spine AS (\n"
        f"  SELECT DISTINCT CAST({spine_col} AS TIMESTAMP) AS metric_time\n"
        f"  FROM {spine_model}\n"
        f")\n"
        f"SELECT spine.metric_time, SUM(daily.v) AS {name}\n"
        f"FROM spine LEFT JOIN daily\n"
        f"  ON {cond}\n"
        f"WHERE spine.metric_time BETWEEN (SELECT MIN(metric_time) FROM daily)\n"
        f"                            AND (SELECT MAX(metric_time) FROM daily)\n"
        f"GROUP BY 1"
    )
    return out, {"grain": "day"}, None


def _saved_query_view(idx: _SemanticIndex, sq: Dict[str, Any],
                      name: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """A saved query is the dimensional cut the analyst already declared in dbt —
    compile it instead of inventing per-dashboard SQL. One CTE per metric at the
    query's grain and dimensions, joined on the full group key (null-safe, since a
    dimension value can legitimately be NULL)."""
    qp = sq.get("query_params") or {}
    grain: Optional[str] = None
    dims: List[Tuple[str, str, str]] = []
    for gb in qp.get("group_by") or []:
        m = _SQ_TIME.match(gb.strip())
        if m:
            grain = m.group(1)
            continue
        m = _SQ_DIM.match(gb.strip())
        if m:
            dims.append((m.group(2), m.group(1), m.group(2)))
            continue
        return None, None, f"unsupported group_by '{gb}'"
    where = qp.get("where")
    dtuple = tuple(dims)
    ctes: List[Tuple[str, str]] = []
    for mname in qp.get("metrics") or []:
        metric = idx.metrics.get(mname)
        if not metric:
            return None, None, f"metric '{mname}' not found"
        mtype = (metric.get("type") or "").lower()
        if mtype == "simple":
            sql, _, err = _grouped_metric_sql(
                idx, metric, mname, grain=grain, dims=dtuple,
                extra_filters=(where,), timespine=False,
            )
        elif mtype == "ratio":
            sql, _, err = _ratio_metric_sql(
                idx, metric, mname, grain=grain, dims=dtuple, extra_filters=(where,),
            )
        else:
            return None, None, (f"metric '{mname}' is {mtype} — only simple and ratio "
                                "compile into a saved-query view")
        if err:
            return None, None, f"{mname}: {err}"
        ctes.append((mname, sql or ""))
    if not ctes:
        return None, None, "saved query names no metrics"
    keys = ["metric_time"] + [alias for alias, _, _ in dims]
    base = ctes[0][0]
    frm = base
    for a, _ in ctes[1:]:
        on = " AND ".join(f"{a}.{k} IS NOT DISTINCT FROM {base}.{k}" for k in keys)
        frm += f"\n  LEFT JOIN {a} ON {on}"
    select = [f"{base}.{k} AS {k}" for k in keys]
    select += [f"{a}.{a} AS {a}" for a, _ in ctes]
    with_sql = ",\n".join(f"{a} AS (\n{_indent(s)}\n)" for a, s in ctes)
    sql = (
        f"WITH {with_sql}\n"
        "SELECT " + ",\n       ".join(select) + "\n"
        f"FROM {frm}"
    )
    return sql, {"grain": grain or "day"}, None


def build_metric_views(man: Manifest, catalog: Dict[str, Any],
                       slug: str) -> Tuple[Dict[str, str], List[str]]:
    """One MDL view per MetricFlow metric and saved query.

    The view *is* the metric: same name, full definition (filter, ratio, offset,
    window) compiled to SQL the engine plans and `wren context validate` dry-plans
    with no warehouse. A metric whose type or parameters have no faithful
    compilation is skipped and counted — never approximated (rule 5).
    """
    idx = _SemanticIndex(man, catalog)
    model_names = {_model_name(man, uid) for uid in man.models()}
    views: Dict[str, str] = {}
    skipped: List[str] = []

    def emit(name: str, kind: str,
             result: Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]],
             description: str) -> None:
        sql, meta, err = result
        if err:
            skipped.append(f"{name}: {err}")
            return
        if name in model_names:
            skipped.append(f"{name}: collides with a model name — rename the metric")
            return
        if name in views:
            skipped.append(f"{name}: duplicate view name")
            return
        props: List[Tuple[str, str]] = [
            ("metric_type", kind), ("grain", str((meta or {}).get("grain") or "day")),
        ]
        views[name] = view_yaml(name, sql or "", description, props)

    for name in sorted(idx.metrics):
        metric = idx.metrics[name]
        mtype = (metric.get("type") or "").lower()
        desc = " ".join((metric.get("description") or "").split()) or (
            f"dbt metric '{name}' ({mtype})."
        )
        if mtype == "simple":
            emit(name, "simple", _grouped_metric_sql(idx, metric, name), desc)
        elif mtype == "ratio":
            emit(name, "ratio", _ratio_metric_sql(idx, metric, name), desc)
        elif mtype == "derived":
            emit(name, "derived", _derived_metric_sql(idx, metric, name), desc)
        elif mtype == "cumulative":
            emit(name, "cumulative", _cumulative_metric_sql(idx, metric, name), desc)
        else:
            skipped.append(f"{name}: metric type '{mtype}' has no faithful view compilation")
    for key in sorted(man.saved_queries):
        sq = man.saved_queries[key]
        name = sq.get("name") or key.rsplit(".", 1)[-1]
        desc = " ".join((sq.get("description") or "").split()) or (
            f"dbt saved query '{name}'."
        )
        emit(name, "saved_query", _saved_query_view(idx, sq, name), desc)
    return views, skipped


# ---------------------------------------------------------------------------------------
# Generation and diffing
# ---------------------------------------------------------------------------------------


def _restore_or_discard(backup: Path, target: Path) -> None:
    """Heal a backup stranded by a hard kill — without destroying newer work.

    A finally clause does not run on SIGKILL, so a sanitized copy (or nothing, or a
    truncated write) can be at the target with the original stranded at the backup
    name. Blindly restoring the backup was measured to destroy a manifest the user
    re-parsed *after* the crash — the sync then regenerated from pre-crash models
    while reporting success. So: restore only when the target is the sanitized copy
    of the SAME dbt invocation (equal `metadata.generated_at`), or is missing or
    unreadable; a target from a different invocation is newer work, and the stale
    backup is discarded instead.
    """
    if not backup.exists():
        return
    if not target.exists():
        backup.replace(target)
        return
    try:
        current = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        # The kill landed mid-write; the backup is the only intact artifact.
        backup.replace(target)
        return
    try:
        original = json.loads(backup.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        backup.unlink(missing_ok=True)
        return
    same_generation = (
        (current.get("metadata") or {}).get("generated_at")
        == (original.get("metadata") or {}).get("generated_at")
    )
    if same_generation:
        backup.replace(target)
    else:
        backup.unlink()


def _heal_stranded_backups(dbt_project: Path, manifest_path: Path) -> None:
    """Run both sanitizers' heals before anything reads the artifacts.

    Ordering is the point: `generate()` loads the manifest before either context
    manager is entered, so healing only inside the CMs meant a post-crash run
    computed alias renames from the already-sanitized file (finding none), healed
    the colliding original back, and handed it to the importer — the exact crash
    the sanitizer exists to prevent. And a truncated manifest died in the loader
    before any CM could heal it.
    """
    rr = dbt_project / "target" / "run_results.json"
    _restore_or_discard(rr.with_suffix(".json.wren-sync-orig"), rr)
    _restore_or_discard(
        manifest_path.with_suffix(".json.wren-sync-alias-orig"), manifest_path
    )


@contextlib.contextmanager
def _model_level_tests_hidden(dbt_project: Path, man: Manifest) -> Iterator[None]:
    """Hide model-level test rows from run_results.json for the duration of the import.

    wrenai 0.13.2's importer sorts its test events by `(model, column)` and a dbt test
    with no column — a singular test, a model-level dbt_utils test — carries
    `column_name: None`, so the sort compares None to str and the whole import dies
    (wren/dbt.py:1201; fix staged at external/patches/). Dropping run_results.json
    entirely would also dodge it, but it takes the `dbt_test_status: verified` column
    enrichment with it. So only the rows the importer cannot sort are filtered, the
    original file is set aside under a distinct name, and it is restored no matter how
    the import exits.
    """
    rr = dbt_project / "target" / "run_results.json"
    backup = rr.with_suffix(".json.wren-sync-orig")
    # A finally clause does not run on SIGKILL. If a previous run was killed inside the
    # window, heal first, before reading — and only in a way that cannot clobber an
    # artifact regenerated after the crash (_restore_or_discard).
    _restore_or_discard(backup, rr)
    if not rr.exists():
        yield
        return
    columnless = {
        uid for uid, node in man.tests().items() if node.get("column_name") is None
    }
    data = load_json(str(rr), "run_results")
    kept = [r for r in data.get("results", []) if r.get("unique_id") not in columnless]
    if len(kept) == len(data.get("results", [])):
        yield
        return
    rr.rename(backup)
    try:
        rr.write_text(json.dumps({**data, "results": kept}), encoding="utf-8")
        yield
    finally:
        rr.unlink(missing_ok=True)
        backup.rename(rr)


@contextlib.contextmanager
def _colliding_aliases_disambiguated(manifest_path: Path, man: Manifest) -> Iterator[None]:
    """Make colliding dbt aliases importable, without touching what they bind to.

    A multi-connector project aliases one conformed name per connector —
    `fortnox_bi_dim_accounts` and `tripletex_bi_dim_accounts` are both `dim_accounts`,
    in different schemas. dbt is fine with that (relations are schema-qualified); the
    importer names Wren models `alias or name` and dies on the first duplicate —
    measured on enhanza-analytics: 21 colliding aliases across 359 models (fix staged
    at external/patches/).

    The importer computes the Wren model *name* and the physical *table* independently,
    and `identifier` outranks `alias` in its table chain. So for colliding models only,
    the manifest is rewritten for the import's duration: `alias` becomes the node's
    name (unique in any dbt project) and `identifier` pins the original alias, which
    keeps `table_reference` byte-identical to what dbt built. Same set-aside/restore
    discipline as `_model_level_tests_hidden`, including healing a stranded backup.
    """
    backup = manifest_path.with_suffix(".json.wren-sync-alias-orig")
    _restore_or_discard(backup, manifest_path)
    models = {uid: n for uid, n in man.models().items()
              if str((n.get("config") or {}).get("materialized", "")).lower() != "ephemeral"}
    renames = _unique_wren_names(models)
    if not renames:
        yield
        return
    data = load_json(str(manifest_path), "manifest")
    for uid, new_name in renames.items():
        node = data.get("nodes", {}).get(uid)
        if node is None:
            continue
        original = node.get("alias") or node.get("name") or ""
        node["identifier"] = node.get("identifier") or original
        node["alias"] = new_name
    manifest_path.rename(backup)
    try:
        manifest_path.write_text(json.dumps(data), encoding="utf-8")
        yield
    finally:
        manifest_path.unlink(missing_ok=True)
        backup.rename(manifest_path)


def _unique_wren_names(models: Dict[str, Dict[str, Any]]) -> Dict[str, str]:
    """uid -> replacement alias, for exactly the nodes whose importer name collides.

    Uniqueness is decided over the FINAL name set, not per collision class: renaming a
    colliding alias to its node name can itself collide with another node's alias
    (measured: `shopify_bi_dim_articles` is one model's *name* and another's *alias*).
    Escalation per node is deterministic — alias -> name -> package_name -> unique_id —
    and every step keeps nodes the importer would accept unchanged.
    """
    initial = {
        uid: (n.get("alias") or n.get("name") or "") for uid, n in models.items()
    }
    counts: Dict[str, int] = {}
    for name in initial.values():
        counts[name] = counts.get(name, 0) + 1

    taken: set = set()
    final: Dict[str, str] = {}
    for uid in sorted(models):
        n = models[uid]
        node_name = n.get("name") or ""
        for cand in (
            initial[uid],
            node_name,
            f"{n.get('package_name')}_{node_name}",
            uid.replace(".", "_"),
        ):
            if not cand or cand in taken:
                continue
            # A contested initial name belongs to the node it is the dbt *name* of
            # (names are unique per project, so at most one such node); every
            # alias-holder escalates instead of racing for it.
            if cand == initial[uid] and counts[cand] > 1 and cand != node_name:
                continue
            taken.add(cand)
            final[uid] = cand
            break
    return {uid: name for uid, name in final.items() if name != initial[uid]}


def generate(cli: str, use_case: Path, slug: str, manifest_path: Path,
             catalog_path: Path, scratch: Path) -> Dict[str, Any]:
    """Run importer + enrichment into `scratch`; return generation stats."""
    if scratch.exists():
        shutil.rmtree(scratch)
    scratch.mkdir(parents=True)

    dbt_project = use_case / "dbt_project"
    # Heal any hard-kill leftovers BEFORE the manifest is read: renames must be
    # computed from the true original, and a truncated file must be recovered
    # rather than dying in the loader with a pristine backup sitting beside it.
    _heal_stranded_backups(dbt_project, manifest_path)
    man = Manifest.load(str(manifest_path))
    init = run_wren(cli, ["context", "init", "--empty", "--path", str(scratch)])
    if init.returncode != 0:
        die(f"wren context init failed: {_tail(init)}")
    with _model_level_tests_hidden(dbt_project, man), \
            _colliding_aliases_disambiguated(manifest_path, man):
        imp = run_wren(cli, [
            "context", "import", "dbt",
            "--project-dir", str(dbt_project),
            "--profiles-path", str(dbt_project / "profiles.yml"),
            "--path", str(scratch), "--force",
        ])
    if imp.returncode != 0:
        die(f"wren context import dbt failed: {_tail(imp)}")
    # The importer drops any model it has no column information for (neither catalog
    # nor schema.yml). Locally that can be most of a project — enhanza's sample DuckDB
    # catalogs 4 of 359 relations — and a summary that says "176 models" without saying
    # what it left out is the silently-partial trap this repo documents twice already.
    m = re.search(r"skipped (\d+) node\(s\) without catalog columns",
                  imp.stdout + imp.stderr)
    models_without_columns = int(m.group(1)) if m else 0

    catalog = load_json(str(catalog_path), "catalog")

    knowledge_written = 0
    for rel, content in (
        ("knowledge/rules/ontology-concepts.md",
         concepts_markdown(_optional_json(use_case / "ontology/index.json"), slug)),
        ("knowledge/rules/column-contracts.md",
         contracts_markdown(_optional_json(use_case / "ontology/column-memory.json"), slug)),
        ("knowledge/caveats/adapter-drift.md",
         drift_markdown(_optional_json(use_case / "ontology/column-memory.json"), slug)),
        ("knowledge/rules/semantic-metrics.md", metrics_markdown(man, slug)),
    ):
        if content is None:
            continue
        target = scratch / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        knowledge_written += 1

    views, views_skipped = build_metric_views(man, catalog, slug)
    for name, content in sorted(views.items()):
        target = scratch / "views" / name / "metadata.yml"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    (scratch / ".gitignore").write_text(
        "target/\n.wren/\n.wren-home/\nmcp.json\n", encoding="utf-8"
    )

    validate = run_wren(cli, ["context", "validate", "--path", str(scratch)])
    if validate.returncode != 0:
        die(f"wren context validate failed: {_tail(validate)}")
    # The CLI prints an aggregate ("Warnings: 120 total" / "120 warning(s)"); counting
    # lines that start with "warning" reported that as 1.
    wm = re.search(r"(\d+)\s+(?:warning\(s\)|total)", validate.stdout)
    warnings = int(wm.group(1)) if wm else sum(
        1 for ln in validate.stdout.splitlines() if ln.strip().lower().startswith("warning")
    )
    build = run_wren(cli, ["context", "build", "--path", str(scratch)])
    if build.returncode != 0:
        die(f"wren context build failed: {_tail(build)}")
    # Build output validated, then discarded: target/ is derived state and stays out of
    # the committed tree — a fresh clone rebuilds it with one command.
    shutil.rmtree(scratch / "target", ignore_errors=True)

    models = sum(1 for _ in scratch.glob("models/*/metadata.yml"))
    relationships = 0
    rel_file = scratch / "relationships.yml"
    if rel_file.exists():
        relationships = sum(
            1 for ln in rel_file.read_text(encoding="utf-8").splitlines()
            if ln.startswith("- name:")
        )
    return {
        "models": models,
        "models_without_columns": models_without_columns,
        "relationships": relationships,
        "views": len(views),
        "views_skipped": sorted(views_skipped),
        "knowledge_files": knowledge_written,
        "validate_warnings": warnings,
    }


def _optional_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    return load_json(str(path), path.name)


def _tree(root: Path) -> Dict[str, bytes]:
    files: Dict[str, bytes] = {}
    if not root.exists():
        return files
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if rel.parts and rel.parts[0] in UNTOUCHED_DIRS:
            continue
        if str(rel) in UNTOUCHED_FILES:
            continue
        files[str(rel)] = p.read_bytes()
    return files


# Paths the generation pipeline owns wholesale — a stale file here is an orphan of a
# renamed or deleted dbt node, not somebody's hand work. `cubes/` stays listed although
# nothing generates cubes any more: committed trees still carry them from before metrics
# compiled to views, and the prefix is what lets the first regeneration delete them as
# the orphans they now are. `views/` is deliberately NOT here — generated views are
# owned by their `source: dbt_metric` marker, so a hand-authored view in the same
# directory is reported `stale` and never touched.
_OWNED_PREFIXES = ("models/", "cubes/")
_OWNED_FILES = {"wren_project.yml", "relationships.yml", "AGENTS.md", ".gitignore"}


def _generation_owned(rel: str, blob: bytes) -> bool:
    if rel in _OWNED_FILES or rel.startswith(_OWNED_PREFIXES):
        return True
    # Knowledge files are shared ground: the importer's and this script's carry markers;
    # anything else there is hand-authored context (including `wren memory store` pairs).
    text = blob.decode("utf-8", errors="replace")
    return (
        "Generated by scripts/wren_context_sync.py" in text
        or "source: dbt" in text  # importer-seeded NL->SQL pairs and rules
    )


def diff_and_sync(scratch: Path, target: Path,
                  check: bool) -> Tuple[List[str], List[str], List[str]]:
    """Returns (changed, deleted, kept_stale).

    `deleted` is generation-owned orphans — a cube whose semantic model was removed, a
    model dir for a renamed dbt node. Leaving them would ship a committed tree that
    references dropped tables while `--check` stays green, so they count as changes and
    are removed on sync. `kept_stale` is everything else: hand-authored files, reported
    and never touched.
    """
    generated, committed = _tree(scratch), _tree(target)
    changed = sorted(
        rel for rel, blob in generated.items() if committed.get(rel) != blob
    )
    stale = sorted(set(committed) - set(generated))
    deleted = [rel for rel in stale if _generation_owned(rel, committed[rel])]
    kept_stale = [rel for rel in stale if rel not in set(deleted)]
    if not check:
        for rel in changed:
            dest = target / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(generated[rel])
        for rel in deleted:
            (target / rel).unlink(missing_ok=True)
    return changed, deleted, kept_stale


def _project_data_source(wren_dir: Path) -> str:
    """`data_source:` from wren_project.yml — importer-generated flat YAML, so a line
    scan is the whole parser (same reasoning as the sources.yml insert-only rule:
    never round-trip a file another tool owns)."""
    project = wren_dir / "wren_project.yml"
    if not project.exists():
        return ""
    for ln in project.read_text(encoding="utf-8").splitlines():
        if ln.startswith("data_source:"):
            return ln.split(":", 1)[1].strip()
    return ""


def write_mcp_config(cli: str, use_case: Path, slug: str) -> Tuple[Optional[str], Optional[str]]:
    """Write wren/mcp.json + wren/.wren-home — the ready-to-register MCP server.

    Returns (relative_path, skip_reason); exactly one is set.

    `wren serve mcp` is upstream's own MCP server (in-process engine, no HTTP tier);
    this pins it to the use-case's project. Connection handling is the decision:

    - **duckdb**: the connection is a path to the local dbt project — zero credentials,
      fully derivable — so the sync writes it into a repo-local WREN_HOME
      (`wren/.wren-home/connection_info.json`, upstream's own env channel) and the
      server comes up live: `run_sql` over the metric views works out of the box.
    - **anything else**: the connection is credentials, and a sync flow must not
      conjure or copy credentials (wren rule 9's instinct). Skipped, with the
      `wren profile add` remedy named — never a config that half-works.

    Absolute paths make these files correct for this clone and wrong for every other,
    which is why both are gitignored and rewritten on each sync, like target/.
    """
    wren_dir = use_case / "wren"
    if not wren_dir.is_dir():
        return None, "no wren/ project yet"
    ds = _project_data_source(wren_dir)
    if ds != "duckdb":
        # A previously emitted config would keep serving the OLD duckdb warehouse
        # after the project migrated — an already-registered server answering from a
        # frozen local build with no error. "Never a config that half-works" means
        # removing it, not just declining to rewrite it.
        (wren_dir / "mcp.json").unlink(missing_ok=True)
        shutil.rmtree(wren_dir / ".wren-home", ignore_errors=True)
        return None, (
            f"data_source '{ds or '?'}' needs credentials — wren profile add "
            f"<name>, then: claude mcp add wren-{slug} -- {cli} serve mcp "
            f"--project {wren_dir.resolve()} --profile <name>"
        )
    home = wren_dir / ".wren-home"
    home.mkdir(exist_ok=True)
    (home / "connection_info.json").write_text(
        json.dumps({
            "datasource": "duckdb",
            "url": str((use_case / "dbt_project").resolve()),
            "format": "duckdb",
        }) + "\n",
        encoding="utf-8",
    )
    server = {
        "command": str(Path(cli).resolve()),
        "args": ["serve", "mcp", "--project", str(wren_dir.resolve())],
        "env": {"WREN_HOME": str(home.resolve())},
    }
    path = wren_dir / "mcp.json"
    path.write_text(
        json.dumps({"mcpServers": {f"wren-{slug}": server}}, indent=2) + "\n",
        encoding="utf-8",
    )
    try:
        return str(path.relative_to(REPO)), None
    except ValueError:  # use-case outside the repo root (tests, embedding repos)
        return str(path), None


# ---------------------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------------------


def sync(slug: str, manifest_arg: Optional[str], check: bool) -> Dict[str, Any]:
    use_case = use_case_dir(slug)
    if not use_case:
        die(f"no such use-case under skill-packs/*/use-cases/: {slug}")

    payload: Dict[str, Any] = {"use_case": slug, "status": "skip"}

    if not (use_case / "dbt_project").exists():
        payload["reason"] = "no dbt_project yet"
        return payload
    default_manifest = use_case / "dbt_project/target/manifest.json"
    manifest_path = Path(manifest_arg) if manifest_arg else default_manifest
    # The wrenai importer always reads <dbt_project>/target/ itself; honoring a foreign
    # --manifest here would sanitize and enrich from one manifest while the importer
    # reads another — two internally consistent halves of different generations.
    if manifest_arg and manifest_path.resolve() != default_manifest.resolve():
        payload["reason"] = (
            "--manifest points outside dbt_project/target/ — the wren importer reads "
            "the project's own target; re-run dbt parse there instead"
        )
        return payload
    # Heal before the existence check: a kill between the sanitizer's rename and its
    # write leaves the manifest missing with the intact original at the backup name —
    # that state must recover here, not demand a re-parse.
    _heal_stranded_backups(use_case / "dbt_project", manifest_path)
    if not manifest_path.exists():
        payload["reason"] = "no manifest — dbt parse (or artifacts/refresh.sh)"
        return payload
    catalog_path = manifest_path.parent / "catalog.json"
    if not catalog_path.exists():
        payload["reason"] = "no catalog.json — dbt docs generate against the local target"
        return payload
    cli = find_wren_cli()
    if not cli:
        payload["reason"] = "wren CLI not installed — pip install -r requirements.txt"
        return payload

    scratch = use_case / ".wren.tmp"
    try:
        stats = generate(cli, use_case, slug, manifest_path, catalog_path, scratch)
        changed, deleted, stale = diff_and_sync(scratch, use_case / "wren", check)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    payload.update(stats)
    payload["status"] = "changed" if (changed or deleted) else "ok"
    payload["changed"] = changed
    payload["deleted"] = deleted
    payload["stale"] = stale
    if check:
        payload["mcp"] = None
    else:
        payload["mcp"], mcp_skip = write_mcp_config(cli, use_case, slug)
        if mcp_skip:
            payload["mcp_skipped"] = mcp_skip
    return payload


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate the WrenAI semantic-layer project for a use-case: "
                    "native dbt import plus ontology/contract/metric enrichment.",
    )
    p.add_argument("--use-case", required=True, help="slug under skill-packs/*/use-cases/")
    p.add_argument("--manifest", help="manifest.json (default: <project>/target/manifest.json)")
    p.add_argument("--check", action="store_true",
                   help="write nothing; report what would change")
    p.add_argument("--format", choices=("text", "json"), default="text")
    args = p.parse_args(argv)

    payload = sync(args.use_case, args.manifest, args.check)

    if args.format == "json":
        print(json.dumps(payload, ensure_ascii=False))
    else:
        status = payload["status"]
        if status == "skip":
            print(f"skip  {payload['use_case']}: {payload['reason']}")
        else:
            without = payload.get("models_without_columns", 0)
            coverage = f" ({without} dropped: no column info)" if without else ""
            print(
                f"{status:<5} {payload['use_case']}: {payload.get('models', 0)} models"
                f"{coverage}, "
                f"{payload.get('relationships', 0)} relationships, "
                f"{payload.get('views', 0)} metric views, "
                f"{payload.get('knowledge_files', 0)} knowledge files, "
                f"{payload.get('validate_warnings', 0)} validate warning(s)"
            )
            for rel in payload.get("changed", []):
                print(f"  changed  wren/{rel}")
            for rel in payload.get("deleted", []):
                print(f"  deleted  wren/{rel} (generation-owned orphan)")
            for rel in payload.get("stale", []):
                print(f"  stale    wren/{rel} (hand-authored; left alone)")
            skipped = payload.get("views_skipped", [])
            if skipped:
                print(f"  {len(skipped)} metric(s) skipped rather than approximated:")
                for reason in skipped[:10]:
                    print(f"    - {reason}")
            if payload.get("mcp"):
                cfg = json.loads((REPO / payload["mcp"]).read_text(encoding="utf-8"))
                (server_name, server), = cfg["mcpServers"].items()
                env = "".join(f"-e {k}={v} " for k, v in (server.get("env") or {}).items())
                print(f"  mcp      {payload['mcp']} — register with:")
                print(f"           claude mcp add {server_name} {env}-- "
                      f"{server['command']} {' '.join(server['args'])}")
            elif payload.get("mcp_skipped"):
                print(f"  mcp      skipped: {payload['mcp_skipped']}")

    if payload["status"] == "changed" and args.check:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
