#!/usr/bin/env python3
"""Project a use-case into a WrenAI semantic-layer project — import, then enrich.

WrenAI (pinned as a submodule at external/WrenAI, installed as the `wrenai` wheel) already
ships a native dbt importer: `wren context import dbt` turns a dbt project's manifest.json +
catalog.json into a Wren MDL project — models, columns, relationships from `relationships`
tests, knowledge scaffolding. This script does **not** reimplement any of that. It runs the
native importer and then writes the one thing the importer cannot know: the business context
this repository already derives.

    importer (upstream, mechanical)          enrichment (this repo's artifacts)
    ---------------------------------        -------------------------------------------
    models/<name>/metadata.yml               knowledge/rules/ontology-concepts.md
    relationships.yml (dbt tests)              <- ontology/index.json
    knowledge/rules/general.md               knowledge/rules/column-contracts.md
    knowledge/sql/*.md seed pairs              <- ontology/column-memory.json
    wren_project.yml, AGENTS.md              knowledge/caveats/adapter-drift.md
                                               <- column-memory drift findings
                                             knowledge/rules/semantic-metrics.md
                                               <- manifest metrics (MetricFlow)
                                             views/<name>/metadata.yml
                                               <- manifest metrics + saved queries,
                                                  typed from catalog.json

Metrics compile to MDL *views*, not cubes. A cube measure is `AGG(column)` with the
metric's filter, ratio, offset, and window silently dropped — measured on
example-order-revenue-mart, the cube's `order_total` and the metric `revenue` disagreed
by 4.4% while both looked authoritative. A view carries the whole definition as SQL, so
`SELECT * FROM revenue` through the engine *is* the metric, for BI and agents alike.
MetricFlow stays the source of truth (analytics rule 42); the view is a projection with
a generated marker, regenerated whole (wren rule 4).

Ownership is disjoint on purpose: re-running the importer with `--force` regenerates its
files and only its files, and this script's files carry a generated-by header naming the
regeneration command. Hand-authored knowledge belongs in *other* filenames — both layers
leave unknown files alone (they are reported as `stale`, never deleted).

Generation happens in a scratch directory beside the target and is diffed file-by-file, for
the same reason the other emitters do it: `--check` must write nothing, a re-run must change
nothing, and the changed-file list is the report. Nothing run-dependent goes into the tree.

Types are read from catalog.json — the warehouse's own answer — never guessed (rule 5).
A metric whose type or parameters have no faithful SQL compilation is skipped and counted
in the payload rather than approximated. Casts in the generated SQL come from the catalog
too: wren-core registers a parameterized DECIMAL model column as Utf8 when planning a
view's statement (fix staged at external/patches/), so every bare decimal measure column
is CAST to its own catalog type — a no-op at execution, correct at planning.

Inputs that are missing produce a `skip` with the way out, not a failure: no dbt_project, no
manifest (`dbt parse`), no catalog.json (`dbt docs generate`), no `wren` CLI
(pip install -r requirements.txt). The CLI is resolved from $WREN_CLI, then PATH, then the
repository's .venv-wren/.

Usage:
    python3 scripts/wren_context_sync.py --use-case example-order-revenue-mart
    python3 scripts/wren_context_sync.py --use-case <slug> --check --format json
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _manifest import Manifest, die, load_json  # noqa: E402

REPO = Path(__file__).resolve().parent.parent

GENERATED_HEADER = (
    "<!-- Generated by scripts/wren_context_sync.py — do not hand-edit. "
    "Regenerate: python3 scripts/use_case_sync.py --use-case {slug} --stage wren -->"
)

# Files the upstream importer owns and regenerates under --force. Everything else in the
# project tree that we did not generate is someone's hand-authored context: report, never
# touch. `apps/` is agent-authored GenBI output; `.wren/` and `target/` are derived state.
UNTOUCHED_DIRS = {"apps", ".wren", "target"}

# MetricFlow aggregation -> SQL projection. Anything not listed has no faithful
# single-expression projection (percentile, median, sum_boolean) and is skipped,
# counted, and reported.
AGG_SQL = {
    "sum": "SUM({x})",
    "avg": "AVG({x})",
    "average": "AVG({x})",
    "count": "COUNT({x})",
    "count_distinct": "COUNT(DISTINCT {x})",
    "min": "MIN({x})",
    "max": "MAX({x})",
}

# Grain ordering for derived metrics: the view's grain is the coarsest offset any
# input carries, because a 1-month offset only aligns on a monthly series.
_GRAIN_ORDER = ("day", "week", "month", "quarter", "year")

_BARE_COLUMN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")

# MetricFlow filter templates reference dimensions as {{ Dimension('entity__name') }}.
_DIM_REF = re.compile(r"\{\{\s*Dimension\(\s*'([A-Za-z0-9_]+)__([A-Za-z0-9_]+)'\s*\)\s*\}\}")

# Saved-query group_by entries are the same call forms, as bare strings.
_SQ_TIME = re.compile(r"TimeDimension\(\s*'metric_time'\s*,\s*'([a-z]+)'\s*\)\Z")
_SQ_DIM = re.compile(r"Dimension\(\s*'([A-Za-z0-9_]+)__([A-Za-z0-9_]+)'\s*\)\Z")


def use_case_dir(slug: str) -> Optional[Path]:
    matches = [p for p in REPO.glob(f"skill-packs/*/use-cases/{slug}") if p.is_dir()]
    return matches[0] if matches else None


def find_wren_cli() -> Optional[str]:
    env = os.environ.get("WREN_CLI")
    if env and Path(env).exists():
        return env
    on_path = shutil.which("wren")
    if on_path:
        return on_path
    local = REPO / ".venv-wren" / "bin" / "wren"
    return str(local) if local.exists() else None


def run_wren(cli: str, args: List[str]) -> subprocess.CompletedProcess:
    # Per-call budget deliberately below stage_wren's whole-script timeout in
    # use_case_sync.py (1800s): four wren calls at 300s each leave headroom, so the outer
    # timeout can never SIGKILL this process while the run_results sanitizer is open.
    return subprocess.run(
        [cli, *args], capture_output=True, text=True, timeout=300, cwd=REPO,
    )


def _tail(proc: subprocess.CompletedProcess) -> str:
    lines = (proc.stderr or proc.stdout).strip().splitlines()
    return lines[-1] if lines else "no output"


# ---------------------------------------------------------------------------------------
# YAML emission — small and local. The cube files are simple mappings; a hand-rolled
# emitter keeps this script standard-library like every other emitter in scripts/.
# ---------------------------------------------------------------------------------------


# Plain scalars YAML 1.1 loads as something other than a string. `on` becomes True,
# `no` becomes False, `~` becomes null — and a column literally named `no` exists in the
# wild (Norwegian country codes).
_YAML_SPECIALS = {"true", "false", "yes", "no", "on", "off", "null", "none", "y", "n", "~"}


def _yml_scalar(value: str) -> str:
    """Quote a YAML scalar defensively; identifiers pass through unquoted."""
    if value == "" or value != value.strip():
        return json.dumps(value)
    if value.lower() in _YAML_SPECIALS:
        return json.dumps(value)
    try:  # all-digit and float-ish forms (1.5, 1e3, .inf) must stay strings
        float(value)
        return json.dumps(value)
    except ValueError:
        pass
    plain = all(c.isalnum() or c in "_-." for c in value)
    return value if plain else json.dumps(value)


def view_yaml(name: str, statement: str, description: str,
              props: List[Tuple[str, str]]) -> str:
    """An MDL view file: name + statement (block scalar) + generated marker.

    `source: dbt_metric` is the ownership marker `_generation_owned` matches on, so an
    orphaned view (its metric was renamed or removed) is deleted on the next sync while
    a hand-authored view in the same directory is reported `stale` and never touched.
    """
    lines = [f"name: {_yml_scalar(name)}", "statement: |"]
    for ln in statement.splitlines():
        lines.append(f"  {ln}" if ln.strip() else "")
    lines.append("properties:")
    lines.append(f"  description: {_yml_scalar(description)}")
    lines.append("  source: dbt_metric")
    for key, value in props:
        lines.append(f"  {key}: {_yml_scalar(str(value))}")
    return "\n".join(lines) + "\n"


def _indent(sql: str, pad: str = "  ") -> str:
    return "\n".join(pad + ln if ln.strip() else "" for ln in sql.splitlines())


# ---------------------------------------------------------------------------------------
# Enrichment content
# ---------------------------------------------------------------------------------------


def concepts_markdown(index: Dict[str, Any], slug: str) -> Optional[str]:
    concepts = index.get("concepts") or []
    if not concepts:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Ontology concepts", ""]
    lines += [
        "Business concepts this use-case's ontology defines, and which connectors supply",
        "each one. A concept named here is the conformed entity; the dbt models that",
        "implement it per connector are listed in `column-contracts.md`.", "",
    ]
    for c in sorted(concepts, key=lambda x: x.get("concept", "")):
        implemented = ", ".join(sorted(c.get("implemented_by") or [])) or "none yet"
        planned = ", ".join(sorted(c.get("planned_by") or []))
        line = f"- **{c.get('concept')}** ({c.get('core_class', '?')}) — implemented by: {implemented}"
        if planned:
            line += f"; planned: {planned}"
        lines.append(line)
    gaps = index.get("gaps") or []
    if gaps:
        lines += ["", "## Coverage gaps", ""]
        for g in sorted(gaps, key=lambda x: x.get("concept", "")):
            lines.append(f"- {g.get('concept')}: {g.get('reason')}")
    return "\n".join(lines) + "\n"


def contracts_markdown(memory: Dict[str, Any], slug: str) -> Optional[str]:
    contracts = memory.get("contracts") or []
    if not contracts:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Column contracts", ""]
    lines += [
        "Conformed column lists per concept, derived from parsed column lineage across",
        "every connector's adapter model. When writing SQL against a conformed concept,",
        "these are the column names that exist on every supplier.", "",
    ]
    for c in sorted(contracts, key=lambda x: x.get("concept", "")):
        adapters = c.get("adapters") or {}
        supplier_note = ", ".join(
            f"{k} ({v})" for k, v in sorted(adapters.items())
        )
        lines.append(f"## {c.get('concept')}")
        lines.append("")
        if supplier_note:
            lines.append(f"Suppliers: {supplier_note}")
        conformed = c.get("conformed") or []
        if conformed:
            lines.append(f"Conformed columns ({len(conformed)}): " + ", ".join(conformed))
        partial = c.get("partial_for") or []
        if partial:
            lines.append(
                f"Partial (macro-generated column list, cannot be fully named): "
                + ", ".join(sorted(partial))
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def drift_markdown(memory: Dict[str, Any], slug: str) -> Optional[str]:
    drift = memory.get("drift") or []
    if not drift:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Adapter column drift", ""]
    lines += [
        "Known disagreements between connector adapters that supply the same concept.",
        "SQL that unions or compares across these connectors must account for them.", "",
    ]
    for d in sorted(drift, key=lambda x: (x.get("concept", ""), x.get("column", ""))):
        missing = ", ".join(sorted(d.get("missing_from") or [])) or "-"
        carried = ", ".join(sorted(d.get("carried_by") or [])) or "-"
        lines.append(
            f"- **{d.get('concept')}.{d.get('column')}** ({d.get('confidence')}) — "
            f"carried by: {carried}; missing from: {missing}"
        )
    return "\n".join(lines) + "\n"


def metrics_markdown(man: Manifest, slug: str) -> Optional[str]:
    metrics = man.metrics
    if not metrics:
        return None
    lines = [GENERATED_HEADER.format(slug=slug), "", "# Semantic-layer metrics", ""]
    lines += [
        "Metric definitions from the dbt semantic layer (MetricFlow). These are the",
        "canonical definitions — a query answering a metric question should reproduce",
        "the definition below, not invent a variant (one metric, one definition).", "",
        "Each metric that compiles is also an MDL **view** of the same name:",
        "`SELECT * FROM <metric>` through the engine returns the governed series",
        "(metric_time, value). Prefer the view over re-deriving the SQL.", "",
    ]
    for key in sorted(metrics):
        m = metrics[key]
        name = m.get("name", key)
        lines.append(f"## {name}")
        lines.append("")
        label = m.get("label")
        if label and label != name:
            lines.append(f"Label: {label}")
        lines.append(f"Type: {m.get('type', '?')}")
        desc = " ".join((m.get("description") or "").split())
        if desc:
            lines.append(f"Definition: {desc}")
        params = m.get("type_params") or {}
        expr = params.get("expr")
        if expr:
            lines.append(f"Formula: `{expr}`")
        num, den = params.get("numerator"), params.get("denominator")
        if num or den:
            # A ratio leg can carry its own filter and alias — emea_revenue_share's
            # numerator is revenue *filtered to EMEA*. Dropping that renders the metric
            # as revenue/revenue, a wrong definition presented as canonical.
            lines.append(f"Ratio: {_metric_ref(num)} / {_metric_ref(den)}")
        flt = _filter_sql(m.get("filter"))
        if flt:
            lines.append(f"Filter: `{flt}`")
        lines.append("")
    return "\n".join(lines) + "\n"


def _filter_sql(flt: Any) -> str:
    """Flatten MetricFlow's filter shapes to the SQL templates they carry."""
    if not flt:
        return ""
    if isinstance(flt, dict):
        templates = [
            w.get("where_sql_template", "") for w in flt.get("where_filters", [])
            if isinstance(w, dict)
        ]
        flt = " AND ".join(t for t in templates if t) or flt.get("where_sql_template", "")
    return " ".join(str(flt).split())


def _metric_ref(side: Any) -> str:
    if not isinstance(side, dict):
        return f"`{side}`"
    ref = f"`{side.get('name', '?')}`"
    leg_filter = _filter_sql(side.get("filter"))
    if leg_filter:
        ref += f" filtered by `{leg_filter}`"
    if side.get("alias"):
        ref += f" (as {side['alias']})"
    return ref


def _model_name(man: Manifest, unique_id: str) -> str:
    """The model's declared name — from the manifest node, never the unique_id.

    A versioned model's unique_id is `model.<pkg>.<name>.v<version>`, so splitting the
    id string yields `v2` as the "name". The node's own `name` field is what the wrenai
    importer emits as the Wren model name, so it is the only join key that holds.
    """
    node = man.all_nodes().get(unique_id) or {}
    return node.get("name") or unique_id.rsplit(".", 1)[-1]


class _SemanticIndex:
    """Resolved lookups over the manifest's semantic layer and the warehouse catalog.

    Built once per generation. Everything a compiler needs to turn a metric into SQL —
    which semantic model a measure lives on, which single dbt model that sits on, the
    catalog type of a column, which model is the time spine — resolved here so each
    metric compiler stays a straight-line SQL builder.
    """

    def __init__(self, man: Manifest, catalog: Dict[str, Any]) -> None:
        self.man = man
        self._cat: Dict[str, Dict[str, str]] = {
            uid: {
                c.lower(): (meta or {}).get("type", "")
                for c, meta in ((node or {}).get("columns") or {}).items()
            }
            for uid, node in (catalog.get("nodes") or {}).items()
        }
        self.sms: Dict[str, Dict[str, Any]] = {}
        self.sm_model: Dict[str, Optional[Tuple[str, str]]] = {}
        self.measure_sm: Dict[str, str] = {}
        self.primary_entity: Dict[str, str] = {}
        for key in sorted(man.semantic_models):
            sm = man.semantic_models[key]
            name = sm.get("name") or key.rsplit(".", 1)[-1]
            self.sms[name] = sm
            model_ids = [u for u in (sm.get("depends_on") or {}).get("nodes", [])
                         if u.startswith("model.")]
            self.sm_model[name] = (
                (model_ids[0], _model_name(man, model_ids[0]))
                if len(model_ids) == 1 else None
            )
            for m in sm.get("measures") or []:
                self.measure_sm.setdefault(m.get("name", ""), name)
            for e in sm.get("entities") or []:
                if (e.get("type") or "").lower() == "primary":
                    self.primary_entity.setdefault(e.get("name", ""), name)
        self.metrics: Dict[str, Dict[str, Any]] = {}
        for key in sorted(man.metrics):
            m = man.metrics[key]
            self.metrics[m.get("name") or key.rsplit(".", 1)[-1]] = m
        # The time spine comes from the manifest's own declaration
        # (`time_spine.standard_granularity_column` on a model) — never from a
        # name convention (rule 5). No declaration means cumulative metrics and
        # timespine fills are skipped and counted, not guessed.
        self.spine: Optional[Tuple[str, str]] = None
        for uid in sorted(man.models()):
            ts = man.models()[uid].get("time_spine")
            if isinstance(ts, dict) and ts.get("standard_granularity_column"):
                self.spine = (_model_name(man, uid), ts["standard_granularity_column"])
                break

    def catalog_type(self, model_uid: str, column: str) -> Optional[str]:
        return self._cat.get(model_uid, {}).get(column.strip().lower())

    def model_in_catalog(self, model_uid: str) -> bool:
        return bool(self._cat.get(model_uid))


def _typed_column(idx: _SemanticIndex, model_uid: str, model: str, expr: str) -> str:
    """Qualify a bare column and make its type visible to the planner.

    wren-core's `map_data_type` matches `decimal`/`numeric` as exact strings, so a
    parameterized `DECIMAL(28, 6)` from the catalog registers as Utf8 and any aggregate
    over it fails to plan *inside a view statement* (model queries never plan the user's
    aggregate, which is why the importer's output works unchanged). CAST to the column's
    own catalog type is a no-op at execution and correct at planning. Fix staged at
    external/patches/; measured on example-order-revenue-mart.

    Non-bare expressions pass through untouched: their component columns are the model's
    own and the planner infers from them.
    """
    if not _BARE_COLUMN.match(expr):
        return expr
    ctype = idx.catalog_type(model_uid, expr) or ""
    base = ctype.split("(")[0].strip().lower()
    if "(" in ctype and base in ("decimal", "numeric"):
        return f"CAST({model}.{expr} AS {ctype.replace(' ', '')})"
    return f"{model}.{expr}"


def _resolve_dim(idx: _SemanticIndex, base_sm_name: str, entity: str,
                 dim_name: str) -> Tuple[Optional[str], Optional[Tuple[str, str]], Optional[str]]:
    """Resolve `entity__dim` to (sql_expr, join_or_None, err).

    Same-model dimensions qualify against the base model. A foreign dimension joins
    through the base semantic model's foreign entity of the same name — MetricFlow's
    own join rule — and anything that cannot be resolved that way is an error the
    caller turns into a skip, never a guess.
    """
    target_sm_name = idx.primary_entity.get(entity)
    if not target_sm_name:
        return None, None, f"no semantic model has primary entity '{entity}'"
    sm = idx.sms[target_sm_name]
    dim = next((d for d in sm.get("dimensions") or [] if d.get("name") == dim_name), None)
    if dim is None:
        return None, None, f"dimension '{dim_name}' not on semantic model '{target_sm_name}'"
    expr = (dim.get("expr") or dim.get("name") or "").strip()
    tinfo = idx.sm_model.get(target_sm_name)
    if not tinfo:
        return None, None, f"semantic model '{target_sm_name}' does not sit on exactly one model"
    _, tmodel = tinfo
    col = f"{tmodel}.{expr}" if _BARE_COLUMN.match(expr) else expr
    if target_sm_name == base_sm_name:
        return col, None, None
    base = idx.sms[base_sm_name]
    fk = next((e for e in base.get("entities") or []
               if e.get("name") == entity and (e.get("type") or "").lower() == "foreign"), None)
    if fk is None:
        return None, None, f"'{base_sm_name}' has no foreign entity '{entity}' to join through"
    pk = next((e for e in sm.get("entities") or []
               if e.get("name") == entity and (e.get("type") or "").lower() == "primary"), None)
    binfo = idx.sm_model.get(base_sm_name)
    if not binfo or pk is None:
        return None, None, f"cannot derive the join for entity '{entity}'"
    fk_expr = (fk.get("expr") or fk.get("name") or "").strip()
    pk_expr = (pk.get("expr") or pk.get("name") or "").strip()
    join = (tmodel, f"{binfo[1]}.{fk_expr} = {tmodel}.{pk_expr}")
    return col, join, None


def _render_filter(idx: _SemanticIndex, base_sm_name: str,
                   flt: Any) -> Tuple[Optional[str], List[Tuple[str, str]], Optional[str]]:
    """MetricFlow where-template -> (sql, joins, err). Empty filter -> ("", [], None)."""
    raw = _filter_sql(flt)
    if not raw:
        return "", [], None
    joins: List[Tuple[str, str]] = []
    errs: List[str] = []

    def sub(m: "re.Match[str]") -> str:
        col, join, err = _resolve_dim(idx, base_sm_name, m.group(1), m.group(2))
        if err:
            errs.append(err)
            return m.group(0)
        if join and join not in joins:
            joins.append(join)
        return col or m.group(0)

    sql = _DIM_REF.sub(sub, raw)
    if errs:
        return None, [], "; ".join(errs)
    if "{{" in sql:
        return None, [], f"unsupported template in filter: {raw}"
    return sql, joins, None


def _grouped_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any], value_alias: str,
                        grain: Optional[str] = None,
                        dims: Tuple[Tuple[str, str, str], ...] = (),
                        extra_filters: Tuple[Any, ...] = (),
                        timespine: bool = True,
                        ) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """The core builder: a simple metric as (metric_time[, dims], AGG) SQL.

    Everything else composes it — ratio legs, derived inputs, the cumulative daily
    series, and saved-query cuts all reduce to this with a grain override, extra
    dimensions, or extra filters.

    `dims` entries are (alias, entity, dim_name). With no dims, a measure that declares
    `join_to_timespine` gets the spine join and its `fill_nulls_with`, bounded to the
    observed data range; with dims the fill is not applied (a per-combination fill needs
    the dimension domain, which SQL from one model cannot know) and `meta["filled"]`
    says so — visible, not silent.
    """
    tp = metric.get("type_params") or {}
    mref = tp.get("measure") or {}
    mname = mref.get("name") or ""
    sm_name = idx.measure_sm.get(mname)
    if not sm_name:
        return None, None, f"measure '{mname}' not on any semantic model"
    sm = idx.sms[sm_name]
    minfo = idx.sm_model.get(sm_name)
    if not minfo:
        return None, None, f"semantic model '{sm_name}' does not sit on exactly one model"
    model_uid, model = minfo
    if not idx.model_in_catalog(model_uid):
        return None, None, f"{model} not in catalog.json — dbt docs generate"
    measure = next((m for m in sm.get("measures") or [] if m.get("name") == mname), None)
    agg = ((measure or {}).get("agg") or "").lower()
    template = AGG_SQL.get(agg)
    if not template:
        return None, None, f"no faithful SQL for agg '{agg}'"
    agg_sql = template.format(
        x=_typed_column(idx, model_uid, model, (measure.get("expr") or mname).strip())
    )

    td_name = measure.get("agg_time_dimension") or (sm.get("defaults") or {}).get("agg_time_dimension")
    td = next((d for d in sm.get("dimensions") or [] if d.get("name") == td_name), None)
    if td is None:
        return None, None, f"agg_time_dimension '{td_name}' not found on '{sm_name}'"
    t_expr = (td.get("expr") or td.get("name") or "").strip()
    if _BARE_COLUMN.match(t_expr):
        t_expr = f"{model}.{t_expr}"
    g = grain or ((td.get("type_params") or {}).get("time_granularity") or "day")

    joins: List[Tuple[str, str]] = []
    where: List[str] = []
    for f in (metric.get("filter"), mref.get("filter"), *extra_filters):
        sql_f, f_joins, err = _render_filter(idx, sm_name, f)
        if err:
            return None, None, err
        if sql_f:
            where.append(f"({sql_f})")
            for j in f_joins:
                if j not in joins:
                    joins.append(j)
    dim_cols: List[Tuple[str, str]] = []
    for alias, entity, dname in dims:
        col, join, err = _resolve_dim(idx, sm_name, entity, dname)
        if err:
            return None, None, err
        if join and join not in joins:
            joins.append(join)
        dim_cols.append((alias, col or ""))

    select = [f"date_trunc('{g}', {t_expr}) AS metric_time"]
    select += [f"{col} AS {alias}" for alias, col in dim_cols]
    select.append(f"{agg_sql} AS {value_alias}")
    frm = model
    for jmodel, cond in joins:
        frm += f"\n  JOIN {jmodel} ON {cond}"
    sql = "SELECT " + ",\n       ".join(select) + f"\nFROM {frm}"
    if where:
        sql += "\nWHERE " + "\n  AND ".join(where)
    sql += "\nGROUP BY " + ", ".join(str(i + 1) for i in range(1 + len(dim_cols)))

    filled = False
    if timespine and not dims and mref.get("join_to_timespine") and idx.spine:
        spine_model, spine_col = idx.spine
        fill = mref.get("fill_nulls_with")
        value = (f"COALESCE(base.{value_alias}, {fill})" if fill is not None
                 else f"base.{value_alias}")
        sql = (
            f"WITH base AS (\n{_indent(sql)}\n),\n"
            f"spine AS (\n"
            f"  SELECT DISTINCT date_trunc('{g}', CAST({spine_col} AS TIMESTAMP)) AS metric_time\n"
            f"  FROM {spine_model}\n"
            f")\n"
            f"SELECT spine.metric_time, {value} AS {value_alias}\n"
            f"FROM spine LEFT JOIN base ON base.metric_time = spine.metric_time\n"
            f"WHERE spine.metric_time BETWEEN (SELECT MIN(metric_time) FROM base)\n"
            f"                            AND (SELECT MAX(metric_time) FROM base)"
        )
        filled = True
    return sql, {"grain": g, "filled": filled}, None


def _ratio_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any], name: str,
                      grain: Optional[str] = None,
                      dims: Tuple[Tuple[str, str, str], ...] = (),
                      extra_filters: Tuple[Any, ...] = (),
                      ) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """Ratio = numerator CTE / denominator CTE joined on the group keys.

    The denominator drives the series (LEFT JOIN) and a missing numerator group is 0,
    not NULL — a day with no EMEA revenue has share 0, it does not vanish.
    """
    tp = metric.get("type_params") or {}
    legs: Dict[str, Tuple[str, Dict[str, Any]]] = {}
    for role, alias in (("numerator", "num"), ("denominator", "den")):
        ref = tp.get(role)
        if not isinstance(ref, dict) or not ref.get("name"):
            return None, None, f"{role} is not a metric reference"
        base = idx.metrics.get(ref["name"])
        if not base:
            return None, None, f"{role} metric '{ref['name']}' not found"
        if (base.get("type") or "").lower() != "simple":
            return None, None, f"{role} '{ref['name']}' is not a simple metric"
        sql, meta, err = _grouped_metric_sql(
            idx, base, alias, grain=grain, dims=dims,
            extra_filters=(ref.get("filter"), *extra_filters), timespine=False,
        )
        if err:
            return None, None, f"{role}: {err}"
        legs[role] = (sql or "", meta or {})
    g = legs["denominator"][1].get("grain")
    if legs["numerator"][1].get("grain") != g:
        return None, None, "numerator and denominator compile at different grains"
    keys = ["metric_time"] + [alias for alias, _, _ in dims]
    on = " AND ".join(f"num.{k} IS NOT DISTINCT FROM den.{k}" for k in keys)
    select = [f"den.{k} AS {k}" for k in keys]
    select.append(
        f"CAST(COALESCE(num.num, 0) AS DOUBLE) / NULLIF(CAST(den.den AS DOUBLE), 0) AS {name}"
    )
    sql = (
        f"WITH num AS (\n{_indent(legs['numerator'][0])}\n),\n"
        f"den AS (\n{_indent(legs['denominator'][0])}\n)\n"
        "SELECT " + ",\n       ".join(select) + "\n"
        f"FROM den LEFT JOIN num ON {on}"
    )
    return sql, {"grain": g}, None


def _derived_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any],
                        name: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """Derived metric: one CTE per input (offset inputs shift their metric_time
    forward by the offset, so an equality join lines the periods up), then the
    formula verbatim over the joined value columns."""
    tp = metric.get("type_params") or {}
    expr = tp.get("expr")
    inputs = tp.get("metrics") or []
    if not expr or not inputs:
        return None, None, "derived metric without expr or input metrics"
    grain: Optional[str] = None
    for i in inputs:
        og = (i.get("offset_window") or {}).get("granularity")
        if og and og in _GRAIN_ORDER and (
            grain is None or _GRAIN_ORDER.index(og) > _GRAIN_ORDER.index(grain)
        ):
            grain = og
    ctes: List[Tuple[str, str]] = []
    base_alias: Optional[str] = None
    for i in inputs:
        base = idx.metrics.get(i.get("name") or "")
        if not base:
            return None, None, f"input metric '{i.get('name')}' not found"
        if (base.get("type") or "").lower() != "simple":
            return None, None, f"input '{i.get('name')}' is not a simple metric"
        alias = i.get("alias") or i.get("name") or ""
        sql, meta, err = _grouped_metric_sql(
            idx, base, alias, grain=grain,
            extra_filters=(i.get("filter"),), timespine=False,
        )
        if err:
            return None, None, f"input {alias}: {err}"
        if grain is None:
            grain = (meta or {}).get("grain")
        ow = i.get("offset_window") or {}
        if ow.get("count") and ow.get("granularity"):
            sql = (
                f"SELECT metric_time + INTERVAL '{int(ow['count'])} {ow['granularity']}'"
                f" AS metric_time, {alias}\n"
                f"FROM (\n{_indent(sql or '')}\n) t"
            )
        elif base_alias is None:
            base_alias = alias
        ctes.append((alias, sql or ""))
    base_alias = base_alias or ctes[0][0]
    with_sql = ",\n".join(f"{a} AS (\n{_indent(s)}\n)" for a, s in ctes)
    frm = base_alias
    for a, _ in ctes:
        if a != base_alias:
            frm += f"\n  LEFT JOIN {a} ON {a}.metric_time = {base_alias}.metric_time"
    sql = (
        f"WITH {with_sql}\n"
        f"SELECT {base_alias}.metric_time,\n"
        f"       ({expr}) AS {name}\n"
        f"FROM {frm}"
    )
    return sql, {"grain": grain or "day"}, None


def _cumulative_metric_sql(idx: _SemanticIndex, metric: Dict[str, Any],
                           name: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """Cumulative metric: daily series x time spine, windowed by a join condition.

    A join range, not a window frame: `RANGE INTERVAL` frames are the one piece of this
    SQL whose planner support varies, and the join form means the statement only needs
    joins, aggregates, and interval arithmetic — which both the planner and every
    target dialect here handle.
    """
    tp = metric.get("type_params") or {}
    ctp = tp.get("cumulative_type_params") or {}
    window, g2d = ctp.get("window"), ctp.get("grain_to_date")
    if not idx.spine:
        return None, None, ("no time spine — declare time_spine.standard_granularity_column "
                            "on a model")
    if bool(window) == bool(g2d):
        return None, None, "cumulative needs exactly one of window / grain_to_date"
    inner = {"type_params": {"measure": tp.get("measure")}, "filter": metric.get("filter")}
    sql, _, err = _grouped_metric_sql(idx, inner, "v", grain="day", timespine=False)
    if err:
        return None, None, err
    spine_model, spine_col = idx.spine
    if window:
        cond = (
            f"daily.metric_time > spine.metric_time"
            f" - INTERVAL '{int(window['count'])} {window['granularity']}'\n"
            f"  AND daily.metric_time <= spine.metric_time"
        )
    else:
        cond = (
            f"daily.metric_time >= date_trunc('{g2d}', spine.metric_time)\n"
            f"  AND daily.metric_time <= spine.metric_time"
        )
    out = (
        f"WITH daily AS (\n{_indent(sql or '')}\n),\n"
        f"spine AS (\n"
        f"  SELECT DISTINCT CAST({spine_col} AS TIMESTAMP) AS metric_time\n"
        f"  FROM {spine_model}\n"
        f")\n"
        f"SELECT spine.metric_time, SUM(daily.v) AS {name}\n"
        f"FROM spine LEFT JOIN daily\n"
        f"  ON {cond}\n"
        f"WHERE spine.metric_time BETWEEN (SELECT MIN(metric_time) FROM daily)\n"
        f"                            AND (SELECT MAX(metric_time) FROM daily)\n"
        f"GROUP BY 1"
    )
    return out, {"grain": "day"}, None


def _saved_query_view(idx: _SemanticIndex, sq: Dict[str, Any],
                      name: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
    """A saved query is the dimensional cut the analyst already declared in dbt —
    compile it instead of inventing per-dashboard SQL. One CTE per metric at the
    query's grain and dimensions, joined on the full group key (null-safe, since a
    dimension value can legitimately be NULL)."""
    qp = sq.get("query_params") or {}
    grain: Optional[str] = None
    dims: List[Tuple[str, str, str]] = []
    for gb in qp.get("group_by") or []:
        m = _SQ_TIME.match(gb.strip())
        if m:
            grain = m.group(1)
            continue
        m = _SQ_DIM.match(gb.strip())
        if m:
            dims.append((m.group(2), m.group(1), m.group(2)))
            continue
        return None, None, f"unsupported group_by '{gb}'"
    where = qp.get("where")
    dtuple = tuple(dims)
    ctes: List[Tuple[str, str]] = []
    for mname in qp.get("metrics") or []:
        metric = idx.metrics.get(mname)
        if not metric:
            return None, None, f"metric '{mname}' not found"
        mtype = (metric.get("type") or "").lower()
        if mtype == "simple":
            sql, _, err = _grouped_metric_sql(
                idx, metric, mname, grain=grain, dims=dtuple,
                extra_filters=(where,), timespine=False,
            )
        elif mtype == "ratio":
            sql, _, err = _ratio_metric_sql(
                idx, metric, mname, grain=grain, dims=dtuple, extra_filters=(where,),
            )
        else:
            return None, None, (f"metric '{mname}' is {mtype} — only simple and ratio "
                                "compile into a saved-query view")
        if err:
            return None, None, f"{mname}: {err}"
        ctes.append((mname, sql or ""))
    if not ctes:
        return None, None, "saved query names no metrics"
    keys = ["metric_time"] + [alias for alias, _, _ in dims]
    base = ctes[0][0]
    frm = base
    for a, _ in ctes[1:]:
        on = " AND ".join(f"{a}.{k} IS NOT DISTINCT FROM {base}.{k}" for k in keys)
        frm += f"\n  LEFT JOIN {a} ON {on}"
    select = [f"{base}.{k} AS {k}" for k in keys]
    select += [f"{a}.{a} AS {a}" for a, _ in ctes]
    with_sql = ",\n".join(f"{a} AS (\n{_indent(s)}\n)" for a, s in ctes)
    sql = (
        f"WITH {with_sql}\n"
        "SELECT " + ",\n       ".join(select) + "\n"
        f"FROM {frm}"
    )
    return sql, {"grain": grain or "day"}, None


def build_metric_views(man: Manifest, catalog: Dict[str, Any],
                       slug: str) -> Tuple[Dict[str, str], List[str]]:
    """One MDL view per MetricFlow metric and saved query.

    The view *is* the metric: same name, full definition (filter, ratio, offset,
    window) compiled to SQL the engine plans and `wren context validate` dry-plans
    with no warehouse. A metric whose type or parameters have no faithful
    compilation is skipped and counted — never approximated (rule 5).
    """
    idx = _SemanticIndex(man, catalog)
    model_names = {_model_name(man, uid) for uid in man.models()}
    views: Dict[str, str] = {}
    skipped: List[str] = []

    def emit(name: str, kind: str,
             result: Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]],
             description: str) -> None:
        sql, meta, err = result
        if err:
            skipped.append(f"{name}: {err}")
            return
        if name in model_names:
            skipped.append(f"{name}: collides with a model name — rename the metric")
            return
        if name in views:
            skipped.append(f"{name}: duplicate view name")
            return
        props: List[Tuple[str, str]] = [
            ("metric_type", kind), ("grain", str((meta or {}).get("grain") or "day")),
        ]
        views[name] = view_yaml(name, sql or "", description, props)

    for name in sorted(idx.metrics):
        metric = idx.metrics[name]
        mtype = (metric.get("type") or "").lower()
        desc = " ".join((metric.get("description") or "").split()) or (
            f"dbt metric '{name}' ({mtype})."
        )
        if mtype == "simple":
            emit(name, "simple", _grouped_metric_sql(idx, metric, name), desc)
        elif mtype == "ratio":
            emit(name, "ratio", _ratio_metric_sql(idx, metric, name), desc)
        elif mtype == "derived":
            emit(name, "derived", _derived_metric_sql(idx, metric, name), desc)
        elif mtype == "cumulative":
            emit(name, "cumulative", _cumulative_metric_sql(idx, metric, name), desc)
        else:
            skipped.append(f"{name}: metric type '{mtype}' has no faithful view compilation")
    for key in sorted(man.saved_queries):
        sq = man.saved_queries[key]
        name = sq.get("name") or key.rsplit(".", 1)[-1]
        desc = " ".join((sq.get("description") or "").split()) or (
            f"dbt saved query '{name}'."
        )
        emit(name, "saved_query", _saved_query_view(idx, sq, name), desc)
    return views, skipped


# ---------------------------------------------------------------------------------------
# Generation and diffing
# ---------------------------------------------------------------------------------------


@contextlib.contextmanager
def _model_level_tests_hidden(dbt_project: Path, man: Manifest) -> Iterator[None]:
    """Hide model-level test rows from run_results.json for the duration of the import.

    wrenai 0.13.2's importer sorts its test events by `(model, column)` and a dbt test
    with no column — a singular test, a model-level dbt_utils test — carries
    `column_name: None`, so the sort compares None to str and the whole import dies
    (wren/dbt.py:1201; fix staged at external/patches/). Dropping run_results.json
    entirely would also dodge it, but it takes the `dbt_test_status: verified` column
    enrichment with it. So only the rows the importer cannot sort are filtered, the
    original file is set aside under a distinct name, and it is restored no matter how
    the import exits.
    """
    rr = dbt_project / "target" / "run_results.json"
    backup = rr.with_suffix(".json.wren-sync-orig")
    # A finally clause does not run on SIGKILL. If a previous run was killed inside the
    # window, the sanitized copy (or nothing) is on disk and the original is stranded at
    # the backup name — heal that first, before reading, and never let a fresh rename
    # clobber the stranded copy silently.
    if backup.exists():
        backup.replace(rr)
    if not rr.exists():
        yield
        return
    columnless = {
        uid for uid, node in man.tests().items() if node.get("column_name") is None
    }
    data = load_json(str(rr), "run_results")
    kept = [r for r in data.get("results", []) if r.get("unique_id") not in columnless]
    if len(kept) == len(data.get("results", [])):
        yield
        return
    rr.rename(backup)
    try:
        rr.write_text(json.dumps({**data, "results": kept}), encoding="utf-8")
        yield
    finally:
        rr.unlink(missing_ok=True)
        backup.rename(rr)


def generate(cli: str, use_case: Path, slug: str, manifest_path: Path,
             catalog_path: Path, scratch: Path) -> Dict[str, Any]:
    """Run importer + enrichment into `scratch`; return generation stats."""
    if scratch.exists():
        shutil.rmtree(scratch)
    scratch.mkdir(parents=True)

    dbt_project = use_case / "dbt_project"
    man = Manifest.load(str(manifest_path))
    init = run_wren(cli, ["context", "init", "--empty", "--path", str(scratch)])
    if init.returncode != 0:
        die(f"wren context init failed: {_tail(init)}")
    with _model_level_tests_hidden(dbt_project, man):
        imp = run_wren(cli, [
            "context", "import", "dbt",
            "--project-dir", str(dbt_project),
            "--profiles-path", str(dbt_project / "profiles.yml"),
            "--path", str(scratch), "--force",
        ])
    if imp.returncode != 0:
        die(f"wren context import dbt failed: {_tail(imp)}")

    catalog = load_json(str(catalog_path), "catalog")

    knowledge_written = 0
    for rel, content in (
        ("knowledge/rules/ontology-concepts.md",
         concepts_markdown(_optional_json(use_case / "ontology/index.json"), slug)),
        ("knowledge/rules/column-contracts.md",
         contracts_markdown(_optional_json(use_case / "ontology/column-memory.json"), slug)),
        ("knowledge/caveats/adapter-drift.md",
         drift_markdown(_optional_json(use_case / "ontology/column-memory.json"), slug)),
        ("knowledge/rules/semantic-metrics.md", metrics_markdown(man, slug)),
    ):
        if content is None:
            continue
        target = scratch / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        knowledge_written += 1

    views, views_skipped = build_metric_views(man, catalog, slug)
    for name, content in sorted(views.items()):
        target = scratch / "views" / name / "metadata.yml"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    (scratch / ".gitignore").write_text("target/\n.wren/\n", encoding="utf-8")

    validate = run_wren(cli, ["context", "validate", "--path", str(scratch)])
    if validate.returncode != 0:
        die(f"wren context validate failed: {_tail(validate)}")
    warnings = sum(
        1 for ln in validate.stdout.splitlines() if ln.strip().lower().startswith("warning")
    )
    build = run_wren(cli, ["context", "build", "--path", str(scratch)])
    if build.returncode != 0:
        die(f"wren context build failed: {_tail(build)}")
    # Build output validated, then discarded: target/ is derived state and stays out of
    # the committed tree — a fresh clone rebuilds it with one command.
    shutil.rmtree(scratch / "target", ignore_errors=True)

    models = sum(1 for _ in scratch.glob("models/*/metadata.yml"))
    relationships = 0
    rel_file = scratch / "relationships.yml"
    if rel_file.exists():
        relationships = sum(
            1 for ln in rel_file.read_text(encoding="utf-8").splitlines()
            if ln.startswith("- name:")
        )
    return {
        "models": models,
        "relationships": relationships,
        "views": len(views),
        "views_skipped": sorted(views_skipped),
        "knowledge_files": knowledge_written,
        "validate_warnings": warnings,
    }


def _optional_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    return load_json(str(path), path.name)


def _tree(root: Path) -> Dict[str, bytes]:
    files: Dict[str, bytes] = {}
    if not root.exists():
        return files
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if rel.parts and rel.parts[0] in UNTOUCHED_DIRS:
            continue
        files[str(rel)] = p.read_bytes()
    return files


# Paths the generation pipeline owns wholesale — a stale file here is an orphan of a
# renamed or deleted dbt node, not somebody's hand work. `cubes/` stays listed although
# nothing generates cubes any more: committed trees still carry them from before metrics
# compiled to views, and the prefix is what lets the first regeneration delete them as
# the orphans they now are. `views/` is deliberately NOT here — generated views are
# owned by their `source: dbt_metric` marker, so a hand-authored view in the same
# directory is reported `stale` and never touched.
_OWNED_PREFIXES = ("models/", "cubes/")
_OWNED_FILES = {"wren_project.yml", "relationships.yml", "AGENTS.md", ".gitignore"}


def _generation_owned(rel: str, blob: bytes) -> bool:
    if rel in _OWNED_FILES or rel.startswith(_OWNED_PREFIXES):
        return True
    # Knowledge files are shared ground: the importer's and this script's carry markers;
    # anything else there is hand-authored context (including `wren memory store` pairs).
    text = blob.decode("utf-8", errors="replace")
    return (
        "Generated by scripts/wren_context_sync.py" in text
        or "source: dbt" in text  # importer-seeded NL->SQL pairs and rules
    )


def diff_and_sync(scratch: Path, target: Path,
                  check: bool) -> Tuple[List[str], List[str], List[str]]:
    """Returns (changed, deleted, kept_stale).

    `deleted` is generation-owned orphans — a cube whose semantic model was removed, a
    model dir for a renamed dbt node. Leaving them would ship a committed tree that
    references dropped tables while `--check` stays green, so they count as changes and
    are removed on sync. `kept_stale` is everything else: hand-authored files, reported
    and never touched.
    """
    generated, committed = _tree(scratch), _tree(target)
    changed = sorted(
        rel for rel, blob in generated.items() if committed.get(rel) != blob
    )
    stale = sorted(set(committed) - set(generated))
    deleted = [rel for rel in stale if _generation_owned(rel, committed[rel])]
    kept_stale = [rel for rel in stale if rel not in set(deleted)]
    if not check:
        for rel in changed:
            dest = target / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(generated[rel])
        for rel in deleted:
            (target / rel).unlink(missing_ok=True)
    return changed, deleted, kept_stale


# ---------------------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------------------


def sync(slug: str, manifest_arg: Optional[str], check: bool) -> Dict[str, Any]:
    use_case = use_case_dir(slug)
    if not use_case:
        die(f"no such use-case under skill-packs/*/use-cases/: {slug}")

    payload: Dict[str, Any] = {"use_case": slug, "status": "skip"}

    if not (use_case / "dbt_project").exists():
        payload["reason"] = "no dbt_project yet"
        return payload
    default_manifest = use_case / "dbt_project/target/manifest.json"
    manifest_path = Path(manifest_arg) if manifest_arg else default_manifest
    # The wrenai importer always reads <dbt_project>/target/ itself; honoring a foreign
    # --manifest here would sanitize and enrich from one manifest while the importer
    # reads another — two internally consistent halves of different generations.
    if manifest_arg and manifest_path.resolve() != default_manifest.resolve():
        payload["reason"] = (
            "--manifest points outside dbt_project/target/ — the wren importer reads "
            "the project's own target; re-run dbt parse there instead"
        )
        return payload
    if not manifest_path.exists():
        payload["reason"] = "no manifest — dbt parse (or artifacts/refresh.sh)"
        return payload
    catalog_path = manifest_path.parent / "catalog.json"
    if not catalog_path.exists():
        payload["reason"] = "no catalog.json — dbt docs generate against the local target"
        return payload
    cli = find_wren_cli()
    if not cli:
        payload["reason"] = "wren CLI not installed — pip install -r requirements.txt"
        return payload

    scratch = use_case / ".wren.tmp"
    try:
        stats = generate(cli, use_case, slug, manifest_path, catalog_path, scratch)
        changed, deleted, stale = diff_and_sync(scratch, use_case / "wren", check)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    payload.update(stats)
    payload["status"] = "changed" if (changed or deleted) else "ok"
    payload["changed"] = changed
    payload["deleted"] = deleted
    payload["stale"] = stale
    return payload


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate the WrenAI semantic-layer project for a use-case: "
                    "native dbt import plus ontology/contract/metric enrichment.",
    )
    p.add_argument("--use-case", required=True, help="slug under skill-packs/*/use-cases/")
    p.add_argument("--manifest", help="manifest.json (default: <project>/target/manifest.json)")
    p.add_argument("--check", action="store_true",
                   help="write nothing; report what would change")
    p.add_argument("--format", choices=("text", "json"), default="text")
    args = p.parse_args(argv)

    payload = sync(args.use_case, args.manifest, args.check)

    if args.format == "json":
        print(json.dumps(payload, ensure_ascii=False))
    else:
        status = payload["status"]
        if status == "skip":
            print(f"skip  {payload['use_case']}: {payload['reason']}")
        else:
            print(
                f"{status:<5} {payload['use_case']}: {payload.get('models', 0)} models, "
                f"{payload.get('relationships', 0)} relationships, "
                f"{payload.get('views', 0)} metric views, "
                f"{payload.get('knowledge_files', 0)} knowledge files, "
                f"{payload.get('validate_warnings', 0)} validate warning(s)"
            )
            for rel in payload.get("changed", []):
                print(f"  changed  wren/{rel}")
            for rel in payload.get("deleted", []):
                print(f"  deleted  wren/{rel} (generation-owned orphan)")
            for rel in payload.get("stale", []):
                print(f"  stale    wren/{rel} (hand-authored; left alone)")
            skipped = payload.get("views_skipped", [])
            if skipped:
                print(f"  {len(skipped)} metric(s) skipped rather than approximated:")
                for reason in skipped[:10]:
                    print(f"    - {reason}")

    if payload["status"] == "changed" and args.check:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
