{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox', 'seventime'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_offers`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.OrderReference
    , d0.InvoiceReference
    , d0.Currency
    , d0.CurrencyRate
    , d0.Net
    , d0.ContributionValue
    , d0.Comments
    , d0.Country
    , d0.Labels
    , d0.OrgId
    , d0.CustomerId
    , d0.ProjectId
    , d0.CostCenterId
from {{ ref('erp_bi_fact_offers') }} d0
order by 1
