{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox', 'seventime', 'shopify', 'tripletex', 'upsales', 'visma_eaccounting', 'visma_economic'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `dim_customers`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.CustomerId
    , d0.Name
    , d0.OrganisationNumber
    , d0.Address
    , d0.Website
    , d0.isActive
    , d0.Country
    , d0.Comments
    , d0.DefaultTemplate
    , d0.TemplateReference
    , d0.DefaultDeliveryType
    , d0.PriceListId
    , d0.CostCenterId
    , d0.ProjectId
    , d0.FirstInvoiceDate
from {{ ref('erp_bi_dim_customers') }} d0
order by 1
