{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['favrit', 'fortnox', 'shopify', 'upsales'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_order_rows`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.OrderId
    , d0.OrderDate
    , d0.Currency
    , d0.ArticleNumber
    , d0.Description
    , d0.OrderedQuantity
    , d0.isVATIncluded
    , d0.PriceAfterDiscount
    , d0.SalesValue
    , d0.OrderedValue
    , d0.ContributionValue
    , d0.InvoiceReference
    , d0.OrgId
    , d0.ArticleId
    , d0.CustomerId
    , d0.AccountId
    , d0.CostCenterId
    , d0.ProjectId
from {{ ref('erp_bi_fact_order_rows') }} d0
order by 1
