{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox', 'seventime', 'visma_eaccounting', 'visma_economic'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_invoice_rows`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.InvoiceNo
    , d0.InvoiceDate
    , d0.AccountNumber
    , d0.ArticleNumber
    , d0.PriceAfterDiscount
    , d0.SalesValue
    , d0.ContributionValue
    , d0.InvoiceType
    , d0.OrgId
from {{ ref('erp_bi_fact_invoice_rows') }} d0
order by 1
