{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox', 'seventime', 'tempo'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_time_reporting_registrations`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.UserNo
    , d0.UserId
    , d0.StartTime
    , d0.DocumentType
from {{ ref('erp_bi_fact_time_reporting_registrations') }} d0
order by 1
