{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox', 'tripletex', 'visma_eaccounting', 'visma_economic'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_vouchers`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.TransactionDate
    , d0.Account
    , d0.Description
    , d0.AccountClass
    , d0.ReferenceNumber
    , d0.ReferenceType
    , d0.OrgId
    , d0.FinancialYearId
    , d0.AccountId
    , d0.CostCenterId
    , d0.ProjectId
    , d0.VoucherSeriesId
    , d0.CustomerId
    , d0.SupplierId
from {{ ref('erp_bi_fact_vouchers') }} d0
order by 1
