{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_stocktakings`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.Name
    , d0.Date
    , d0.OrgId
    , d0.ArticleId
    , d0.StockPointId
    , d0.CostCenterId
    , d0.ProjectId
from {{ ref('erp_bi_fact_stocktakings') }} d0
order by 1
