{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `dim_supplier_invoice_files`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.SupplierInvoiceNo
    , d0.FileName
    , d0.OrgId
from {{ ref('erp_bi_dim_supplier_invoice_files') }} d0
order by 1
