{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox', 'seventime', 'tripletex', 'upsales', 'visma_eaccounting', 'visma_economic'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `dim_company`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.OrgId
    , d0.OrgName
from {{ ref('erp_bi_dim_company') }} d0
order by 1
