{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_budgets`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.OrgId
    , d0.BudgetDate
    , d0.Account
    , d0.Amount
    , d0.AccountId
    , d0.FinancialYearId
    , d0.CostCenterId
from {{ ref('erp_bi_fact_budgets') }} d0
order by 1
