{{ config(
    alias=(model_alias(model.name)),
        enabled = any_source_enabled(['fortnox'])
) }}

-- GENERATED by scripts/ontology_to_dbt.py. Regenerate with:
--   python3 scripts/ontology_to_dbt.py --use-case <slug> --write
--
-- The conformed concept `fact_salary_transactions`, restricted to the columns whose
-- meaning is recorded in ontology/annotations.yml. Columns are enumerated rather
-- than starred (rule 25) so a new upstream column cannot appear here silently.

select
    d0.DataSource
    , d0.OrgId
    , d0.EmployeeId
    , d0.Date
    , d0.SalaryCode
    , d0.NumberOfUnits
    , d0.AmountPerUnit
    , d0.Comments
    , d0.AccountId
    , d0.CostCenterId
    , d0.ProjectId
from {{ ref('erp_bi_fact_salary_transactions') }} d0
order by 1
