version: 2

models:

  - name: fortnox_bi_dim_accounts_staging
  - name: fortnox_erp_bi_dim_accounts
  - name: fortnox_bi_dim_articles_staging
  - name: fortnox_erp_bi_dim_articles
  - name: fortnox_bi_dim_assets_types_staging
  - name: fortnox_bi_dim_bundle_articles_staging
  - name: fortnox_bi_dim_company_staging
  - name: fortnox_erp_bi_dim_company
  - name: fortnox_bi_dim_cost_centers_staging
  - name: fortnox_erp_bi_dim_cost_centers
  - name: fortnox_bi_dim_customers_staging
  - name: fortnox_erp_bi_dim_customers
  - name: fortnox_bi_dim_employees_staging
  - name: fortnox_erp_bi_dim_employees
  - name: fortnox_bi_dim_expenses_staging
  - name: fortnox_bi_dim_financial_years_staging
  - name: fortnox_erp_bi_dim_financial_years
  - name: fortnox_bi_dim_labels_staging
  - name: fortnox_bi_dim_meta_data_staging
  - name: fortnox_bi_dim_pricelists_staging
  - name: fortnox_bi_dim_prices_staging
  - name: fortnox_bi_dim_projects_staging
  - name: fortnox_erp_bi_dim_projects
  - name: fortnox_bi_dim_stockpoints_staging
  - name: fortnox_bi_dim_supplier_invoice_files_staging
  - name: fortnox_erp_bi_dim_supplier_invoice_files
  - name: fortnox_bi_dim_supplier_items_staging
  - name: fortnox_bi_dim_suppliers_staging
  - name: fortnox_erp_bi_dim_suppliers
  - name: fortnox_bi_dim_voucher_series_staging
  - name: fortnox_bi_fact_absence_transactions_staging
  - name: fortnox_erp_bi_fact_absence_transactions
  - name: fortnox_bi_fact_asset_rows_staging
  - name: fortnox_bi_fact_assets_staging
  - name: fortnox_bi_fact_attendance_transactions_staging
  - name: fortnox_erp_bi_fact_attendance_transactions
  - name: fortnox_bi_fact_budgets_staging
  - name: fortnox_erp_bi_fact_budgets
  - name: fortnox_bi_fact_contract_rows_staging
  - name: fortnox_bi_fact_contracts_staging
  - name: fortnox_bi_fact_employee_schedules_staging
  - name: fortnox_bi_fact_employee_wages_staging
  - name: fortnox_bi_fact_incoming_goods_staging
  - name: fortnox_erp_bi_fact_incoming_goods
  - name: fortnox_bi_fact_invoice_accruals_staging
  - name: fortnox_bi_fact_invoice_payments_staging
  - name: fortnox_bi_fact_invoice_rows_staging
  - name: fortnox_erp_bi_fact_invoice_rows
  - name: fortnox_bi_fact_invoices_staging
  - name: fortnox_erp_bi_fact_invoices
  - name: fortnox_bi_fact_locked_period_staging
  - name: fortnox_bi_fact_offer_rows_staging
  - name: fortnox_bi_fact_offers_staging
  - name: fortnox_erp_bi_fact_offers
  - name: fortnox_bi_fact_order_rows_staging
  - name: fortnox_erp_bi_fact_order_rows
  - name: fortnox_bi_fact_orders_staging
  - name: fortnox_erp_bi_fact_orders
  - name: fortnox_bi_fact_production_orders_staging
  - name: fortnox_bi_fact_purchase_orders_staging
  - name: fortnox_erp_bi_fact_purchase_orders
  - name: fortnox_bi_fact_salary_transactions_staging
  - name: fortnox_erp_bi_fact_salary_transactions
  - name: fortnox_bi_fact_stockbalance_staging
  - name: fortnox_erp_bi_fact_stockbalance
  - name: fortnox_bi_fact_stocktakings_staging
  - name: fortnox_erp_bi_fact_stocktakings
  - name: fortnox_bi_fact_supplier_invoice_accruals_staging
  - name: fortnox_bi_fact_supplier_invoice_rows_staging
  - name: fortnox_erp_bi_fact_supplier_invoice_rows
  - name: fortnox_bi_fact_supplier_invoices_staging
  - name: fortnox_erp_bi_fact_supplier_invoices
  - name: fortnox_bi_time_reporting_registrations_staging
  - name: fortnox_erp_bi_fact_time_reporting_registrations
  - name: fortnox_bi_fact_vouchers_staging
  - name: fortnox_erp_bi_fact_vouchers
  - name: fortnox_bi_fact_rolling_sum_staging

  - name: fortnox_flat_article_prices_staging
  - name: fortnox_flat_articles_stockbalance_staging
  - name: fortnox_flat_contract_rows_staging
  - name: fortnox_flat_contracts_staging
  - name: fortnox_flat_incoming_goods_staging
  - name: fortnox_flat_invoice_rows_staging
  - name: fortnox_flat_invoices_staging
  - name: fortnox_flat_offers_staging
  - name: fortnox_flat_order_rows_staging
  - name: fortnox_flat_orders_staging
  - name: fortnox_flat_purchaseorders_staging
  - name: fortnox_flat_supplier_invoice_rows_staging
  - name: fortnox_flat_supplier_invoices_staging
  - name: fortnox_flat_vouchers_staging

  - name: fortnox_reports_balance_sheet_staging
  - name: fortnox_reports_contracts_staging
  - name: fortnox_reports_contribution_suppliers_staging
  - name: fortnox_reports_liquidity_staging
  - name: fortnox_reports_rolling_sum_report_staging
  - name: fortnox_reports_vouchers_budgets_staging
